### ISSUE TITLE
I can't playback via HLS from WOWZA server

### ISSUE THREAD

**Issue by shogo4405** [shogo4405/lf.swift#10]
from https://github.com/shogo4405/lf.swift/issues/9

**Comment by shogo4405** [comment]
iOS HLS must these codecs
* H264 Baseline 3.0 or 3.1, Main 3.1 4.0
* HE-AAC or AAC-LC, stereo

current
* H264 Baseline 2.1
* AAC mono 

I will fix asap!

**Comment by shogo4405** [comment]
Wowza log
2016-02-02	21:07:28	JST	comment	server	INFO	200	-	LiveStreamPacketizerCupertino.handlePacket[live/_definst_/live][mp4a.40.1]: AAC Audio info: {AACFrame: codec:AAC, channels:1, frequency:44100, samplesPerFrame:1024, objectType:Main}	-	-	-	520108.671	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-
2016-02-02	21:07:28	JST	comment	server	INFO	200	-	LiveStreamPacketizerCupertino.handlePacket[live/_definst_/live][avc1.66.21]: H.264 Video info: {H264CodecConfigInfo: codec:H264, profile:Baseline, level:2.1, frameSize:480x272, displaySize:480x272}	-

**Comment by mrbemani** [comment]
um....why the transcoder in wowza cannot transcode it?

**Comment by mrbemani** [comment]
ah....I fixed it. Just leave the framerate and resolution blank in your transcoder, and it will work on ios devices.

**Comment by mrbemani** [comment]
One question. why the resolution and frame interval is constantly changing....

**Comment by mrbemani** [comment]
and NO, set rtmpStream.videoSettings = ["width": 320, "height": 240,"fps": 30] wont fix the resolution.....

**Comment by MingLoan** [comment]
@mrbemani you said you fixed the problem?

**Comment by shogo4405** [comment]
fixed. tested Wowza 4.3
* https://github.com/shogo4405/lf.swift/commit/87eead46b308a5c72b50c278b2a950a7c7c81443
* https://github.com/shogo4405/lf.swift/commit/fadf00141d439ea64adaa09e88581b40f7d72432

H264 Main Profile and RTMPStream.videoSettins["fps"] are next step.

**Comment by mrbemani** [comment]
@MingLoan yep! Just leave "frame interval" and "width, height" blank in your Wowza transcoder. And it will work.

**Comment by MingLoan** [comment]
<img width="1388" alt="screen shot 2016-02-03 at 11 18 49" src="https://cloud.githubusercontent.com/assets/5032142/12771921/f856e336-ca67-11e5-848e-43cc647830fa.png">

fatal error: unexpectedly found nil while unwrapping an Optional value

optional type handling bug founded when publishing!

**Comment by mrbemani** [comment]
how did it happen?

**Comment by MingLoan** [comment]
it is the most updated commit.

**Comment by MingLoan** [comment]
sorry, it should be my problem. Please ignore it.
