### ISSUE TITLE
XCGLogger always crashes

### ISSUE THREAD

**Issue by jeremytregunna** [shogo4405/lf.swift#100]
I'm always getting a crash with XCGLogger, no matter if I try and build it without optimisations, or with. I've also changed versions from 3.3 to 3.5 in the podfile, rebuilt and still no dice. Always crashes at the same spot.

Crashes inside:

`XCGLogger.logDestination(identifier: String) -> XCGLogDestinationProtocol?`

In my AppDelegate I initialise it thusly:

`        XCGLogger.defaultInstance().outputLogLevel = .Info
        XCGLogger.defaultInstance().xcodeColorsEnabled = true`

Have also tried initialising it with all the infos by using .setup, and still nothing gets printed to the screen.

Base SDK 9.3, iOS app, running on an iPhone 6S with 9.3.5.

Any ideas?

**Comment by shogo4405** [comment]
it works for me... I want to more information.
Could you send me your project workspace?
shogo4405 at gmail.com

Regards.

**Comment by jeremytregunna** [comment]
@shogo4405 Just discovered my issue. Xcode being ridiculous, wasn't copying over the new framework file in my copy files build phase, still had an old version of the logger. I can't reproduce once I purge all the things. Closing.
