### ISSUE TITLE
Holidays from 1 Oct to Mid Nov.

### ISSUE THREAD

**Issue by shogo4405** [shogo4405/lf.swift#101]
Hi. I will be in Europe from 1 Oct to Mid Nov.
During this term, I can't develop framework.
I probably won't be able to reply right away. 

Best regards.
---

10月１日〜11月中旬までヨーロッパにいます。
期間中、フレームワークの開発ができません。
また、問い合わせ対応にも遅れます。

よろしくお願いします。

**Comment by bzmario** [comment]
Happy Holidays! Will 0.5.0 be delayed?

**Comment by shogo4405** [comment]
no delay. I will be able to release 17-18 Sep.

**Comment by jianglin612** [comment]
Does this version support Swift3?

**Comment by shogo4405** [comment]
@jianglin612 
Yes. support Swift3.

**Comment by shogo4405** [comment]
I'm waiting for release XCGLogger 4.0.0.
Please wait :)

**Comment by shogo4405** [comment]
@bzmario, @jianglin612 
Released 0.5.0 :)

**Comment by danlniel** [comment]
happy holiday. thanks for your hardwork

**Comment by shogo4405** [comment]
I came back to Japan :)
