### ISSUE TITLE
rtmpStream内への要素追加について

### ISSUE THREAD

**Issue by strikerin5vs5** [shogo4405/lf.swift#102]
日本語で失礼します。
基本的なことかもしれませんが、
rtmpStream内のカメラ映像へのラベル（UILabel）追加について、どうやったら追加できますでしょうか？
また、NSTimerによってアニメーションも考えており、簡単な実装方法を教えていただければと思います。

**Comment by shogo4405** [comment]
* カメラ映像へのラベルの追加
フレームワーク内部の、VisualEffectという仕組みを使って実現します。
現在時刻をとカメラ映像を合成するVisualEffectのサンプル実装が次のURLです。
 - https://github.com/shogo4405/lf.swift/blob/master/Examples/iOS/VisualEffect.swift#L6
>||
// エフェクトを使う場合はGLLFViewを使う。
var view:GLLFView = GLLFView(frame: xxxxx)
rtmpStream.registerEffect(video:  CurrentTimeEffect())
||<

* アニメーションについて
 UIの実装するときにはTimerを使うのですが、カメラ映像にアニメーションをつけるときはTimerを利用しないです。30FPSの設定であれば、0.033秒毎に次の画像が来ます。
 上のCurrenTimeEffect()のラベルを左から右に弾幕のように移動させる考えでいうと、1枚目の画像は、x座標: 0, y座標 0に描画。次の画像は、x座標10, y座標0、次の座標は、x:20, y座標:0に描画...というのを実装すると左から右に流れるアニメーションができます。

**Comment by strikerin5vs5** [comment]
xcode8に上げてから、エラーが出まくってて、返信おそくなりました。。。
タイム表示のラベルのサンプル、理解しました！
ありがとうございました！
