### ISSUE TITLE
Custom Visual Effects

### ISSUE THREAD

**Issue by sherm4n90** [shogo4405/lf.swift#110]
@shogo4405  How VisualEffect works, can I register an effect while streaming and the video will be processed with that filter? Can I make my own VisualEffects? 
Thanks in advance

**Comment by shogo4405** [comment]
> How VisualEffect works

1. use GLLFView
1. RTMPStream.registerEffect(video YourEffects())

try Exsampe-iOS :)

> can I register an effect while streaming ....

Yes.

> Can I make my own VisualEffects?

Yes. Please see https://github.com/shogo4405/lf.swift/blob/master/Examples/iOS/VisualEffect.swift#L64
This VisualEffects architecture is CIFilter base. see also https://developer.apple.com/reference/coreimage/cifilter

**Comment by sherm4n90** [comment]
@shogo4405 I will check it out and let you know. Thanks for your hard work.

**Comment by sherm4n90** [comment]
Hey @shogo4405, the example uses the last version of the framework in Swift 3.0. Is there any way to test it in 0.4.1 version or including the visual effects into my current project so i can use Monochrome and Panorama effects?

**Comment by shogo4405** [comment]
oh... 0.4.x branch is here https://github.com/shogo4405/lf.swift/tree/0.4.x
* VisualEffect Examples 0.4.x is here. https://github.com/shogo4405/lf.swift/blob/0.4.x/Examples/iOS/VisualEffect.swift#L64

```sh
git checkout 0.4.x
```
