### ISSUE TITLE
Library name is not searchable

### ISSUE THREAD

**Issue by alex-vasenin** [shogo4405/lf.swift#113]
Hi,

You library looks very cool and unique, but we spend several _hours_ to actually find it. The name of the library not very search-engine-friendly. **lf** is a cool name, but it's nearly impossible to find anything named like that. LFstreaming or even LFswift (without the dot)?

Thanks,
Alex

**Comment by shogo4405** [comment]
OK. I will change framework name from lf to HaishinKit.
"Live streaming" means "Live Haishin"  in Japanese. lol
