### ISSUE TITLE
What's the best way to use custom capture session with LF for RTMP broadcasting?

### ISSUE THREAD

**Issue by alex-vasenin** [shogo4405/lf.swift#117]
Hello,

As far as I know LF is designed to perform a complete setup of capture session with all inputs, connections and outputs. That's a good thing if you don't want to dive into AVFoundation details, however in our app we already our own highly customized capture session. I want to broadcast audio/video data via RTMP with LF. What's the best way to use LF in this case?

Thanks,
Alex

**Comment by shogo4405** [comment]
in this case, i think best way. framework changes private session property to public
eg. rtmpStream.session. setter/getter

i will change api. when i back Japan.

**Comment by alex-vasenin** [comment]
Well, it's not just session, it's also audio/video inputs, outputs, settings and all that stuff. It's very hard to use LF with external capture infrastructure. Any thoughts how to simplify it?

**Comment by shogo4405** [comment]
well... I think simple way is, add raw level apis. For example.
RTMPStream.appendSampleBuffer(_ sampleBuffer:CMSampleBuffer, mediaType:AVMediaType)
RTMPStream.appendImage(_ image:CIImage, presentationTimeStamp:CMTime)
RTMPStream.appendBytes(_ data:NSData)
