### ISSUE TITLE
Connection timed out after few seconds.

### ISSUE THREAD

**Issue by wasimsafdar** [shogo4405/lf.swift#119]
My RTMP connection timed out after few seconds and I receive following warning.

[Warning] [RTMPSocket.swift:154] didTimeout() > connection timedout

**Comment by shogo4405** [comment]
it seems that your iphone/ipad can't access your server low level network layer.

**Comment by wasimsafdar** [comment]
Yes, but with RTSP protocol it connects to low level network layer and you can stream directly but for RTMP you need to stream to RTMP server. Is there any direct way without using RTMP Server?

**Comment by shogo4405** [comment]
no way. this framework requires a server.
