### ISSUE TITLE
weird crash

### ISSUE THREAD

**Issue by MingLoan** [shogo4405/lf.swift#12]
rtmpStream.videoSettings = [
                    "bitrate": 500 * 1000,
                    "width": 540,
                    "height": 720,
                    "aspectRatio16by9": false,
                ]

if I remove "width": 540, no more crash.

**Comment by shogo4405** [comment]
Please update commits. Then try this code.

import VideoToolbox
rtmpStream.videoSettings = [
"bitrate": 500 * 1000,
"width": 540,
"height": 720,
"profileLevel": kVTProfileLevel_H264_Baseline_3_1, // default kVTProfileLevel_H264_Baseline_3_0
"aspectRatio16by9": false,
]

**Comment by MingLoan** [comment]
thanks.
