### ISSUE TITLE
Class PLBuildVersion: link error

### ISSUE THREAD

**Issue by SKrotkih** [shogo4405/lf.swift#120]
lf.swift 0.5.1, MacOS 10.12, Xcode 8.0, Example iOS,  iPhone 6s simulator:

objc[14524]: Class PLBuildVersion is implemented in both /Applications/Xcode8.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x11812a910) and /Applications/Xcode8.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x117dfd210). One of the two will be used. Which one is undefined.

**Comment by sherm4n90** [comment]
Same here for 0.4.1, Sierra, XCode 8, swift 2.3 in simulators.

**Comment by shogo4405** [comment]
* http://stackoverflow.com/questions/39520499/class-plbuildversion-is-implemented-in-both-frameworks
* 'ALAssetsLibrary' is deprecated: first deprecated in iOS 9.0 - Use PHPhotoLibrary from the Photos framework instead

**Comment by shogo4405** [comment]
Released 0.5.2

**Comment by shogo4405** [comment]
https://forums.developer.apple.com/thread/63254
Apple Staff says:
> Its not a compiler warning, its an Objective-C runtime warning, and it is not in any code that you control. You can safely ignore it, as you cannot fix it.
