### ISSUE TITLE
Background streaming

### ISSUE THREAD

**Issue by sherm4n90** [shogo4405/lf.swift#124]
Any chance of having background streaming feature? I tried with background tasks and it does not work. Thanks.

**Comment by danlniel** [comment]
i hear iOS limit their background time approximately 5m.

**Comment by sherm4n90** [comment]
@danlniel Have you tried broadcasting in background? I know that 5min is the most common background time that sdk provides but I can't make the framework keeps broadcasting after sending the app to background even using background tasks.

**Comment by shogo4405** [comment]
lf framework uses VideoToolkit.
VideoToolkit can't work background.
so, framework not support background mode.

**Comment by San-Jeevan** [comment]
when you go in background mode iOS will not let you access camera.
When it comes to audio, if you add it as background app in the capability, it will work. You can stream audio in background mode :)

**Comment by crossle** [comment]
try recreate VTCompressSession when on background compress failed
