### ISSUE TITLE
Bandwidth property for RTMPConnection

### ISSUE THREAD

**Issue by sherm4n90** [shogo4405/lf.swift#125]
@shogo4405 Any way that I can use the `bandWidth` property in the `RTMPConnection` class.
I want to dynamically check for this property but I have noticed that it never changes. Other way could be allowing to send  an `RTMPSetPeerBandwidthMessage`. Any suggestion? Thanks in advance

**Comment by shogo4405** [comment]
This property is not actually bandwidth. I'm not sure RTMPSetPeerBandwidthMessage X(

Bandwidth detection ways is
1. Client supports onBWCheck and onBWCheck method.
2. Server supports  "check bandwidth" feature.
 -  This feature is optional. Wowza module is here. https://www.wowza.com/forums/content.php?252-How-to-check-bandwidth-from-client-to-server-to-test-uplink-to-be-used-by-a-live-stream-encoder-(ModuleClientBWCheck)
