### ISSUE TITLE
XCODE 8 - SWIFT 3

### ISSUE THREAD

**Issue by pinkladywithcoco** [shogo4405/lf.swift#127]
The project dont work when using xcode 8. Xcode wants the project in swift 3 after convert it dont build and complains about many things...

**Comment by shogo4405** [comment]
Did you resolve it?

**Comment by pinkladywithcoco** [comment]
Hi shogo4405! :-)

- Sadly no... :( still does not work... it will also be better without pods. Pods always have problems in them... please consider it.

**Comment by shogo4405** [comment]
CocoaPods is difficult X( My solution is here.
### Migration XCode7 to XCode8
1. Created a new project by Xcode7 (Swift 2.3)
2. Podfile is
 ```txt
platform :ios, ‘8.0’

target 'Test' do
  use_frameworks!
  pod 'lf', '~> 0.5.0'
end

installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
     config.build_settings['SWIFT_VERSION'] = '3.0'
   end
end
```
4. pod update
5. Open the project by XCode8
6. Migration Swift 2.3 to 3.0

### New Project
1. Create a new project by Xcode8.
2. Podfile is
 ```txt
platform :ios, ‘8.0’

target 'Test' do
  use_frameworks!

  pod 'lf', '~> 0.5.0'

end
```
3. pod update

How about your case?

**Comment by shogo4405** [comment]
frameworks supports Carthage :)
Please consider to use Carthage.
