### ISSUE TITLE
Video did not start for about 20 seconds

### ISSUE THREAD

**Issue by shota-nakamura-recochoku** [shogo4405/lf.swift#132]
When I play to receive a video that was hls delivered in iOS devices in a different iOS devices, it does not start for about 20 seconds playing from the beginning.。
In the case of Android immediately starts playing.

Please tell me how to resolve this problem.

**Comment by shogo4405** [comment]
英語だとすぐ返信てきないので日本語で返しますね。

サーバはwowzaですか？
wowzaだとしたらサーバ側の設定になります。

RTMP→Wowza→HLS→iPhone

という流れだとサーバーの初期設定では30秒程度の遅延、あるいは、スタート開始が遅れます。

サーバーのチューニングが必要です。設定項目、今出先のため確認できません。11月10日頃まで。

**Comment by shogo4405** [comment]
英語だとすぐ返信てきないので日本語で返しますね。

サーバはwowzaですか？
wowzaだとしたらサーバ側の設定になります。

RTMP→Wowza→HLS→iPhone

という流れだとサーバーの初期設定では30秒程度の遅延、あるいは、スタート開始が遅れます。

サーバーの設定項目、今出先のため確認できません。11月10日頃まで。
Wowzaのサポートに問い合わせてみて下さい。

2016/10/25 午前7:31 "shota-nakamura-recochoku" <notifications@github.com>:

**Comment by shota-nakamura-recochoku** [comment]
ご返信ありがとうございます。
日本語で返信記載させていただきます。

＞サーバはwowzaですか？
サーバは、Wowzaです。

＞wowzaだとしたらサーバ側の設定になります。 

iPhone HLS→Wowza→HLS→Android
は、遅延が生じないのですが

iPhone HLS→Wowza→HLS→iPhone
は、遅延が生じております。

このような場合も、Wowzaの設定が関係しますでしょうか？

**Comment by shogo4405** [comment]
はい。このような場合でも設定が関係します。最短3〜5秒程度にはちぢめることは可能です。

Wowzaがデフォルト設定という前提で話しますと。
少なくともiOS, macOS Safariでは遅延が発生します。Androidに関しては端末、OS依存なところがありなんとも言い難いです。

wowza日本代理店のfacebookページにも遅延を抑えたみたいなコラムがありました。
