### ISSUE TITLE
corruption when tapping on FPS segment button

### ISSUE THREAD

**Issue by pzs7602** [shogo4405/lf.swift#136]
The original lf.swift project(0.5.2 release), running the Example iOS target, when tapping on FPS segment control(15.0,or 30.0 or 60.0), the app corrupted at:
    open var captureSettings:[String:Any] {
        get {
            var captureSettings:[String:Any]!
            lockQueue.sync {
                captureSettings = self.mixer.dictionaryWithValues(forKeys: AVMixer.supportedSettingsKeys)
            }
            return captureSettings
        }
        set {
            lockQueue.async {
                self.mixer.setValuesForKeys(newValue)
            }
        }
    }
on NetStream.swift
App runs on iPhone 5s, iPhone 7 plus

**Comment by shogo4405** [comment]
oh... Thanks a lot. I will fix asap!!

**Comment by pzs7602** [comment]
when will the pause functionality be implemented?

**Comment by shogo4405** [comment]
@pzs7602 
Did u mean #111? this week.

**Comment by pzs7602** [comment]
yes, thanks!

**Comment by shogo4405** [comment]
```
[com.github.shogo4405.lf.Stream.lock] [98] continuousAutofocus > focusMode(2) is not supported
2016-11-15 00:46:53.188 [Info] [com.cerebralgardens.xcglogger.defaultInstance] [main] [33] fps > (30.0, __C.CMTime(value: 100, timescale: 3000, flags: __C.CMTimeFlags(rawValue: 1), epoch: 0))
2016-11-15 00:46:58.958593 Example iOS[390:142194] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<lf.AVMixer 0x174280cd0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key orientation.'
*** First throw call stack:
```
> this class is not key value coding-compliant for the key orientation

**Comment by shogo4405** [comment]
Release 0.5.3
