### ISSUE TITLE
localRecord no sound

### ISSUE THREAD

**Issue by pzs7602** [shogo4405/lf.swift#137]
Original lf project, when publishing and choosing .localRecord type, no audio recorded in local mp4 file(check by SPlayerX and QuickTime Player, video part is OK). 
My code:
        rtmpStream.captureSettings = [
            "sessionPreset": AVCaptureSessionPreset1280x720,
            "continuousAutofocus": true,
            "continuousExposure": true,
        ]

        rtmpStream.videoSettings = [
            "width": 1280,
            "height": 720,
        ]
        rtmpStream.recorderSettings = [
            AVMediaTypeAudio: [
                AVFormatIDKey: Int(kAudioFormatMPEG4AAC),
                AVSampleRateKey: sampleRate,
                AVNumberOfChannelsKey: 2,
            ],
            AVMediaTypeVideo: [
                AVVideoCodecKey: AVVideoCodecH264,
                AVVideoHeightKey: 1080,
                AVVideoWidthKey: 1920,
            ],
            
        ]
......
    func rtmpStatusHandler(_ notification:Notification) {
        let e:Event = Event.from(notification)
        if let data:ASObject = e.data as? ASObject , let code:String = data["code"] as? String {
            switch code {
            case RTMPConnection.Code.connectSuccess.rawValue:
                rtmpStream!.publish(Preference.defaultInstance.streamName!,type: .localRecord)
                // sharedObject!.connect(rtmpConnection)
            default:
                break
            }
        }
    }

am I missing something?

**Comment by shogo4405** [comment]
@pzs7602 
Sorry. It's a bug. I fixed it. and Testing...
