### ISSUE TITLE
Publishing pause and Video is last frame and an information text displayed on the last frame image

### ISSUE THREAD

**Issue by shogo4405** [shogo4405/lf.swift#139]
refs #111 
> NetConneciton is connecting. NetStream is publishing. Audio is mute. Video is last frame
> and an information text displayed on the last frame image, such as "The broadcast is paused ...."

**Comment by justinoverton** [comment]
This could almost benefit from being driven by a more generic watermark feature.

**Comment by shogo4405** [comment]
#205
