### ISSUE TITLE
Does lf support RTMP Playback?

### ISSUE THREAD

**Issue by mrbemani** [shogo4405/lf.swift#14]
I saw a "RTMPStream.play" Method in the source file, but I don't know how to use it, when I call it, application always crashes.

**Comment by shogo4405** [comment]
No. playback feature is exprimental.

**Comment by MingLoan** [comment]
how about now??

**Comment by shogo4405** [comment]
Video(H264 Baseline) is works ok.
Audio is NO.

implementing now. difficult for me X)

**Comment by MingLoan** [comment]
Then I can play muted video via RTMP. Thats enough for me at this moment!!

**Comment by timelincoln7648** [comment]
still no audio?

**Comment by shogo4405** [comment]
Audio(AAC(Main) is works ok. But buggy...

**Comment by jackfreed** [comment]
how or where do u attach the audio for playing back?

**Comment by shogo4405** [comment]
@jackfreed 
What did u mean?

**Comment by jackfreed** [comment]
we are currently using GLLFView, on which we attachStream the RTMPStream, but there is no audio, so i was thinking there had to be another object to attach to so we get audio as well?

**Comment by shogo4405** [comment]
@jackfreed 
> how or where do u attach the audio for playing back?

No way. It is a publiser-side job. Playback feature is exprimental. I think framework-side problem.

**Comment by jackfreed** [comment]
ok because i would like to experiment with the audio playback :-)

any hints, how to start ?

let lf = GLLFView(frame: CGRect.zero)
let conn = RTMPConnection()
let stream = RTMPStream(connection: conn)

lf.attachStream(stream)

should be enough (written from the top of my head) for the audio to play ?

**Comment by shogo4405** [comment]
let lf = GLLFView(frame: CGRect.zero)
let conn = RTMPConnection()
let stream = RTMPStream(connection: conn)
lf.attachStream(stream)

_conn.connect("rtmp://your-rtmp-server/appName")_
_stream.play("your-stream-name")_
