### ISSUE TITLE
Does lf provide record locally without streaming?

### ISSUE THREAD

**Issue by JustinCUCS** [shogo4405/lf.swift#144]
Because I would like to let user choose whether live stream their recording or record for later upload to server.

RTMPStream.HowToPublish.localRecord is for record the stream, but I can't find a way to record only without stream.

I know AVcapturesession already provide that function for record locally but I hope can use only lf-framework to complete all the tasks. 
Hope you can tell me the way to do it. Thank you

**Comment by shogo4405** [comment]
@JustinCUCS 
framework has no this feature. I designed streaming and recording.

**Comment by 7bp** [comment]
I managed to start a recording without streaming by using: 

```
rtmpStream.mixer.recorder.fileName = streamName
rtmpStream.mixer.recorder.startRunning()
```

This might not be the intended use but it works.
