### ISSUE TITLE
RTMP stream questions

### ISSUE THREAD

**Issue by kiri11ko** [shogo4405/lf.swift#145]
Hey, answer the question at the expense of your LF library use it for broadcasting and recording Stream. There are two questions:
1 Is it possible to individually set the low quality of broadcast video and audio separately and put high-quality video recording and sound?
2.Can I start recording a broadcast from the very beginning of the broadcast, and the team?
Thank you in advance!

**Comment by shogo4405** [comment]
> 1 Is it possible to individually set the low quality of broadcast video and audio separately and put high-quality video recording and sound?

local-side recording. Maybe, Yes. I will try, then update README.md. Please wait :)

> 2.Can I start recording a broadcast from the very beginning of the broadcast, and the team?

What do you mean by that? Do you want download a stream? framework has no feature.
But publisher can record on client-side(.localRecord), server-side(.record).

```swift
// start publishing and local recording
rtmpStream.publish("streamName", type: .localRecord)
```

```swift
// start publishing
rtmpStream.publish("streamName")
sleep(1000 * 10)
// start local recording
rtmpStream.publish("streamName", type: .localRecord)
```

**Comment by kiri11ko** [comment]
I meant to start a local record does not start at the moment of
translation, and after a while, when it is broadcast without recording?

2016-12-13 19:34 GMT+03:00 shogo4405 <notifications@github.com>:

**Comment by shogo4405** [comment]
>>1 Is it possible to individually set the low quality of broadcast video and audio separately and put high-quality video recording and sound?

> client-side recording. Maybe, Yes. I will try, then update README.md. Please wait :)

Please try this these parameters(comment-out)
```swift
// "0" means the same of input
rtmpStream.recorderSettings = [
    AVMediaTypeAudio: [
        AVFormatIDKey: Int(kAudioFormatMPEG4AAC),
        AVSampleRateKey: 0,
        AVNumberOfChannelsKey: 0,
        // AVEncoderBitRateKey: 128000,
    ],
    AVMediaTypeVideo: [
        AVVideoCodecKey: AVVideoCodecH264,
        AVVideoHeightKey: 0,
        AVVideoWidthKey: 0,
        /*
        AVVideoCompressionPropertiesKey: [
            AVVideoMaxKeyFrameIntervalDurationKey: 2,
            AVVideoProfileLevelKey: AVVideoProfileLevelH264Baseline30,
            AVVideoAverageBitRateKey: 512000
        ]
        */
    ],
]
```

**Comment by shogo4405** [comment]
> I meant to start a local record does not start at the moment of
translation, and after a while, when it is broadcast without recording?

Yes.

**Comment by kiri11ko** [comment]
With these parameters will be high quality recording?

**Comment by kiri11ko** [comment]
Yet such a question whether it is possible to disable copying of the video in the gallery or delete the file from the working directory?

**Comment by kiri11ko** [comment]
I use the following settings, but I did not get above 11 FPS video. At least I need 25 fps, tell me what could be the problem?
  
 rtmpStream.recorderSettings = [
                AVMediaTypeAudio: [
                    AVFormatIDKey: Int(kAudioFormatMPEG4AAC),
                    AVSampleRateKey: 0,
                    AVNumberOfChannelsKey: 0,
                    // AVEncoderBitRateKey: 128000,
                ],
                AVMediaTypeVideo: [
                    AVVideoCodecKey: AVVideoCodecH264,
                    AVVideoHeightKey: 1280,
                    AVVideoWidthKey: 720,
                    
                     AVVideoCompressionPropertiesKey: [
                     AVVideoMaxKeyFrameIntervalDurationKey: 1,
                     AVVideoAllowFrameReorderingKey: 0,
                     AVVideoProfileLevelKey: AVVideoProfileLevelH264High41,
                     AVVideoAverageBitRateKey: 7512000,
                     AVVideoExpectedSourceFrameRateKey: 30,
                     AVVideoAverageNonDroppableFrameRateKey: 30
                     
                     ]
                    
                ],
            ]

**Comment by shogo4405** [comment]
> Yet such a question whether it is possible to disable copying of the video in the gallery or delete the file from the working directory?

not possible. 

> I use the following settings, but I did not get above 11 FPS video. At least I need 25 fps, tell me what could be the problem?

This is the correct behavior. "high quality recording" and performance(FPS) are trade-off.

**Comment by RahulMaithani** [comment]
can you please explain HowToPublish cases(record, live, localRecord, append, appendWithGap) and when they can be used.
And how can i send audio data at each second to server?
