### ISSUE TITLE
Video autorotation

### ISSUE THREAD

**Issue by akovalov** [shogo4405/lf.swift#147]
Video is automatically rotated, but in player its always scaled up to full screen - in landscape this is correct behavior but after rotation to portrait I believe black area should appear on left and right so portrait video is showing in full size scaled down to fit size. 
Could you please correct me if I understand autorotation wrong? Thanks.

**Comment by shogo4405** [comment]
Please tell me. Your environment. I will try.
iPhone XX, iOS XX, LFView or GLLFView... etc.

**Comment by akovalov** [comment]
Thanks for the response. I'm testing more and it looks like autorotation and video size changing are working on the fly. This question appeared because I was watching rtmp strem here https://www.hdwplayer.com/rtmp-player/, but then tried to watch in vlc app and it looks good there but need to restart stream after video size changing. 

Actually my question is like: does the library support correct autorotation out of the box?
And I I suppose the answer is yes, and that it was my wrong setup to test. Let me please test more on my side and I'll get back here and close this if everything is good.

**Comment by shogo4405** [comment]
> Video is automatically rotated, but in player its always scaled up to full screen - in landscape this is correct behavior but after rotation to portrait I believe black area should appear on left and right so portrait video is showing in full size scaled down to fit size. 

OK. This behavior is by design. In your case, try this.
```swift
NotificationCenter.default.addObserver(self, selector: #selector(rotated), name: NSNotification.Name.UIDeviceOrientationDidChange, object: nil)

func rotated() {
    switch UIDevice.current.orientation {
    case .landscapeLeft, .landscapeRight:
       rtmpStream.videoSettings = [
           "width": 640, // video output width
           "height": 360, // video output height
       ]
    default:
       rtmpStream.videoSettings = [
           "width": 360, // video output width
           "height": 640, // video output height
       ]
    }
}
```

Regards.

**Comment by akovalov** [comment]
@shogo4405 thank you! Autorotation work like a charm 👍 

To see correct vide size it's needed to reopen stream in VLC app because it hangs up when video size changes. My project's web rtmp player shows green screen when video size changes so can show correctly only in one video size that was on streaming start (we are now trying to fix this issue on the web).

Also here is a simple wrapper to use the library, maybe it will help someone 
https://gist.github.com/akovalov/af414171f93238603cc43704e75e10fc

@shogo4405 thanks again, you're doing great work!

**Comment by rkoshti** [comment]
@akovalov  @shogo4405  auto syncing is not working for me . 

For ex. if i have started streaming in portrait mode then it will always be in portrait mode and if i have started streaming in landscape mode then it will always be in the landscape mode... Any suggestions ????

**Comment by akovalov** [comment]
@rkoshti Unfortunately, I have not been working with latest versions of HaishinKit lately and not familiar with latest changes that might effect rotation. However, please check the code of a wrapper file that I have used in the app referenced in last message https://gist.github.com/akovalov/af414171f93238603cc43704e75e10fc 

As you can see there is Rotation section where rotation notification is observed `observeDeviceOrientationChanges()`. And after rotation, it was needed to call `updateRTMPStreamSettings()` and `configureRTMPSettingsForCurrentOrientation()` in order to set a new video size. 

Hope this helps!

**Comment by kunwar231** [comment]
@akovalov your code has a bug
Argument type 'String' does not conform to expected type 'KeyPathRepresentable'

**Comment by kunwar231** [comment]
@akolov your code has a bug
Argument type 'String' does not conform to expected type 'KeyPathRepresentable'

**Comment by kunwar231** [comment]
var rtmpSettings: RTMPStreamSettings! {
        didSet {
            if oldValue == nil {
                updateRTMPStreamSettings()
            }
        }
    }

this code is so stupid. I updateRTMPStreamSettings(), a method called configureRTMPSettingsForCurrentOrientation() is called, which uses rtmpSettings. How can you give initial value to a variable using that variable only, when its nil?

**Comment by akovalov** [comment]
@kunwar231 that wrapper class was written 4 years ago and not supported over these years. Feel free to use it and modify for your needs and latest Swift version.

**Comment by kunwar231** [comment]
Even 4 years ago it was invalid. How can you use something that is nil?
It'll always cause a crash. 4 years ago too, you cannot use a variable from
a nil object.

**Comment by akovalov** [comment]
@kunwar231 `if oldValue == nil` checks for a first set a variable, at this moment `rtmpSettings` var is not nil, because `oldValue` is a previous value, not a current value.

**Comment by kunwar231** [comment]
So there is no initialisation of rtmpSettingds?

**Comment by kunwar231** [comment]
let minVideoSize = min(rtmpSettings.videoWidth,
rtmpSettings.videoHeight)


This line causes the crash because rtmpSettings is never initialised in
your code.

**Comment by kunwar231** [comment]
Could you specify the line where rtmpSettings is being initialised?
