### ISSUE TITLE
'shared' is unavailable use view controller based solutions where appropriate

### ISSUE THREAD

**Issue by vladneste** [shogo4405/lf.swift#149]

**Comment by vladneste** [comment]
for window:UIWindow in UIApplication.shared.windows {

**Comment by shogo4405** [comment]
Are you checked "Allow app extension API only" option?
* Deployment Info > App Extensions.

**Comment by vladneste** [comment]
Hi,

Thank you for the fast replay. Yes the "allow app extension API only" is checked

Regards
Vlad
