### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by MingLoan** [shogo4405/lf.swift#15]
1. Adaptive video bitrate supports.
2. Allow processing frame before encoding.

My idea is... (fund captureOutput in AVCEncoder.swift)

let image:CVImageBufferRef = CMSampleBufferGetImageBuffer(sampleBuffer)!
        // delegate here to allow accessing the image and apply filters, etc.
        encodeImageBuffer(image, presentationTimeStamp: CMSampleBufferGetPresentationTimeStamp(sampleBuffer), duration: CMSampleBufferGetDuration(sampleBuffer))

I will try to confirm is it possible.

**Comment by MingLoan** [comment]
I hook the sample buffer out and apply filter with CIFilter and create CVPixelBuffer as following. But the streaming video is all black on iOS 8.4 but no problem on iOS9+. What I make wrong?

CVPixelBufferCreate(
                        kCFAllocatorDefault,
                        width,
                        height,
                        kCVPixelFormatType_32BGRA,
                        nil,
                        &newPixelBuffer)
                    
                    guard let pixelBuf = newPixelBuffer else {
                        return nil
                    }

**Comment by MingLoan** [comment]
I render the image by CIContext. 

context.render(ciImage, toCVPixelBuffer: newPixelBuffer)

**Comment by shogo4405** [comment]
@MingLoan solved it?

**Comment by shogo4405** [comment]
I heard. CIImage(CVPixelBuffer: buffer) dose not work iOS8.x simulator.
But can work real devices. I tested iPod touch 8.1

**Comment by shogo4405** [comment]
currently, support CIFIlter live streaming.
