### ISSUE TITLE
'shared' is unavailable

### ISSUE THREAD

**Issue by vladneste** [shogo4405/lf.swift#151]
<img width="264" alt="screen shot 2016-12-16 at 11 11 25 am" src="https://cloud.githubusercontent.com/assets/3040435/21257424/ce164a90-c380-11e6-8b94-eaa15a7b12b3.png">

**Comment by shogo4405** [comment]
If you are using CocoaPods or cartage, not yet.
Please copy and paste this file to your workspace. https://github.com/shogo4405/lf.swift/blob/master/Platforms/iOS/ScreenCaptureSession.swift

Regards.
