### ISSUE TITLE
Broadcast in poor quality and in excellent quality record.

### ISSUE THREAD

**Issue by kiri11ko** [shogo4405/lf.swift#153]
I understand broadcast recording involves recording of the same quality as the broadcast itself and make different quality (fps) for broadcasting and recording can not be so?

Tried sdelattranslyatsiyu screen, and the screen displays the camera and then record with it, but your library translates to LFViev and the camera writes to the layer and no broadcast images from the camera, whether it is possible that around this limitation?

**Comment by shogo4405** [comment]
> Tried sdelattranslyatsiyu screen,

what's "sdelattranslyatsiyu screen"? I don't know.

**Comment by kiri11ko** [comment]
Tried to make a stream of the screen that displays the camera, and at the same time, record a video with the camera, but the stream your library from LFViev, and the camera displays the image in the layer of View and the image from the camera does not fall into the stream, whether it is possible to get around this limitation?

**Comment by shogo4405** [comment]
Can I  see your test code? 
Your sentence is difficult for me, so I can't understand it.

**Comment by kiri11ko** [comment]
`
import UIKit
import AVFoundation
import lf

class ViewController: UIViewController, AVCaptureVideoDataOutputSampleBufferDelegate {

	override func viewDidLoad() {
		super.viewDidLoad()
        print("start stream")
        let rtmpConnection:RTMPConnection = RTMPConnection()
        let rtmpStream:RTMPStream = RTMPStream(connection: rtmpConnection)
        rtmpStream.attachAudio(AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeAudio))
        //        rtmpStream.attachCamera(DeviceUtil.device(withPosition: .back))
        rtmpStream.attachScreen(ScreenCaptureSession())
        let lfView:LFView = LFView(frame: view.bounds)
        lfView.videoGravity = AVLayerVideoGravityResizeAspectFill
        lfView.attachStream(rtmpStream)
        
        //        view.addSubview(lfView)

//        view.addSubview(lfView)
//        let preview: UIView = UIView(frame: view.bounds)
//        preview.alpha = 0
//        lfView.addSubview(preview)
//        preview.layer.addSublayer(previewLayer)
//        

        
        rtmpConnection.connect("rtmp://54.218.67.227:1935/sometest")
        rtmpStream.publish("mystream")
        
        let delay = Int64(20 * Double(NSEC_PER_SEC))
        let dispatchTime = DispatchTime.now() + Double(delay) / Double(NSEC_PER_SEC)
        DispatchQueue.main.asyncAfter(deadline: dispatchTime, execute: {
            rtmpStream.close()
            print("stop stream")
            
        })
        
        cameraSession.startRunning()
        setupCameraSession()
	}

	override func viewDidAppear(_ animated: Bool) {
		super.viewDidAppear(animated)
        view.layer.addSublayer(previewLayer)
        
        cameraSession.startRunning()

	}

	lazy var cameraSession: AVCaptureSession = {
		let s = AVCaptureSession()
		s.sessionPreset = AVCaptureSessionPresetLow
		return s
	}()

	lazy var previewLayer: AVCaptureVideoPreviewLayer = {
		let preview =  AVCaptureVideoPreviewLayer(session: self.cameraSession)
		preview?.bounds = CGRect(x: 0, y: 0, width: self.view.bounds.width, height: self.view.bounds.height)
		preview?.position = CGPoint(x: self.view.bounds.midX, y: self.view.bounds.midY)
		preview?.videoGravity = AVLayerVideoGravityResize
		return preview!
	}()

	func setupCameraSession() {
		let captureDevice = AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeVideo) as AVCaptureDevice

		do {
			let deviceInput = try AVCaptureDeviceInput(device: captureDevice)
			
			cameraSession.beginConfiguration()

			if (cameraSession.canAddInput(deviceInput) == true) {
				cameraSession.addInput(deviceInput)
			}

			let dataOutput = AVCaptureVideoDataOutput()
			dataOutput.videoSettings = [(kCVPixelBufferPixelFormatTypeKey as NSString) : NSNumber(value: kCVPixelFormatType_420YpCbCr8BiPlanarFullRange as UInt32)]
			dataOutput.alwaysDiscardsLateVideoFrames = true

			if (cameraSession.canAddOutput(dataOutput) == true) {
				cameraSession.addOutput(dataOutput)
			}

			cameraSession.commitConfiguration()

			let queue = DispatchQueue(label: "com.invasivecode.videoQueue")
			dataOutput.setSampleBufferDelegate(self, queue: queue)

		}
		catch let error as NSError {
			NSLog("\(error), \(error.localizedDescription)")
		}
	}

	func captureOutput(_ captureOutput: AVCaptureOutput!, didOutputSampleBuffer sampleBuffer: CMSampleBuffer!, from connection: AVCaptureConnection!) {
		// Here you collect each frame and process it
	}

	func captureOutput(_ captureOutput: AVCaptureOutput!, didDrop sampleBuffer: CMSampleBuffer!, from connection: AVCaptureConnection!) {
		// Here you can count how many frames are dopped
	}
	
}
`
Here is my code that I use to broadcast screen on which I bring the camera image. But broadcast heard only the sound but no picture.

**Comment by shogo4405** [comment]
It's a bug framework side. I will fix.

**Comment by kiri11ko** [comment]
Hail, whether to fix the problem difficult? I really miss this functionality.

**Comment by shogo4405** [comment]
fixed it.

**Comment by kiri11ko** [comment]
What view do you add a camera? I have a white screen broadcast = (
There is an example of code?

**Comment by kiri11ko** [comment]
import UIKit
import AVFoundation
import lf

class ViewController: UIViewController, AVCaptureVideoDataOutputSampleBufferDelegate {

    @IBOutlet weak var imageView: UIImageView!
	override func viewDidLoad() {
		super.viewDidLoad()
        
        
        cameraSession.startRunning()
        setupCameraSession()
        
        print("start stream")
        let rtmpConnection:RTMPConnection = RTMPConnection()
        let rtmpStream:RTMPStream = RTMPStream(connection: rtmpConnection)
        rtmpStream.attachAudio(AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeAudio))
        //        rtmpStream.attachCamera(DeviceUtil.device(withPosition: .back))
        rtmpStream.attachScreen(ScreenCaptureSession(shared: UIApplication.shared))
        let lfView:LFView = LFView(frame: view.bounds)
        lfView.videoGravity = AVLayerVideoGravityResizeAspectFill
        lfView.attachStream(rtmpStream)
        
//                view.addSubview(lfView)
//
////        view.addSubview(lfView)
//        let preview: UIView = UIView(frame: view.bounds)
////        preview.alpha = 0
//        lfView.addSubview(preview)
//        preview.layer.addSublayer(previewLayer)
        

        
        rtmpConnection.connect("rtmp://54.218.67.227:1935/sometest")

        
        let delay = Int64(10 * Double(NSEC_PER_SEC))
        let dispatchTime = DispatchTime.now() + Double(delay) / Double(NSEC_PER_SEC)
        DispatchQueue.main.asyncAfter(deadline: dispatchTime, execute: {
            rtmpStream.publish("mystream")
            print("start stream")
            
        })
        let delay2 = Int64(30 * Double(NSEC_PER_SEC))
        let dispatchTime2 = DispatchTime.now() + Double(delay2) / Double(NSEC_PER_SEC)
        DispatchQueue.main.asyncAfter(deadline: dispatchTime2, execute: {
            rtmpStream.close()
            print("stop stream")
            
        })

	}

	override func viewDidAppear(_ animated: Bool) {
		super.viewDidAppear(animated)
        view.layer.addSublayer(previewLayer)
        
        cameraSession.startRunning()

	}

	lazy var cameraSession: AVCaptureSession = {
		let s = AVCaptureSession()
		s.sessionPreset = AVCaptureSessionPresetLow
		return s
	}()

	lazy var previewLayer: AVCaptureVideoPreviewLayer = {
		let preview =  AVCaptureVideoPreviewLayer(session: self.cameraSession)
		preview?.bounds = CGRect(x: 0, y: 0, width: self.view.bounds.width, height: self.view.bounds.height)
		preview?.position = CGPoint(x: self.view.bounds.midX, y: self.view.bounds.midY)
		preview?.videoGravity = AVLayerVideoGravityResize
		return preview!
	}()

	func setupCameraSession() {
		let captureDevice = AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeVideo) as AVCaptureDevice

		do {
			let deviceInput = try AVCaptureDeviceInput(device: captureDevice)
			
			cameraSession.beginConfiguration()

			if (cameraSession.canAddInput(deviceInput) == true) {
				cameraSession.addInput(deviceInput)
			}
            
//            videoDataOutput = AVCaptureVideoDataOutput()
//            videoDataOutput?.videoSettings = [kCVPixelBufferPixelFormatTypeKey:Int(kCVPixelFormatType_32BGRA)]
//            videoDataOutput?.setSampleBufferDelegate(self, queue: queue)
            
			let dataOutput = AVCaptureVideoDataOutput()
//			dataOutput.videoSettings = [(kCVPixelBufferPixelFormatTypeKey as NSString) : NSNumber(value: kCVPixelFormatType_420YpCbCr8BiPlanarFullRange as UInt32)]
            dataOutput.videoSettings = [kCVPixelBufferPixelFormatTypeKey as AnyHashable:Int(kCVPixelFormatType_32BGRA)]
			dataOutput.alwaysDiscardsLateVideoFrames = true

			if (cameraSession.canAddOutput(dataOutput) == true) {
				cameraSession.addOutput(dataOutput)
			}

			cameraSession.commitConfiguration()

			let queue = DispatchQueue(label: "com.invasivecode.videoQueue")
			dataOutput.setSampleBufferDelegate(self, queue: queue)

		}
		catch let error as NSError {
			NSLog("\(error), \(error.localizedDescription)")
		}
	}

**Comment by kiri11ko** [comment]
as you tested this bug?
