### ISSUE TITLE
When you run the example falls in error

### ISSUE THREAD

**Issue by kiri11ko** [shogo4405/lf.swift#156]
![2016-12-24 14 21 42](https://cloud.githubusercontent.com/assets/6023670/21466697/622791e4-c9e4-11e6-8d58-2e00ffa2bb02.png)

**Comment by kiri11ko** [comment]
When you run the example falls in error. when I press the button to begin broadcasting

**Comment by kiri11ko** [comment]
This may be due to the fact that I do not use authorization and do not specify username and password?

**Comment by shogo4405** [comment]
* console log
  - fatal error: unexpectedly found nil while...

Can I see a break point "1 LiveViewController.rtmpStatus..." ?

**Comment by kiri11ko** [comment]
![2016-12-26 12 40 01](https://cloud.githubusercontent.com/assets/6023670/21479799/8a7e7178-cb68-11e6-9750-b89275ac5c42.png)

**Comment by shogo4405** [comment]
Why are you remove comment. That's the cause.
 https://github.com/shogo4405/lf.swift/blob/master/Examples/iOS/LiveViewController.swift#L241
