### ISSUE TITLE
No sound on RTMP stream with an Bluetooth sound device

### ISSUE THREAD

**Issue by vantassell** [shogo4405/lf.swift#158]
I'm following the iOS example in your project and my streams don't have any audio. Should audio be working?

**Comment by shogo4405** [comment]
I tested now. Is your device iPhone7 (Plus) too?
* MacbookPro 2016 -> works fine.
* iPhone7 Plus (iOS10.1) -> no sound.
* iPad pro 9.7 -> works fine.

**Comment by shogo4405** [comment]
@vantassell 
Thank u. Feed back.

**Comment by shogo4405** [comment]
@shogo4405
```
iPhone7 Plus... mSampleRate: 16000.000000
CMSampleBuffer 0x10123f460 retainCount: 10 allocator: 0x1ab69ebb8
	invalid = NO
	dataReady = YES
	makeDataReadyCallback = 0x0
	makeDataReadyRefcon = 0x0
	formatDescription = <CMAudioFormatDescription 0x170114490 [0x1ab69ebb8]> {
	mediaType:'soun' 
	mediaSubType:'lpcm' 
	mediaSpecific: {
		ASBD: {
			mSampleRate: 16000.000000 
			mFormatID: 'lpcm' 
			mFormatFlags: 0xc 
			mBytesPerPacket: 2 
			mFramesPerPacket: 1 
			mBytesPerFrame: 2 
			mChannelsPerFrame: 1 
			mBitsPerChannel: 16 	} 
		cookie: {(null)} 
		ACL: {(null)}
		FormatList Array: {(null)} 
	} 
	extensions: {(null)}
}
	sbufToTrackReadiness = 0x0
	numSamples = 372
	sampleTimingArray[1] = {
		{PTS = {99138762432791/1000000000 = 99138.762}, DTS = {INVALID}, duration = {1/16000 = 0.000}},
	}
	sampleSizeArray[1] = {
		sampleSize = 2,
	}
	dataBuffer = 0x1741158d0
```

**Comment by shogo4405** [comment]
I tested today(2017/01/16).
iPhone 7 Plus 10.1 works fine. Why? :(

**Comment by shogo4405** [comment]
I understand. In my case, iPhone 7 Plus 10.1 with Bluetooth Sound device(SONY/MDR-EX31BN)
```
AACEncoder
let status:OSStatus = AudioConverterFillComplexBuffer(
print(status) // 560226676 -> kAudioCodecUnsupportedFormatError
```
@vantassell
How about you? Are u using an AirPods or other bluetooth sound device?

**Comment by vantassell** [comment]
@shogo4405 I wasn't using any bluetooth audio, so I think you found a different bug than what I was experiencing. I had my audio bitrate set to _320 * 1024_ thinking it would get me 320kbps. I dropped the bitrate down to _32 * 1024_ and it works 😂

Thanks again for all of your work on this great library!

**Comment by shogo4405** [comment]
lol OK!! Thank you for comment.
