### ISSUE TITLE
AMF3 failing handshake

### ISSUE THREAD

**Issue by Jonsapps** [shogo4405/lf.swift#16]
I am trying to connect to Adobes shared ball project https://helpx.adobe.com/adobe-media-server/dev/sharedball-example.html

I have to change RTMPConnection defaultObjectEncoding from 0x00 to 0x03 otherwise the server never responds.

When the handshake completes and the delegate method "Listen" is called it fails to deserialise in RTMPMessage "commandName = serializer.deserialize(newValue, position: &position)" it shows an assertion failure because it is not a string

RTMPChunk{type:0,streamId:3,message:Optional(RTMPCommandMessage{type:AMF3Command,length:0,streamId:3,timestamp:0,commandName:connect,transactionId:1,commandObject:Optional(["tcUrl": Optional("rtmp://192.168.1.25/SharedBall"), "flashVer": Optional("AND 19,0,0,169"), "swfUrl": Optional("rtmp://192.168.1.25/SharedBall"), "app": Optional("SharedBall"), "fpad": Optional(false), "audioCodecs": Optional(1024), "videoCodecs": Optional(128), "videoFunction": Optional(1), "capabilities": Optional(239), "pageUrl": nil, "objectEncoding": Optional(3)]),arguments:[nil]})}

The byte array after the header has been removed is below, it starts with a 2 (Bool False) rather than 6 (String) which is what I think it is expecting

  - [0] : 2
  - [1] : 0
  - [2] : 6
  - [3] : 95
  - [4] : 101
  - [5] : 114
  - [6] : 114
  - [7] : 111
  - [8] : 114
  - [9] : 0
  - [10] : 65
  - [11] : 112
  - [12] : 80
  - [13] : 0
  - [14] : 0
  - [15] : 0
  - [16] : 0
  - [17] : 0
  - [18] : 5
  - [19] : 3
  - [20] : 0
  - [21] : 5
  - [22] : 108
  - [23] : 101
  - [24] : 118
  - [25] : 101
  - [26] : 108
  - [27] : 2
  - [28] : 0
  - [29] : 5
  - [30] : 101
  - [31] : 114
  - [32] : 114
  - [33] : 111
  - [34] : 114
  - [35] : 0
  - [36] : 4
  - [37] : 99
  - [38] : 111
  - [39] : 100
  - [40] : 101
  - [41] : 2
  - [42] : 0
  - [43] : 30
  - [44] : 78
  - [45] : 101
  - [46] : 116
  - [47] : 67
  - [48] : 111
  - [49] : 110
  - [50] : 110
  - [51] : 101
  - [52] : 99
  - [53] : 116
  - [54] : 105
  - [55] : 111
  - [56] : 110
  - [57] : 46
  - [58] : 67
  - [59] : 111
  - [60] : 110
  - [61] : 110
  - [62] : 101
  - [63] : 99
  - [64] : 116
  - [65] : 46
  - [66] : 82
  - [67] : 101
  - [68] : 106
  - [69] : 101
  - [70] : 99
  - [71] : 116
  - [72] : 101
  - [73] : 100
  - [74] : 0
  - [75] : 11
  - [76] : 100
  - [77] : 101
  - [78] : 115
  - [79] : 99
  - [80] : 114
  - [81] : 105
  - [82] : 112
  - [83] : 116
  - [84] : 105
  - [85] : 111
  - [86] : 110
  - [87] : 2
  - [88] : 0
  - [89] : 38
  - [90] : 91
  - [91] : 32
  - [92] : 83
  - [93] : 101
  - [94] : 114
  - [95] : 118
  - [96] : 101
  - [97] : 114
  - [98] : 46
  - [99] : 82
  - [100] : 101
  - [101] : 106
  - [102] : 101
  - [103] : 99
  - [104] : 116
  - [105] : 32
  - [106] : 93
  - [107] : 32
  - [108] : 58
  - [109] : 32
  - [110] : 67
  - [111] : 111
  - [112] : 110
  - [113] : 110
  - [114] : 101
  - [115] : 99
  - [116] : 116
  - [117] : 105
  - [118] : 111
  - [119] : 110
  - [120] : 32
  - [121] : 102
  - [122] : 97
  - [123] : 105
  - [124] : 108
  - [125] : 101
  - [126] : 100
  - [127] : 46
  - [128] : 195
  - [129] : 0
  - [130] : 0

**Comment by shogo4405** [comment]
AMF3 support not yet. X)

**Comment by Jonsapps** [comment]
That's a shame, any plans to build support for AMF3?

**Comment by Jonsapps** [comment]
I've managed to get this working, the only problem I am facing is that after connecting I receive a few messages from the server but then the connection drops and the TCP socket enters "CloseWait" I've tried on a few servers that I know work ok. Do you know any reason the connection to the server wouldn't remain open?

**Comment by shogo4405** [comment]
* Client-side reason
 1. client mistakes RTMP Handshake
 1. client send an invalid RTMP packet.
* Server-side reason(FMS)
 1. call client.rejectConnection()
 1. forget call application.acceptConnection(client)
 ```javascript
application.onConnect = function(client) {
  if (/* access allow */) {
    application.acceptConnection(client)
  }
  client.rejectConnection();
}
 ```

**Comment by Jonsapps** [comment]
Thank you, I found that I needed to disable the client sending RTMPSetChunkSizeMessage otherwise the server would disconnect and then I found I had to set the stream id to 0 otherwise the server would ignore the messages.

I am now having trouble with large messages not joining together correctly

**Comment by Jonsapps** [comment]
I am getting a command message from my server that is causing a crash

[3, 255, 255, 255, 0, 0, 94, 20, 0, 0, 0, 0, 68, 44, 73, 54, 2, 0, 14, 99, 117, 114, 114, 101, 110, 116, 66, 101, 116, 80, 111, 111, 108, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 2, 0, 64, 48, 48, 48, 48, 49, 50, 48, 54, 57, 48, 48, 48, 48, 49, 48, 57, 52, 50, 54, 48, 48, 48, 48, 48, 48, 52, 53, 55, 48, 48, 48, 48, 48, 48, 55, 49, 48, 48, 48, 48, 48, 48, 48, 55, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48]

The problem seems to be 4 extra bytes after the header, 68, 44, 73, 54 which come just before the command name. So when RTMPMessage CommandMessage bytes getter is called it crashes on
commandName = serializer.deserialize(newValue, position: &position)
Because it is expecting a string.

I can't see any headers longer than 12 bytes mentioned in the documentation, do you know what those extra 4 bytes could be? This also appears to be the start of an aggregated message because after this message I get messages with 1 byte headers

**Comment by shogo4405** [comment]
well... may be 5.3.1.3. Extended Timestamp (@see rtmp_specification_1.0.pdf)
[3, 255, 255, 255] means RTMPChunk type = 0, timestamp = [255, 255, 255] = 0xFFFFFF.

**Comment by Jonsapps** [comment]
Yes you are correct, Extended Timestamps don't appear to be handled.
