### ISSUE TITLE
 does not start broadcasting from Example-ReplayKit

### ISSUE THREAD

**Issue by kiri11ko** [shogo4405/lf.swift#161]
![2017-01-06 13 46 11](https://cloud.githubusercontent.com/assets/6023670/21715646/d67c034a-d416-11e6-8a68-2731b7c3f9d6.png)

**Comment by kiri11ko** [comment]
An example of libraries for iOS Stream video without sound. Maybe it is connected.

**Comment by shogo4405** [comment]
Yes! Example-ReplayKit has no sound!!

**Comment by kiri11ko** [comment]
Sound is not an example to LF library
