### ISSUE TITLE
stream camera preview from screen

### ISSUE THREAD

**Issue by kiri11ko** [shogo4405/lf.swift#162]
I deduce the screen preview of the camera. And I want to stream this screen, but see only a white screen.

**Comment by shogo4405** [comment]
Apparently iOS can't capture an AVCapturePreviewLayer. http://stackoverflow.com/questions/9012397/is-it-possible-to-render-avcapturevideopreviewlayer-in-a-graphics-context

Please consider another way.

**Comment by kiri11ko** [comment]
I thought that there are some restrictions iOS. But replaykit can do it, get it, they do not cover something.
