### ISSUE TITLE
Can I disable copy video to PhotoLibrary?

### ISSUE THREAD

**Issue by kiri11ko** [shogo4405/lf.swift#164]
subj

**Comment by kiri11ko** [comment]
to do so

 public func didFinishWriting(_ recorder:AVMixerRecorder) {
    #if os(iOS)
        guard let writer:AVAssetWriter = recorder.writer else {
            return
        }
//        PHPhotoLibrary.shared().performChanges({() -> Void in
//            PHAssetChangeRequest.creationRequestForAssetFromVideo(atFileURL: writer.outputURL)
//        }, completionHandler: { (isSuccess, error) -> Void in
//            do {
//                try FileManager.default.removeItem(at: writer.outputURL)
//            } catch let error as NSError {
//                logger.error("\(error)")
//            }
//        })
    #endif
    }

**Comment by shogo4405** [comment]
framework has no disable feature. But you can create a cusom recorder delegate.
```
// 0.5.7
class MyDelegate: AVMixerRecorderDelegate {
    // implement protocols 
}
var customDelegate: MyDelegate = MyDelegate()
rtmpStream.recorderDelegate = customDelegate
// rtmpStream.mixer.recorder.delegate = customDelegate
```
