### ISSUE TITLE
[OSX] when not focus to the program/ minimized, the rtmp stream is not work

### ISSUE THREAD

**Issue by JustinCUCS** [shogo4405/lf.swift#165]
I would like to live stream the screen to the server and I hope the program would not block the screen, therefore I need to record with minimize my program to the taskbar.

It seems the thread is not active while program idle? Almost no frames are sending to the server. (FPS is ~0)
Any suggestions for lf to handle such situtation?

**Comment by shogo4405** [comment]
How about your program send a dummy CMSampleBuffer?
1. Detect when the program/ minimized
1. Register timer
1. RTMPStream.appendSampleBuffer(CMSampleBuffer, withType: .video)

**Comment by JustinCUCS** [comment]
Do you mean the **RTMPStream.mixer.record.appendSampleBuffer** ?
Even I can detect the active state of the program, still I have no idea how to get the sample buffer with using the timer and append it to the  current RTMPStream .

Would you please help me and provide some example code to deal with it?
Thank so much!

**Comment by shogo4405** [comment]
> Do you mean the **RTMPStream.mixer.record.appendSampleBuffer** ?

4a8612a92bc6a2f2cc4b21dfbe57e02eccebc1fd No. Please see this new api.
And You must create a new dummy CMSampleBuffer(Black screen etc...) with using timer.

> Would you please help me and provide some example code to deal with it?

I can be able to do this weekend :( Are u ok?

**Comment by JustinCUCS** [comment]
> I can be able to do this weekend :( Are u ok?

Of course! Thank you so much!!

**Comment by shogo4405** [comment]
```
import lf
import Foundation
import CoreMedia

class Issue165RTMPStream: RTMPStream {
    lazy var offscreen:TimerDriver = {
        var driver:TimerDriver = TimerDriver()
        driver.interval = MachUtil.nanosToAbs(33 * MachUtil.nanosPerMsec)
        driver.setDelegate(self)
        return driver
    }()
}

extension Issue165RTMPStream: TimerDriverDelegate {
    // create dummy CMSampleBuffer
    private var sampleBuffer: CMSampleBuffer? {
        guard let originalBuf:CMSampleBuffer = mixer.sampleBuffers[CMSampleBufferType.video]! else {
            return nil
        }

        var sampleBuffer:CMSampleBuffer? = nil
        let numSampleTimingEntries:CMItemCount = CMSampleBufferGetNumSamples(originalBuf)
        let duration:CMTime = CMSampleBufferGetDuration(originalBuf)
        let presentationTimeStamp:CMTime = CMTimeAdd(
            CMSampleBufferGetPresentationTimeStamp(originalBuf),
            duration
        )

        var sampleTimingArray:CMSampleTimingInfo = CMSampleTimingInfo(
            duration: duration,
            presentationTimeStamp: presentationTimeStamp,
            decodeTimeStamp: CMSampleBufferGetDecodeTimeStamp(originalBuf)
        )

        CMSampleBufferCreateCopyWithNewTiming(
            kCFAllocatorDefault,
            originalBuf,
            numSampleTimingEntries,
            &sampleTimingArray,
            &sampleBuffer
        )
        
        return sampleBuffer
    }

    func tick(_ driver:TimerDriver) {
        if let sampleBuffer = self.sampleBuffer {
            appendSampleBuffer(sampleBuffer, withType: .video)
        }
    }
}

```

**Comment by shogo4405** [comment]
> 1. Detect when the program/ minimized

//  the program become inactive.
issue165RTMPStream.offscreen.startRunning()

// the program become active.
issue165RTMPStream.offscreen.stopRunning()

This example code is:
RTMPStream keep sending a LastFrame(CMSampleBuffer) to server with 30FPS.

**Comment by JustinCUCS** [comment]
Oh I have test with the sample code and I found that solution may not satisfy my needs...

As my program needs to record the screen while minimize the program to background without blocking the screen, 
and I misunderstanding your suggestions, I thought sending the dummy buffer would keep initiating the thread to capture the screen and keep on encode it and send to the server..

Still I am very grateful that you spend lots of time answering me and provide the solution for me!

**Comment by shogo4405** [comment]
umm....
> without blocking the screen
Please tell me "the screen" meaning. I thought the capture target application window. Your application window? macOS desktop...

**Comment by JustinCUCS** [comment]
One of my program aims is capturing whole display , like open broadcaster, choosing the capture source, capture, stream, and able to work properly after minimize its window to the taskbar. 

In my program, I use lf framework to do streaming and recording , but I can't overcome the problem that the my program minimized/not active , the program is not function normally, no frames are captured.

**Comment by shogo4405** [comment]
OK. I understand. But I can't reproduce...

**Comment by shogo4405** [comment]
Please show me your example code. Because I can't debug.
Then I will reopen this issue :)
