### ISSUE TITLE
Getting ping value from rtmpConnection

### ISSUE THREAD

**Issue by mzmiric5** [shogo4405/lf.swift#168]
Hi, I was just wondering if there was a way of getting the ping value from a connected stream? 

We are building a solution where we have a number of different RTMP ingest servers, and we would like to test connectivity to them by measuring latency which should help select the best server.

If there isn't a way to get the ping value from a connected stream, what would be the best class to look through to start implementing this feature?

**Comment by shogo4405** [comment]
> If there isn't a way to get the ping value from a connected stream

framework has no feature. Please look this this "RTMPUserControlMessage" class.
https://github.com/shogo4405/lf.swift/blob/master/Sources/RTMP/RTMPMessage.swift#L704

The RTMP client can't send a ping(0x06) message. see also "RTMP Specification 1.0" P27. http://www.adobe.com/content/dam/Adobe/en/devnet/rtmp/pdf/rtmp_specification_1.0.pdf

**Comment by mzmiric5** [comment]
thanks for getting back to me, yeah I think this will do. We can just listen to the PONG messages coming from each of the servers when we run the rtmp in test mode (our internal query param in the rtmp string) and check the time difference from the time received as a timestamp from the ping
