### ISSUE TITLE
Q: RTMP Authentication

### ISSUE THREAD

**Issue by oantajames** [shogo4405/lf.swift#171]
Hi!  I really appreciate all that you are doing on this project. Awesome work! 
I am currently working on a project that needs RTMP Authentication, but there is no documentation regarding this on the internet.
I saw that you implemented it so I took this project as an example.
I managed to get the following response from the server : 
`"[ AccessManager.Reject ] : [ code=403 need auth; authmod=adobe ]"`
From what I have understood from your project the way things go are like this:
**1.** Make a call to the server with the normal url` rtmp://host[:port]/application/streamName`
**2.** You will receive the following error from the server `"[ AccessManager.Reject ] : [ code=403 need auth; authmod=adobe ]"`
**3.** Make a new call with the following url` rtmp://host[:port]/application/streamName?authmod=adobe&user=username`
**4.** You will receive back from the server the following : 
`[ AccessManager.Reject ] : [ authmod=adobe ] : ?reason=needauth&user=100987&salt=NDU=&challenge=NjA4NDEzNzg0`
or something like that.
**5.** With the last response from the server you will build the url that will (hopefully) authenticate you successfully.

My problem is at **4!** I never get the salt, challenge and opaque parameters.... I only receive this : 
`"[ AccessManager.Reject ] : [ code=403 need auth; authmod=adobe ]"`

Am I doing it in the right way ?
Is this ` rtmp://host[:port]/application/streamName?authmod=adobe&user=username` the corect format for the second call ? 

Thanks in advance! 

James

**Comment by shogo4405** [comment]
> Is this rtmp://host[:port]/application/streamName?authmod=adobe&user=username the corect format for the second call?

RTMP ConnectionPacket doesn't need "streamName".
https://github.com/shogo4405/lf.swift/blob/master/Sources/RTMP/RTMPConnection.swift#L353

If you send this uri "rtmp://host[:port]/application/streamName?authmod=adobe&user=username", RTMPServer interprets rtmp://host[:port]/application/**appInstanceName**?authmod=adobe&user=username

Regards.

**Comment by oantajames** [comment]
Will try it that way and come back.
From what I have remembered I also tried it this way.
Will see.
Thank you !!!

**Comment by oantajames** [comment]
```
  fileprivate static func createSanJoseAuthCommand(_ url:URL, description:String) -> String {
        var command:String = url.absoluteString

        guard let index:String.CharacterView.Index = description.characters.index(of: "?") else {
            return command
        }

        let query:String = description.substring(from: description.characters.index(index, offsetBy: 1))
        let challenge:String = String(format: "%08x", arc4random())
        let dictionary:[String:String] = URL(string: "http://localhost?" + query)!.dictionaryFromQuery()

        var response:String = MD5.base64("\(url.user!)\(dictionary["salt"]!)\(url.password!)")
        if let opaque:String = dictionary["opaque"] {
            command += "&opaque=\(opaque)"
            response += opaque
        } else if let challenge:String = dictionary["challenge"] {
            response += challenge
        }

        response = MD5.base64("\(response)\(challenge)")
        command += "&challenge=\(challenge)&response=\(response)"

        return command
    }

> 
```
Could you please help me understand a bit more of the above code ?
Right now I am doing the following in Java:

```
private String formatUrl2(HashMap<String, String> sessionMap) throws IOException {
        //setting the app name back to default
        appName = appName.replace("?authmod=adobe&user=" + user, "");
        String command = tcUrl + "/" + appName;
        String newAppName = "";
        Random random = new Random();
        String challenge1 = String.format("%08x", random.nextInt());
        command = command.replace("?authmod=adobe&user=" + user, "");
        String response = calculateMD5(user + sessionMap.get("salt") + password);
        if (sessionMap.get("opaque") != null) {
            String opaque = sessionMap.get("opaque");
            command = command + "&opaque=" + sessionMap.get("opaque");
            newAppName = appName + "&opaque=" + sessionMap.get("opaque");
            response = response + opaque;
        } else if (sessionMap.get("challenge") != null) {
            String challenge = sessionMap.get("challenge");
            response = response + challenge;
        }
        response = calculateMD5(response + challenge1);
        command = command + "&challenge=" + challenge1 + "&response=" + response;
        newAppName = newAppName + "&challenge=" + challenge1 + "&response=" + response;

        appName = newAppName;
        reconnecting = true;
        connect(command);
        return command;
    }
```
I tried to do the exact same thing that you did in swift, but in java but I always get : 
`Connection failed: Application folder ([install-location]...) is missing. `
Could you please explain in simple terms how you format the url and what you send to the server exactly ?

Thanks in advance!

**Comment by shogo4405** [comment]
> Could you please explain in simple terms

I'm not sure. Please ask stackoverflow! 

Regards.
