### ISSUE TITLE
Noise iPhone6s

### ISSUE THREAD

**Issue by maurodelazeri** [shogo4405/lf.swift#18]
I'm using with wowza but it doing a noise, not big, but have one.
I change the bitrate but does matter, still doing noise

**Comment by maurodelazeri** [comment]
update, tested in 
iphone 5 and 5s - ok
iphone 6s does not

**Comment by shogo4405** [comment]
iphone 6 is ok

**Comment by maurodelazeri** [comment]
the noise that im taking about is this:

http://monosnapmauro.s3.amazonaws.com/monosnapmauro/streaming.m4a

So, it means we have problem only in iphone 6s

**Comment by shogo4405** [comment]
@shogo4405 FYI
* https://forums.developer.apple.com/thread/20187
* http://stackoverflow.com/questions/32893804/robotic-voice-through-iphone-6s-microphone

**Comment by maurodelazeri** [comment]
So, I did some tests with different software, no problem @shogo4405

**Comment by shogo4405** [comment]
iPhone6s Microphone sampleRate is 48khz
iPhone6  Microphone  sampleRate is 44.1khz

I have a down-samplerate bug.
44.1khz → 44.1khz work fine.
48khz    → 44.1khz work no.
44.1khz → 22.05khz work no. 

I think fixed https://github.com/shogo4405/lf.swift/commit/8e1673f86f865de16560d3c24a59dff546dd2b18

**Comment by maurodelazeri** [comment]
@shogo4405 is better than before, but still with a bit of noise
