### ISSUE TITLE
Can not encode when use core image filter

### ISSUE THREAD

**Issue by crazydragon91** [shogo4405/lf.swift#181]
Hi,

I use this filter for my app https://github.com/YuAo/YUCIHighPassSkinSmoothing, but the encoder can not encode avc when I registered this filter.

Can you give me some suggestion for fixing it?

Thanks,

**Comment by anotheren** [comment]
Try to use this one, it works well. 😄
https://github.com/Limon-O-O/Lady

**Comment by shogo4405** [comment]
well... It seems works fine.
Do you know "Bridging-Header"?

1. add Podfile
   > def import_pods
   >    pod 'YUCIHighPassSkinSmoothing'
   > end
   >
   > target 'Example iOS'  do
   >    platform :ios, '8.0'
   >    import_pods
   > end
2. pod update
3. create Bridging-Header file
   - https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html
4. add this line to Bridging-Header
    > #import "YUCIHighPass.h"
    > #import "YUCIHighPassSkinSmoothing.h"
5. update "Exsample  iOS"'s VisualEffect.swift
    > final class MonochromeEffect: VisualEffect {
    > let filter:CIFilter? = YUCIHighPassSkinSmoothing()
    >
    > override func execute(_ image: CIImage) -> CIImage {
    >    guard let filter:CIFilter = filter else {
    >        return image
    >    }
    >    filter.setValue(image, forKey: kCIInputImageKey)
    >    filter.setValue(0.7, forKey: "inputAmount")
    >    return filter.outputImage!
    >}
    >}

**Comment by shogo4405** [comment]
Be careful,  "Bridging-Header" can't use framework project.
If you want to use framework project. Please consider https://github.com/Limon-O-O/Lady.

**Comment by crazydragon91** [comment]
I used to try Lady, but it still show in the camera view. The player can not play the video.
I debug and know that, the encoder can not encode the video with this filter :(

**Comment by shogo4405** [comment]
Could you show me a player's log?

**Comment by crazydragon91** [comment]
Hi,
`ffplay version 3.2.git Copyright (c) 2003-2016 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --enable-libx264 --enable-gpl
  libavutil      55. 41.101 / 55. 41.101
  libavcodec     57. 66.108 / 57. 66.108
  libavformat    57. 58.101 / 57. 58.101
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 68.100 /  6. 68.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
[zup @ 0x7f7ed4001280] zup open 49.213.118.162:7000 /109 0B f=0/0   
[zup @ 0x7f7ed4001280] zup_open success 49.213.118.162:7000
zlv_probe  :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0   
[zlv @ 0x7f7ed4000920] zlv_read_header 4
[zlv @ 0x7f7ed4000920] audio stream discovered after head already parsed
[zlv @ 0x7f7ed4000920] create_stream
Input #0, zlv, from 'zup://49.213.118.162:7000/109':=    0B f=0/0   
  Duration: N/A, start: 14.373000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 44100 Hz, mono, fltp
[zup @ 0x7f7ed4001280] zup_close  19KB vq=    0KB sq=    0B f=0/0   `

**Comment by shogo4405** [comment]
well... I'm not sure. zup:// and zlv....
I'm sorry I couldn't be of any help.

**Comment by crazydragon91** [comment]
we change rtmp to zlp and zlv
we have a protocol looks like rtmp,but change a scheme. We build ffmpeg
with our scheme too.
I test with our fork library and your lf.swift. but I can not reproduce why
it can not encode.

After test it, we change back to rtmp again. But just decode a first frame
video without a filter, if the filter is applies in the first time, it can
not decode yet

Regards,

**Comment by shogo4405** [comment]
In my case, I can work ok. iPhone -> Wowza -> ffplay
* iPhone7 Plus with YUCIHighPassSkinSmoothing is FPS30(AVCaptureSessionPreset1280x720)
* iPod touch5th with YUCIHighPassSkinSmoothing is FPS4(AVCaptureSessionPreset352x288)

But, 32bit or older iPhone is not good performance. How about you?

**Comment by crazydragon91** [comment]
In your example app.

None effect -> stream -> player can play. Apply the beauty effect -> it's
work
But if you addEffect at first, and stream after that the player can not
play the video.

**Comment by crazydragon91** [comment]
In your example app.

None effect -> stream -> player can play. Apply the beauty effect -> it's work
But if you addEffect at first, and stream after that the player can not play the video.

**Comment by shogo4405** [comment]
This is my code. It works fine...
```
    override func viewWillAppear(_ animated: Bool) {
        logger.info("viewWillAppear")
        super.viewWillAppear(animated)
        rtmpStream.registerEffect(video: YUCIHighPassSkinSmoothingEffect())
        rtmpStream.attachAudio(AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeAudio), automaticallyConfiguresApplicationAudioSession: false)
        rtmpStream.attachCamera(DeviceUtil.device(withPosition: currentPosition))
        rtmpStream.addObserver(self, forKeyPath: "currentFPS", options: NSKeyValueObservingOptions.new, context: nil)
        lfView?.attachStream(rtmpStream)
    }
```

**Comment by shogo4405** [comment]
I can't fix it. Please fix it your self. I'm waiting a PR.
