### ISSUE TITLE
Get video time

### ISSUE THREAD

**Issue by dekeract** [shogo4405/lf.swift#183]
Hi! 
I want to ask for advice.
Is there a way to get current video time of rtmp stream? 
I see that RTMPStream class has videoTimestamp var, but it's closed.

The reason I'm asking for is that I want to sync time between broadcaster and viewer (viewer will have some delay when watching a stream). 

Thanks.

**Comment by shogo4405** [comment]
> Is there a way to get current video time of rtmp stream?

No way.
