### ISSUE TITLE
Get CMSampleBufferRef/CIImage from current AVCaptureVideoDataOutput

### ISSUE THREAD

**Issue by V1C0D3R** [shogo4405/lf.swift#186]
I attached a HTTPStream to a LFView but I would like to get last frame at selected time. I know that capturing a screenshot of the LFView is not the right way to do it.

Is there a way to get last CMSampleBufferRef at any time from HTTPStream?
Maybe a way to add an additional external SampleBufferDelegate?

Thanks for the amazing work!

**Comment by shogo4405** [comment]
I think it is different applications.... 
```
open class VisualEffect: NSObject {
    var lastFrame:CIImage?
    open func execute(_ image: CIImage) -> CIImage {
        lastImage = image // You can get a every CIImage 
        return image
    }
}

httpStream.registerEffect(VisualEffect())
```

**Comment by V1C0D3R** [comment]
Thank you but this mean I need to modify your framework after installing it, right?

**Comment by V1C0D3R** [comment]
Got it with something like that: 
`class VisualSaver: VisualEffect {
    var lastImage:CIImage? = nil
    override func execute(_ image: CIImage) -> CIImage {
        self.lastImage = super.execute(image)
        return image
    }
}`

Thanks!

**Comment by shogo4405** [comment]
> Got it with something like that:
Yes!
