### ISSUE TITLE
Video aspect ratio cannot change when rotation changes.

### ISSUE THREAD

**Issue by mrbemani** [shogo4405/lf.swift#19]
```swift
override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()

        let ori = UIDevice.currentDevice().orientation
        if ori == UIDeviceOrientation.Portrait {
            self.rtStream?.videoSettings = [
                "width": 272,
                "height": 480
            ]
        } else {
            self.rtStream?.videoSettings = [
                "width": 480,
                "height": 272
            ]
        }
}
```
I'm not sure if this is the right way to do.

**Comment by maurodelazeri** [comment]
@mrbemani "out of main topic", I saw you use this project, are you make it with wowza?
I'm using wownza, works well, but the audio is not perfect, make a bit of noise, I'm using iphone 6s

**Comment by mrbemani** [comment]
audio is fine. maybe I didn't notice it. the noise may be the feedback from your mic, it happened to me when I tried it the first time. try separate your sending and receiving devices, see if the problem goes away.

**Comment by maurodelazeri** [comment]
@mrbemani I recorded it, take a look

http://monosnapmauro.s3.amazonaws.com/monosnapmauro/streaming.m4a

I left the computer recording the streaming and I was in another room, the noise still the same, for you the audio is clear and perfect?

**Comment by mrbemani** [comment]
No I don't get this notice. Ha....strange...

**Comment by maurodelazeri** [comment]
So if we have the same code, could be or the iphone model or the wowza server.
I will try reinstall the wowza server

**Comment by shogo4405** [comment]
currently... no way X)
I will try fix

**Comment by shogo4405** [comment]
@mrbemani currently master branch works ok!!

**Comment by shogo4405** [comment]
released https://github.com/shogo4405/lf.swift/releases/tag/0.1.8

**Comment by mrbemani** [comment]
That was fast! Nice work!
