### ISSUE TITLE
Can't stop the broadcast

### ISSUE THREAD

**Issue by okpatil4u** [shogo4405/lf.swift#194]
I am using javascript webview to start and stop broadcast. Broadcast starts promptly, but when I try to stop my broadcast, it shows the log "Broadcast Stopped", which I added after I close and dispose my rtmp stream, but doesn't stop the broadcast. What am I doing wrong in here ?

        let sentData = message.body as! NSDictionary
        let sampleRate:Double = 44_100
        let rtmpConnection:RTMPConnection = RTMPConnection()
        let rtmpStream:RTMPStream = RTMPStream(connection: rtmpConnection)
        
        rtmpStream.syncOrientation = true
        rtmpStream.captureSettings = [
            "sessionPreset": AVCaptureSessionPreset1280x720,
            "continuousAutofocus": true,
            "continuousExposure": true,
        ]
        rtmpStream.videoSettings = [
            "width": 720,
            "height": 1280,
        ]
        rtmpStream.audioSettings = [
            "sampleRate": sampleRate
        ]
        rtmpStream.attachAudio(AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeAudio))
        rtmpStream.attachCamera(DeviceUtil.device(withPosition: .back))

        let command = sentData["cmd"] as! String
        if command == "startBroadcast"{
            guard let streamName = sentData["streamName"] as? String else{
                return
            }
            
            rtmpConnection.connect(streamURL)
            rtmpStream.publish(streamName)
            print("Broadcast Started")

            //var lfView:LFView = LFView(frame: view.bounds)
            //lfView.videoGravity = AVLayerVideoGravityResizeAspectFill
            //lfView.attachStream(rtmpStream)
            
            //response["count"] = count as AnyObject?
        }else if command == "stopBroadcast"{
            rtmpStream.close()
            rtmpStream.dispose()
            print("Broadcast Stopped")
        }

**Comment by shogo4405** [comment]
Are "startBroadcast" rtmpStream and "stopBroadcast" rtmpStream same instance?
It seems another instance....

**Comment by okpatil4u** [comment]
There is just one instance declared above. What do you suggest ?

**Comment by shogo4405** [comment]
Have to same instance.

Actually, I'm not sure how to use a webview. I can't suggest you.

**Comment by okpatil4u** [comment]
Is there a way to identify an instance id ?
