### ISSUE TITLE
Facebook aspectRatio always Squared

### ISSUE THREAD

**Issue by omarojo** [shogo4405/lf.swift#195]
Im implementing LF library to do livestreaming to Facebook.
But I found that.. when Im doing a portrait or landscape stream (720x1280 or 1280x720)
the aspect ratio of the streamed video.. is always squared **when visualizing the livestream in the facebook mobile app** but it looks fine and with the proper dimensions when visualizing in desktop browser.

**Comment by shogo4405** [comment]
I’m not sure.
Please consider to ask Facebook.

**Comment by omarojo** [comment]
It doesnt happen with other thirdparty iOS rtmp streaming libraries like VideoCore, only happens with LF. Its a little weird, I will post an issue request at Facebook to see if they know something.

**Comment by omarojo** [comment]
Im live streaming a video of resolution 720x1280 (Portrait).
The video looks portrait as it should.. when viewing in desktop browser, but when watching the live stream in facebook mobile app the aspect ratio is square. 

When the live stream finalizes and the VOD becomes available, The Portrait video has the proper aspect ratio when watching in Mobile app, as well as Desktop browser.

The previous issue doesnt happen when streaming 1280x720 (Landscape) 

Sample Video with the issue (Portrait): https://www.facebook.com/omarojo/videos/10154368386185754/
Sample Video withOUT the issue (Landscape): https://www.facebook.com/omarojo/videos/10154368432410754/

Note: because these videos are no longer in LIVE Mode, their aspect ratios are correct in all mobile and desktop players. The incorrect aspect ratio happens only when in Live Mode and viewing in the mobile app. 

Im also attaching screenshots during and after the stream.
![aspectratioissue](https://cloud.githubusercontent.com/assets/995265/23575239/e071688c-003e-11e7-88c3-419ae287726f.png)

**Comment by omarojo** [comment]
This issue has been fixed by Facebook ! :) 
so happy.
