### ISSUE TITLE
"Publish" to recording is not working

### ISSUE THREAD

**Issue by 7bp** [shogo4405/lf.swift#197]
iOS:

Whenever I try to "publish" to a recording file (using .localRecord) the stream always disconnects and the recording ends directly. The final recording file contains about 1 second only.

The last message in the logs is: 
error: AMF0Serializer{bytes:[2, 0, 5, 99, 108, 111, 115, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0],position:17,reference:AMFReference}

I tried this in my own project as well as using a fresh clone from this repository.

**Comment by shogo4405** [comment]
Would you tell me your server software name?

**Comment by 7bp** [comment]
The server is running FMS (Flash Media Server).

**Comment by 7bp** [comment]
Sorry. My mistake. I tried to publish two times (one live stream + localRecord). Thanks for your fast reply and your work here!
