### ISSUE TITLE
picture in picture

### ISSUE THREAD

**Issue by jackfreed** [shogo4405/lf.swift#198]
any way to support iPad's picture in picture multitasking mode, to allow recording while "in the background" ?

**Comment by shogo4405** [comment]
iOS not allow to use a camera and a microphone with picture in picture mode.
so framework can't support.

**Comment by jackfreed** [comment]
how about playback?

i know its still experimental but i already attached it to a GLLFView and its pretty nice :-)

**Comment by shogo4405** [comment]
I'm not sure :( I have never try to use a PiP.

https://developer.apple.com/library/content/samplecode/AVFoundationPiPPlayer/Introduction/Intro.html
