### ISSUE TITLE
Automatically reconnect after connectivity loss

### ISSUE THREAD

**Issue by 7bp** [shogo4405/lf.swift#199]
Is it possible to keep the recording running and restore the connection to the streaming server after a connection was lost - like a re-connect and publish without a complete re-initialization (e.g. recorder and muxer are stopped at the moment but could be reused if I'm not wrong?

Currently the connection is simply closed once the connectivity has been restored (and the recording will be stopped the same time).

**Comment by shogo4405** [comment]
Yes. framework has no automatically reconnect.

Please use RTMPStatus event and manually.
https://github.com/shogo4405/lf.swift/blob/master/Examples/iOS/Screencast/RTMPBroadcaster.swift#L64

**Comment by pvinis** [comment]
@shogo4405 i am also trying to do reconnection when the network goes down.

lets say i did `rtmpConn.connect(someUrl)` and then i did `rtmpStream.publish(someKey)`.
when the rtmp status goes `connectFailed` or `connectClosed`, do i need to call `connect`? or `connect` and `publish`?

**Comment by shogo4405** [comment]
@pvinis 
Please call `connect` and `publish`

**Comment by SeriousMax** [comment]
> @pvinis
> Please call `connect` and `publish`

Hi, @pvinis 

After **connectionClosed** (just turning off wifi) I'm trying to restore connection: I'm calling **rtmpConnection.connect**, than I'm waiting for **connectionSuccess** _rtmpStatus_, then I'm trying to call **rtmpStream.publish**, but after that connection is becomes **closed** again. After 2-3 retries connection becomes **success** and stream continues without any issues.

What am I doing wrong?

**Comment by pvinis** [comment]
I haven't worked with this for about 3 years, so I don't think I can help you at this point. Sorry and good luck!
