### ISSUE TITLE
ipad2 ,ipadMini 1,iphone 5C cant send Audio 

### ISSUE THREAD

**Issue by aruku773** [shogo4405/lf.swift#20]
Following devices unable to stream audio to wowza server
ipadMini 1 (Model A1455)
ipad 2 (A1396)
iphone 5C (A1529)

Seems like all old ipads have this issue.

In AACEncoder.swift it fails at the following line while converting the audio. This method returns -50
status = fillComplexBuffer(&outputDataPacketSize, outOutputData: &outOutputData, outPacketDescription: nil)

Anyone faced the same issue ?

**Comment by serbintv** [comment]
Hi!

Have the same issue on iPhone 4s and iPod 5th. 
Try to add this line in file AACEncoder.swift
_inDestinationFormat!.mBytesPerFrame = 0

If it doesn't fix your trouble also try comment line 
 AudioClassDescription(mType: kAudioEncoderComponentType, mSubType: kAudioFormatMPEG4AAC, mManufacturer: kAppleHardwareAudioCodecManufacturer),

**Comment by shogo4405** [comment]
https://github.com/shogo4405/lf.swift/issues/17

**Comment by aruku773** [comment]
As suggested by serbintv , commenting  the below line solved the problem. Thanks for the solution

AudioClassDescription(mType: kAudioEncoderComponentType, mSubType: kAudioFormatMPEG4AAC, mManufacturer: kAppleHardwareAudioCodecManufacturer),

**Comment by shogo4405** [comment]
released 0.1.8 https://github.com/shogo4405/lf.swift/releases/tag/0.1.8
