### ISSUE TITLE
RPBroadcastSampleHandler (ReplayKitLive) Huge Delay

### ISSUE THREAD

**Issue by justinoverton** [shogo4405/lf.swift#202]
I had to make quite a few changes to get this to work with quality, and most of them are probably breaking for existing camera functionality. I'll try and refactor my changes out so they don't affect things and do a pull request.

I haven't used this with camera streaming, just replaykit live. There's about a 10 to 15 second delay in the stream. Is this normal? Any idea what settings I might look at to try to improve it?

**Comment by shogo4405** [comment]
In my case. a 2 to 3 second delay.
iOS(ReplayKit) -- [RTMP] --> Wowza(localhost) -- [RTMP] --> FlashPlayer.
