### ISSUE TITLE
No Audio on Some Devices

### ISSUE THREAD

**Issue by Nightsd01** [shogo4405/lf.swift#203]
Hi Shogo, I want to say, you have done such an amazing job with this library, I am incredibly impressed and thankful!

On some devices, broadcasting RTMP HLS video streams are always muted. On other devices, audio works perfectly without any issues. It is unrelated to bluetooth/external audio devices. I have been fighting with this for days and there seems to be absolutely no reason I can find. It just works on some devices, and NEVER works on some other devices. The same iPhone 7 always has this issue, while a different 7 Plus _never_ has this issue.

I've been able to confirm it's not an issue with the stream server or the client (it's muted even in VLC). It's also not a hardware issue since the same devices can record audio (in videos) using the Camera app just fine. I've even tried telling AVAudioSession to use different microphones on the device itself (front, bottom, etc) and none worked.

Our company has 12 test devices, 9 of them work perfectly fine and 3 have this issue (a 6S Plus, and two 7's)

iOS 10.2.1
Swift 3
lf 0.5.10

Here is my code:

        self.sampleRate = 44100;
        self.connection = RTMPConnection();
        self.stream = RTMPStream(connection: self.connection!);

        self.stream?.syncOrientation = true;
        do {
            try AVAudioSession.sharedInstance().setPreferredSampleRate(self.sampleRate)
            try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord)
            try AVAudioSession.sharedInstance().setMode(AVAudioSessionModeDefault)
            try AVAudioSession.sharedInstance().setActive(true)
        } catch {
                NSLog("Unable to activate audio session");
        }
        
        self.stream?.audioSettings = [
            "sampleRate": self.sampleRate,
            "muted" : false,
            "bitrate" : 32 * 1024
         ]
        
        self.stream?.captureSettings = [
            "sessionPreset": AVCaptureSessionPresetMedium,
            "continuousAutofocus": true,
            "continuousExposure": true,
        ]
        
        self.stream?.videoSettings = [
            "width": 320, // video output width
            "height": 568, // video output height
            "bitrate": 320 * 1024, // video output bitrate
            // "dataRateLimits": [160 * 1024 / 8, 1], optional kVTCompressionPropertyKey_DataRateLimits property
            "profileLevel": kVTProfileLevel_H264_Baseline_3_1, // H264 Profile require "import VideoToolbox"
            "maxKeyFrameIntervalDuration": 2, // key frame / sec
        ]
        
        // "0" means the same of input
        self.stream?.recorderSettings = [
            AVMediaTypeAudio: [
                AVFormatIDKey: Int(kAudioFormatMPEG4AAC),
                AVSampleRateKey: 0,
                AVNumberOfChannelsKey: 0,
            ],
            AVMediaTypeVideo: [
                AVVideoCodecKey: AVVideoCodecH264,
                AVVideoHeightKey: 0,
                AVVideoWidthKey: 0,
            ],
        ]
        
        self.stream?.attachCamera(DeviceUtil.device(withPosition: .back));
        
        self.stream!.attachAudio(AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeAudio));

**Comment by shogo4405** [comment]
> Our company has 12 test devices, 9 of them work perfectly fine and 3 have this issue (a 6S Plus, and two 7's)
I have no these devices :( Please tell me 3 devices. I try to prepare...
1. iPhone 6S Plus
2. iPhone 7
3. ??????

**Comment by shogo4405** [comment]
How about this?

    self.sampleRate = 48000;
    self.stream?.syncOrientation = true;
    do {
        try AVAudioSession.sharedInstance().setPreferredSampleRate(self.sampleRate)
        try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord)
        try AVAudioSession.sharedInstance().setMode(AVAudioSessionModeVideoChat)
        //                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
        try AVAudioSession.sharedInstance().setActive(true)
    } catch {
            NSLog("Unable to activate audio session");
    }
    
    self.stream?.audioSettings = [
        // "sampleRate": self.sampleRate, <- comment out here.
        "muted" : false,
        "bitrate" : 32 * 1024
     ]

**Comment by Nightsd01** [comment]
Hey Shogo, thanks for your fast response! 

The 3 devices are: iPhone 6S Plus, and 2x iPhone 7's. 

I have used the settings you've suggested just now and it still has the same issue. Please let me know if there's anything I can send you that might make it easier to discover the problem, I can send you the entire source file, a recorded example of the video itself, etc. Just let me know, thanks!

**Comment by shogo4405** [comment]
Please set an attachAudio method 2nd argument to false.
see also https://github.com/shogo4405/lf.swift/issues/58 
``` swift
rtmpStream.attachAudio(AVCaptureDevice.defaultDeviceWithMediaType(AVMediaTypeAudio), automaticallyConfiguresApplicationAudioSession: false)
```

**Comment by Nightsd01** [comment]
Hey Shogo, thanks, I tried this and the same issue still happens on the same devices.

Here are some examples of the problem. 

        hls = "https://d1lugopol1lmon.cloudfront.net/live-nightsd02-1490214169455/index.m3u8";
        "mp4_224p" = "https://d1lugopol1lmon.cloudfront.net/live-nightsd02-1490214169455/400x224.mp4";
        "mp4_360p" = "https://d1lugopol1lmon.cloudfront.net/live-nightsd02-1490214169455/640x360.mp4";
        "mp4_720p" = "https://d1lugopol1lmon.cloudfront.net/live-nightsd02-1490214169455/1280x720.mp4";
        "webm_224p" = "https://d1lugopol1lmon.cloudfront.net/live-nightsd02-1490214169455/400x224.webm";
        "webm_360p" = "https://d1lugopol1lmon.cloudfront.net/live-nightsd02-1490214169455/640x360.webm";
        "webm_720p" = "https://d1lugopol1lmon.cloudfront.net/live-nightsd02-1490214169455/1280x720.webm";

I've also tried the same exact AVAudioSession settings & RTMP audio settings you posted in #58 and the same issue still occurs there as well. I've pretty much tried every possible combination of settings, messing with different sampling rates, and so on.

If it helps, here is the entire source file I am using to interface with lf:

`//
//  LiveVideoStreamer.swift
//  HaulsTV
//
//  Created by Brad Hesse on 12/6/16.
//  Copyright © 2016 PayWall, Inc. All rights reserved.
//

import Foundation
import lf
import UIKit
import AVFoundation
import VideoToolbox

public enum StreamState
{
    case running;
    case paused;
    case closed;
}

public enum CameraType
{
    case front;
    case back;
}

class LiveVideoStreamer
{
    var connection : RTMPConnection?;
    var stream : RTMPStream?;
    var state = StreamState.closed;
    let sampleRate:Double = 48_000 // or 44_100
    var secureStreamUrl = "";
    var streamName = "";
    var cameraType : CameraType = .back;
    var diagnosticTimer : Timer?;
    var diagnosticBlock : ((_ diags: String) -> Void)?;
    var iteration = 0;
    var audioCaptureDevice : AVCaptureDevice!;
    
    func embedStreamInView(_ view: UIView) -> GLLFView
    {
        self.connection = RTMPConnection();
        self.stream = RTMPStream(connection: self.connection!);
        
        self.stream?.syncOrientation = true;
        
        do {
            try AVAudioSession.sharedInstance().setPreferredSampleRate(self.sampleRate)
            try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord)
            try AVAudioSession.sharedInstance().setMode(AVAudioSessionModeVideoChat)
            try AVAudioSession.sharedInstance().setActive(true)
        } catch let error {
            HaulsLogger.logStatement("ENCOUNTERED AN ERROR ACTIVATING AUDIO SESSION: \(error)");
        }
        
        self.stream?.audioSettings = [
            "sampleRate": self.sampleRate,
            "muted" : false
        ]
        
        self.stream?.captureSettings = [
            "sessionPreset": AVCaptureSessionPreset1280x720,
            "continuousAutofocus": true,
            "continuousExposure": true,
        ]
        
        self.stream?.videoSettings = [
            "width": 320, // video output width
            "height": 568, // video output height
            "bitrate": 320 * 1024, // video output bitrate
            // "dataRateLimits": [160 * 1024 / 8, 1], optional kVTCompressionPropertyKey_DataRateLimits property
            "profileLevel": kVTProfileLevel_H264_Baseline_4_1, // H264 Profile require "import VideoToolbox"
            "maxKeyFrameIntervalDuration": 2, // key frame / sec
        ]
        
        // "0" means the same of input
        self.stream?.recorderSettings = [
            AVMediaTypeAudio: [
                AVFormatIDKey: Int(kAudioFormatMPEG4AAC),
                AVSampleRateKey: 0,
                AVNumberOfChannelsKey: 0,
            ],
            AVMediaTypeVideo: [
                AVVideoCodecKey: AVVideoCodecH264,
                AVVideoHeightKey: 0,
                AVVideoWidthKey: 0,
            ],
        ]
        
        self.stream?.attachCamera(DeviceUtil.device(withPosition: .back));
        
        self.stream!.attachAudio(AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeAudio), automaticallyConfiguresApplicationAudioSession: false);
        
        self.diagnosticTimer = Timer.scheduledTimer(timeInterval: 1, target: self, selector: #selector(self.diags), userInfo: nil, repeats: true);
        
        let liveFeedView = self.generatePreviewView(view);
        
        return liveFeedView;
    }
    
    func deconstruct()
    {
        self.diagnosticTimer?.invalidate();
        self.stream?.close();
    }
    
    func generatePreviewView(_ view: UIView) -> GLLFView
    {
        if (UIDevice.current.userInterfaceIdiom == .pad) {
            let size = (view.frame.size.width > view.frame.size.height) ? view.frame.size.width : view.frame.size.height;
            let liveFeedView = GLLFView(frame: CGRect(x: 0, y: 0, width: size, height: size));
            self.addLiveView(liveFeedView, view: view);
            return liveFeedView;
        } else {
            
            let liveFeedView = GLLFView(frame: view.bounds);
            self.addLiveView(liveFeedView, view: view);
            return liveFeedView;
        }
        
    }
    
    func addLiveView(_ liveFeedView: GLLFView, view: UIView)
    {
        NSLog("ATTACHING STREAM ---");
        liveFeedView.videoGravity = AVLayerVideoGravityResizeAspectFill;
        liveFeedView.attachStream(self.stream!);
        view.addSubview(liveFeedView);
        view.sendSubview(toBack: liveFeedView);
        liveFeedView.backgroundColor = UIColor.black;
        
        let leadingConstraint = NSLayoutConstraint(item: liveFeedView, attribute: .leading, relatedBy: .equal, toItem: view, attribute: .leading, multiplier: 1.0, constant: 0.0);
        let trailingConstraint = NSLayoutConstraint(item: liveFeedView, attribute: .trailing, relatedBy: .equal, toItem: view, attribute: .trailing, multiplier: 1.0, constant: 0.0);
        let topConstraint = NSLayoutConstraint(item: liveFeedView, attribute: .top, relatedBy: .equal, toItem: view, attribute: .top, multiplier: 1.0, constant: 0.0);
        let bottomConstraint = NSLayoutConstraint(item: liveFeedView, attribute: .bottom, relatedBy: .equal, toItem: view, attribute: .bottom, multiplier: 1.0, constant: 0.0);
        
        view.addConstraint(leadingConstraint);
        view.addConstraint(trailingConstraint);
        view.addConstraint(topConstraint);
        view.addConstraint(bottomConstraint);
    }
    
    func canUseTorch() -> Bool
    {
        if (self.cameraType == .back) {
            return true;
        } else {
            return false;
        }
    }
    
    @objc func diags()
    {
        if (self.state == .running) {
            self.diagnosticBlock?("DIAGNOSTIC INFO: \nBYTES IN PER SECOND: \(self.connection?.currentBytesInPerSecond)\nBYTES OUT PER SECOND: \(self.connection?.currentBytesOutPerSecond)\nCONNECTED: \(self.connection?.connected)\nFLASH VER: \(self.connection?.flashVer)\nSECONDS: \(self.iteration), \(self.stream?.audioSettings)");
            self.iteration += 1;
        } else {
            
        }
    }
    
    func orientationWillChange()
    {
        
    }
    
    func orientationDidChange()
    {
        Wait.waitForInterval(0.1) {
            NSLog("STREAMER DID CHANGE ORIENTATION");
        }
    }
    
    func prepareStream(_ credentials: (username: String, password: String), streamName: String, streamUrl: String, port: String)
    {
        self.secureStreamUrl = "rtmp://" + credentials.username + ":" + credentials.password + "@" + streamUrl +
            ":" + port + "/" + "live";
        self.streamName = streamName;
    }
    
    func beginStream()
    {
        
        HaulsLogger.logStatement("URL: \(self.secureStreamUrl)");
        
        self.connection?.connect(self.secureStreamUrl.URLEncodedString()!, arguments: nil);
        self.stream?.publish(self.streamName);
        self.state = StreamState.running;
    }
    
    func switchCamera()
    {
        if (self.cameraType == .back) {
            self.stream?.attachCamera(DeviceUtil.device(withPosition: .front));
            self.cameraType = .front;
        } else {
            self.stream?.attachCamera(DeviceUtil.device(withPosition: .back));
            self.cameraType = .back;
        }
    }
    
    func endStream()
    {
        self.stream?.close();
        self.state = StreamState.closed;
    }
}
`

**Comment by Nightsd01** [comment]
Alright! I have figured out the problem.

It looks like the problem was that I was creating the stream and the GLLFView and adding it to the view **immediately** when the view controller was presented. However, my app lets users pick a Thumbnail image to display as the thumbnail for the stream. 

It appears like something with the UIImagePickerController screws with the audio for the stream.

The solution: do NOT create the RTMPStream or GLLFView/LFView immediately if the user will be able to present a UIImagePickerController. Instead, create your own camera preview layer (using AVCaptureVideoPreviewLayer) and present that instead. Once the user has finished using the UIImagePickerController and you are ready to begin the stream, remove the AVCaptureVideoPreviewLayer and create the stream & CLLFView/LFView and add it to your view. This appears to resolve the audio issue on every device our company owns.

Thanks so much for your help Shogo! Maybe for a future release it might be best to figure out why a temporary UIImagePickerController being presented causes issues with the audio stream. Might be a bug in AVFoundation itself! Thanks 👍

**Comment by RamzyChatti90** [comment]
hello,
I have the same problem with my app using my Iphone 6S could you tell me more how to solve the problem plz

**Comment by Rupasekhar** [comment]
Hi,
i've kept the same sample rate in my code, rtmpStream.audioSettings = [
"sampleRate": 48_000
]

rtmpStream.audioSettings = [
"sampleRate": 41_000
]
But I'm having low audio issue in iPhone 6S Plus and Higher devices.
Can you please figure out what might be the issue in this..?
