### ISSUE TITLE
Infinite listen loop

### ISSUE THREAD

**Issue by jbiscarri** [shogo4405/lf.swift#209]
I'm having problems connecting with a rtmp server implementing this protocol (I don't have access to its implementation:
http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/rtmp/pdf/rtmp_specification_1.0.pdf

Execution enters in infinite loop (listen function) after handshake.
The problem comes in las listen command:
```
if (position < bytes.count) {
            listen(bytes: Array(bytes[position..<bytes.count]))
        }
```
current chunk is not null and is setting position to 0 value always.

Any idea?

LOG:

> 2017-04-03 18:56:28.195 [Info] [AACEncoder.swift:81] inSourceFormat > nil
> 2017-04-03 18:56:28.204 [Info] [VideoIOComponent.swift:32] fps > (30.0, __C.CMTime(value: 100, timescale: 3000, flags: __C.CMTimeFlags(rawValue: 1), epoch: 0))
> 2017-04-03 18:56:28.212 [Info] [VideoIOComponent.swift:32] fps > (30.0, __C.CMTime(value: 100, timescale: 3000, flags: __C.CMTimeFlags(rawValue: 1), epoch: 0))
> 2017-04-03 18:56:39.602 [Error] [RTMPMessage.swift:318] payload > AMF0Serializer{bytes:[2, 0, 11, 111, 110, 70, 67, 80, 117, 98, 108, 105, 115, 104],position:14,reference:lf.AMFReference}
> 2017-04-03 18:56:39.787 [Error] [RTMPMessage.swift:59] create > 0
> 2017-04-03 18:56:39.791 [Error] [RTMPChunk.swift:249] bytes > [0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 0, 196, 20, 1, 0, 0, 0, 2, 0, 8, 111, 110, 83, 116, 97, 116, 117, 115, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 3, 0, 5, 108, 101, 118, 101, 108, 2, 0, 6, 115, 116, 97, 116, 117, 115, 0, 4, 99, 111, 100, 101, 2, 0, 23, 78, 101, 116, 83, 116, 114, 101, 97, 109, 46, 80, 117, 98, 108, 105, 115, 104, 46, 83, 116, 97, 114, 116, 0, 11, 100, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 2, 0, 43, 78, 84, 70, 105, 77, 68, 65, 119, 90, 106, 70, 108, 77, 68, 81, 52, 77, 84, 73, 48, 89, 49, 57, 102, 77, 81, 32, 105, 115, 32, 110, 111, 119, 32, 112, 117, 98, 108, 105, 115, 104, 101, 195, 100, 0, 7, 100, 101, 116, 97, 105, 108, 115, 2, 0, 26, 78, 84, 70, 105, 77, 68, 65, 119, 90, 106, 70, 108, 77, 68, 81, 52, 77, 84, 73, 48, 89, 49, 57, 102, 77, 81, 0, 8, 99, 108, 105, 101, 110, 116, 105, 100, 2, 0, 13, 76, 97, 118, 102, 53, 55, 46, 53, 55, 46, 49, 48, 48, 0, 0, 9]

**Comment by shogo4405** [comment]
Could you tell me server name?
Wowza or FMS?

**Comment by jbiscarri** [comment]
It's a private FMS server...

**Comment by shogo4405** [comment]
@jbiscarri 
Plase tell me FMS version and library version.

Related Issues is here.
https://github.com/shogo4405/lf.swift/issues/200

**Comment by jbiscarri** [comment]
Library version is the last. I don't have the server version and I'm not sure if it is an FMS... I know server side is using: rtmpsrv (rtmpdump v2.1) with ffmpeg

**Comment by shogo4405** [comment]
OK. As the reason for this, Framework can't parse RTMPPacket.
I want to see a full packet. Could you show me fullpacket?

```
XCGLogger.default.setup(
    level: .verbose, // default is .info
    // ~~~~~~~~~~~~~
    showLogIdentifier: true,
    showFunctionName: true,
    showThreadName: true,
    showLevel: true,
    showFileNames: false,
    showLineNumbers: true,
    showDate: true,
    writeToFile: nil,
    fileLevel: nil
)
```

**Comment by jbiscarri** [comment]
Hi,
This is the verbose log with all packets received:

2017-04-04 15:46:38.444 [Verbose]
> [com.cerebralgardens.xcglogger.defaultInstance]
> [com.github.shogo4405.lf.NetSocket.network] [79] doOutput(chunk:locked:) >
> RTMPChunk{size:0,type:zero,streamId:3,message:Optional(RTMPCommandMessage{type:amf0Command,length:278,streamId:0,timestamp:0,payload:[2,
> 0, 7, 99, 111, 110, 110, 101, 99, 116, 0, 63, 240, 0, 0, 0, 0, 0, 0, 3, 0,
> 11, 118, 105, 100, 101, 111, 67, 111, 100, 101, 99, 115, 0, 64, 96, 0, 0,
> 0, 0, 0, 0, 0, 5, 116, 99, 85, 114, 108, 2, 0, 35, 114, 116, 109, 112, 58,
> 47, 47, 114, 116, 109, 112, 45, 100, 101, 118, 46, 116, 101, 108, 101, 115,
> 99, 111, 112, 101, 46, 116, 118, 58, 56, 48, 47, 99, 118, 115, 0, 8, 102,
> 108, 97, 115, 104, 86, 101, 114, 2, 0, 31, 70, 77, 76, 69, 47, 51, 46, 48,
> 32, 40, 99, 111, 109, 112, 97, 116, 105, 98, 108, 101, 59, 32, 70, 77, 83,
> 99, 47, 49, 46, 48, 41, 0, 3, 97, 112, 112, 2, 0, 3, 99, 118, 115, 0, 13,
> 118, 105, 100, 101, 111, 70, 117, 110, 99, 116, 105, 111, 110, 0, 63, 240,
> 0, 0, 0, 0, 0, 0, 0, 6, 115, 119, 102, 85, 114, 108, 5, 0, 4, 102, 112, 97,
> 100, 1, 0, 0, 12, 99, 97, 112, 97, 98, 105, 108, 105, 116, 105, 101, 115,
> 0, 64, 109, 224, 0, 0, 0, 0, 0, 0, 11, 97, 117, 100, 105, 111, 67, 111,
> 100, 101, 99, 115, 0, 64, 144, 0, 0, 0, 0, 0, 0, 0, 7, 112, 97, 103, 101,
> 85, 114, 108, 5, 0, 14, 111, 98, 106, 101, 99, 116, 69, 110, 99, 111, 100,
> 105, 110, 103, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
> 9],objectEncoding:0,commandName:connect,transactionId:1,commandObject:Optional(["videoCodecs":
> Optional(128), "tcUrl": Optional("rtmp://rtmp-dev.telescope.tv:80/cvs"),
> "flashVer": Optional("FMLE/3.0 (compatible; FMSc/1.0)"), "app":
> Optional("cvs"), "videoFunction": Optional(1), "swfUrl": nil, "fpad":
> Optional(false), "capabilities": Optional(239), "audioCodecs":
> Optional(1024), "pageUrl": nil, "objectEncoding":
> Optional(0)]),arguments:[],serializer:AMF0Serializer{bytes:[],position:0,reference:lf.AMFReference}}),fragmented:false,_bytes:[3,
> 0, 0, 0, 0, 1, 10, 20, 0, 0, 0, 0]}
> 2017-04-04 15:46:38.805 [Verbose]
> [com.cerebralgardens.xcglogger.defaultInstance]
> [com.github.shogo4405.lf.NetSocket.network] [451] listen(bytes:) >
> RTMPChunk{size:128,type:zero,streamId:2,message:Optional(RTMPWindowAcknowledgementSizeMessage{type:windowAck,length:4,streamId:0,timestamp:0,payload:[0,
> 38, 37, 160],size:2500000}),fragmented:false,_bytes:[2, 0, 0, 0, 0, 0, 4,
> 5, 0, 0, 0, 0]}
> 2017-04-04 15:46:38.805 [Verbose]
> [com.cerebralgardens.xcglogger.defaultInstance]
> [com.github.shogo4405.lf.NetSocket.network] [79] doOutput(chunk:locked:) >
> RTMPChunk{size:0,type:zero,streamId:2,message:Optional(RTMPWindowAcknowledgementSizeMessage{type:windowAck,length:16,streamId:0,timestamp:0,payload:[0,
> 38, 37, 160],size:2500000}),fragmented:false,_bytes:[2, 0, 0, 0, 0, 0, 4,
> 5, 0, 0, 0, 0]}
> 2017-04-04 15:46:38.806 [Verbose]
> [com.cerebralgardens.xcglogger.defaultInstance]
> [com.github.shogo4405.lf.NetSocket.network] [451] listen(bytes:) >
> RTMPChunk{size:128,type:one,streamId:2,message:Optional(RTMPSetPeerBandwidthMessage{type:bandwidth,length:5,streamId:0,timestamp:0,payload:[0,
> 38, 37, 160, 2],size:2500000,limit:dynamic}),fragmented:false,_bytes:[66,
> 0, 0, 0, 0, 0, 5, 6]}
> 2017-04-04 15:46:38.808 [Verbose]
> [com.cerebralgardens.xcglogger.defaultInstance]
> [com.github.shogo4405.lf.NetSocket.network] [451] listen(bytes:) >
> RTMPChunk{size:128,type:one,streamId:2,message:Optional(RTMPUserControlMessage{type:user,length:6,streamId:0,timestamp:0,payload:[0,
> 0, 0, 0, 0, 0],event:streamBegin,value:0}),fragmented:false,_bytes:[66, 0,
> 0, 0, 0, 0, 6, 4]}
> 2017-04-04 15:46:38.808 [Verbose]
> [com.cerebralgardens.xcglogger.defaultInstance]
> [com.github.shogo4405.lf.NetSocket.network] [451] listen(bytes:) >
> RTMPChunk{size:128,type:zero,streamId:3,message:Optional(RTMPSetChunkSizeMessage{type:chunkSize,length:4,streamId:0,timestamp:0,payload:[0,
> 0, 0, 128],size:128}),fragmented:false,_bytes:[3, 0, 0, 0, 0, 0, 4, 1, 0,
> 0, 0, 0]}
> 2017-04-04 15:46:38.810 [Verbose]
> [com.cerebralgardens.xcglogger.defaultInstance]
> [com.github.shogo4405.lf.NetSocket.network] [451] listen(bytes:) >
> RTMPChunk{size:128,type:one,streamId:3,message:Optional(RTMPCommandMessage{type:amf0Command,length:190,streamId:0,timestamp:0,payload:[2,
> 0, 7, 95, 114, 101, 115, 117, 108, 116, 0, 63, 240, 0, 0, 0, 0, 0, 0, 3, 0,
> 6, 102, 109, 115, 86, 101, 114, 2, 0, 13, 70, 77, 83, 47, 51, 44, 48, 44,
> 49, 44, 49, 50, 51, 0, 12, 99, 97, 112, 97, 98, 105, 108, 105, 116, 105,
> 101, 115, 0, 64, 63, 0, 0, 0, 0, 0, 0, 0, 0, 9, 3, 0, 5, 108, 101, 118,
> 101, 108, 2, 0, 6, 115, 116, 97, 116, 117, 115, 0, 4, 99, 111, 100, 101, 2,
> 0, 29, 78, 101, 116, 67, 111, 110, 110, 101, 99, 116, 105, 111, 110, 46,
> 67, 111, 110, 110, 101, 99, 116, 46, 83, 117, 99, 99, 101, 115, 115, 0, 11,
> 100, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 2, 0, 21, 67, 111,
> 110, 110, 101, 99, 116, 105, 111, 110, 32, 115, 117, 99, 99, 101, 101, 100,
> 101, 100, 46, 0, 14, 111, 98, 106, 101, 99, 116, 69, 110, 99, 111, 100,
> 105, 110, 103, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
> 9],objectEncoding:0,commandName:_result,transactionId:1,commandObject:Optional(["fmsVer":
> Optional("FMS/3,0,1,123"), "capabilities":
> Optional(31.0)]),arguments:[Optional(["description": Optional("Connection
> succeeded."), "level": Optional("status"), "code":
> Optional("NetConnection.Connect.Success"), "objectEncoding":
> Optional(0.0)])],serializer:AMF0Serializer{bytes:[],position:0,reference:lf.AMFReference}}),fragmented:false,_bytes:[67,
> 0, 0, 0, 0, 0, 190, 20]}
> 2017-04-04 15:46:38.811 [Verbose]
> [com.cerebralgardens.xcglogger.defaultInstance]
> [com.github.shogo4405.lf.NetSocket.network] [79] doOutput(chunk:locked:) >
> RTMPChunk{size:0,type:one,streamId:2,message:Optional(RTMPSetChunkSizeMessage{type:chunkSize,length:12,streamId:0,timestamp:0,payload:[0,
> 0, 32, 0],size:8192}),fragmented:false,_bytes:[66, 0, 0, 0, 0, 0, 4, 1]}
> 2017-04-04 15:46:38.811 [Verbose]
> [com.cerebralgardens.xcglogger.defaultInstance]
> [com.github.shogo4405.lf.NetSocket.network] [79] doOutput(chunk:locked:) >
> RTMPChunk{size:0,type:zero,streamId:3,message:Optional(RTMPCommandMessage{type:amf0Command,length:37,streamId:0,timestamp:0,payload:[2,
> 0, 12, 99, 114, 101, 97, 116, 101, 83, 116, 114, 101, 97, 109, 0, 64, 0, 0,
> 0, 0, 0, 0, 0,
> 5],objectEncoding:0,commandName:createStream,transactionId:2,commandObject:nil,arguments:[],serializer:AMF0Serializer{bytes:[],position:0,reference:lf.AMFReference}}),fragmented:false,_bytes:[3,
> 0, 0, 0, 0, 0, 25, 20, 0, 0, 0, 0]}
> 2017-04-04 15:46:38.813 [Verbose]
> [com.cerebralgardens.xcglogger.defaultInstance]
> [com.github.shogo4405.lf.NetSocket.network] [451] listen(bytes:) >
> RTMPChunk{size:128,type:one,streamId:3,message:Optional(RTMPCommandMessage{type:amf0Command,length:30,streamId:0,timestamp:0,payload:[2,
> 0, 8, 111, 110, 66, 87, 68, 111, 110, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0,
> 64, 192, 0, 0, 0, 0, 0,
> 0],objectEncoding:0,commandName:onBWDone,transactionId:0,commandObject:Optional([:]),arguments:[Optional(8192.0)],serializer:AMF0Serializer{bytes:[],position:0,reference:lf.AMFReference}}),fragmented:false,_bytes:[67,
> 0, 0, 0, 0, 0, 30, 20]}
> 2017-04-04 15:46:39.278 [Verbose]
> [com.cerebralgardens.xcglogger.defaultInstance]
> [com.github.shogo4405.lf.NetSocket.network] [451] listen(bytes:) >
> RTMPChunk{size:128,type:one,streamId:3,message:Optional(RTMPCommandMessage{type:amf0Command,length:29,streamId:0,timestamp:0,payload:[2,
> 0, 7, 95, 114, 101, 115, 117, 108, 116, 0, 64, 0, 0, 0, 0, 0, 0, 0, 5, 0,
> 63, 240, 0, 0, 0, 0, 0,
> 0],objectEncoding:0,commandName:_result,transactionId:2,commandObject:Optional([:]),arguments:[Optional(1.0)],serializer:AMF0Serializer{bytes:[],position:0,reference:lf.AMFReference}}),fragmented:false,_bytes:[67,
> 0, 0, 0, 0, 0, 29, 20]}
> 2017-04-04 15:46:39.278 [Verbose]
> [com.cerebralgardens.xcglogger.defaultInstance]
> [com.github.shogo4405.lf.NetStream.lock] [79] doOutput(chunk:locked:) >
> RTMPChunk{size:0,type:zero,streamId:3,message:Optional(RTMPCommandMessage{type:amf0Command,length:63,streamId:0,timestamp:0,payload:[2,
> 0, 9, 70, 67, 80, 117, 98, 108, 105, 115, 104, 0, 64, 8, 0, 0, 0, 0, 0, 0,
> 5, 2, 0, 26, 78, 84, 70, 105, 77, 68, 65, 119, 90, 106, 70, 108, 77, 68,
> 81, 52, 77, 84, 73, 48, 89, 49, 57, 102, 77,
> 81],objectEncoding:0,commandName:FCPublish,transactionId:3,commandObject:nil,arguments:[Optional("NTFiMDAwZjFlMDQ4MTI0Y19fMQ")],serializer:AMF0Serializer{bytes:[],position:0,reference:lf.AMFReference}}),fragmented:false,_bytes:[3,
> 0, 0, 0, 0, 0, 51, 20, 0, 0, 0, 0]}
> 2017-04-04 15:46:39.279 [Verbose]
> [com.cerebralgardens.xcglogger.defaultInstance]
> [com.github.shogo4405.lf.NetStream.lock] [79] doOutput(chunk:locked:) >
> RTMPChunk{size:0,type:zero,streamId:4,message:Optional(RTMPCommandMessage{type:amf0Command,length:68,streamId:1,timestamp:0,payload:[2,
> 0, 7, 112, 117, 98, 108, 105, 115, 104, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 2, 0,
> 26, 78, 84, 70, 105, 77, 68, 65, 119, 90, 106, 70, 108, 77, 68, 81, 52, 77,
> 84, 73, 48, 89, 49, 57, 102, 77, 81, 2, 0, 4, 108, 105, 118,
> 101],objectEncoding:0,commandName:publish,transactionId:0,commandObject:nil,arguments:[Optional("NTFiMDAwZjFlMDQ4MTI0Y19fMQ"),
> Optional("live")],serializer:AMF0Serializer{bytes:[],position:0,reference:lf.AMFReference}}),fragmented:false,_bytes:[4,
> 0, 0, 0, 0, 0, 56, 20, 1, 0, 0, 0]}
> 2017-04-04 15:46:39.466 [Error]
> [com.cerebralgardens.xcglogger.defaultInstance]
> [com.github.shogo4405.lf.NetSocket.network] [318] payload >
> AMF0Serializer{bytes:[2, 0, 11, 111, 110, 70, 67, 80, 117, 98, 108, 105,
> 115, 104],position:14,reference:lf.AMFReference}
> 2017-04-04 15:46:39.467 [Verbose]
> [com.cerebralgardens.xcglogger.defaultInstance]
> [com.github.shogo4405.lf.NetSocket.network] [451] listen(bytes:) >
> RTMPChunk{size:128,type:one,streamId:3,message:Optional(RTMPCommandMessage{type:amf0Command,length:14,streamId:0,timestamp:0,payload:[2,
> 0, 11, 111, 110, 70, 67, 80, 117, 98, 108, 105, 115,
> 104],objectEncoding:0,commandName:onFCPublish,transactionId:0,commandObject:nil,arguments:[],serializer:AMF0Serializer{bytes:[],position:0,reference:lf.AMFReference}}),fragmented:false,_bytes:[67,
> 0, 0, 0, 0, 0, 14, 20]}


2017-04-04 14:42 GMT+02:00 shogo4405 <notifications@github.com>:

**Comment by shogo4405** [comment]
@jbiscarri 
Hi. It seems looks OK this log.

**Comment by jbiscarri** [comment]
@shogo4405 But Framework crashes after infinite loop. What can I do to make It work?

**Comment by shogo4405** [comment]
@jbiscarri 
Where is this line?

>2017-04-03 18:56:39.602 [Error] [RTMPMessage.swift:318] payload > AMF0Serializer{bytes:[2, 0, 11, 111, 110, 70, 67, 80, 117, 98, 108, 105, 115, 104],position:14,reference:lf.AMFReference}
>2017-04-03 18:56:39.787 [Error] [RTMPMessage.swift:59] create > 0
>2017-04-03 18:56:39.791 [Error] [RTMPChunk.swift:249] bytes > [0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 0, 196, 20, 1, 0, 0, 0, 2, 0, 8, 111, 110, 83, 116, 97, 116, 117, 115, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 3, 0, 5, 108, 101, 118, 101, 108, 2, 0, 6, 115, 116, 97, 116, 117, 115, 0, 4, 99, 111, 100, 101, 2, 0, 23, 78, 101, 116, 83, 116, 114, 101, 97, 109, 46, 80, 117, 98, 108, 105, 115, 104, 46, 83, 116, 97, 114, 116, 0, 11, 100, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 2, 0, 43, 78, 84, 70, 105, 77, 68, 65, 119, 90, 106, 70, 108, 77, 68, 81, 52, 77, 84, 73, 48, 89, 49, 57, 102, 77, 81, 32, 105, 115, 32, 110, 111, 119, 32, 112, 117, 98, 108, 105, 115, 104, 101, 195, 100, 0, 7, 100, 101, 116, 97, 105, 108, 115, 2, 0, 26, 78, 84, 70, 105, 77, 68, 65, 119, 90, 106, 70, 108, 77, 68, 81, 52, 77, 84, 73, 48, 89, 49, 57, 102, 77, 81, 0, 8, 99, 108, 105, 101, 110, 116, 105, 100, 2, 0, 13, 76, 97, 118, 102, 53, 55, 46, 53, 55, 46, 49, 48, 48, 0, 0, 9]

**Comment by jbiscarri** [comment]
I'm sorry I pasted a log and this what server was returning... but now data received are what you can see in verbose log.
Framework was crashing in both cases with an inf loop in listen...
Thank you

**Comment by shogo4405** [comment]
@jbiscarri 
Can I access your server?

**Comment by shogo4405** [comment]
Go to email!
