### ISSUE TITLE
Crashes during streaming

### ISSUE THREAD

**Issue by Gamec** [shogo4405/lf.swift#210]
Hey, I'm running latest release (0.5.14). And during streaming I get those two crashes. It's pretty random, sometimes it works for a long time, sometimes it crashes all the time. I'm streaming using RTMP to Wowza server.

This is config I'm using:

        let sampleRate: Double = 44_100

        rtmpStream.syncOrientation = true
        rtmpStream.captureSettings = [
            "fps": 30, // FPS
            "sessionPreset": AVCaptureSessionPreset1280x720, // input video width/height
            "continuousAutofocus": true, // use camera autofocus mode
            "continuousExposure": true, //  use camera exposure mode
        ]
        rtmpStream.audioSettings = [
            "muted": false, // mute audio
            "bitrate": 32 * 1024,
            "sampleRate": sampleRate,
        ]
        rtmpStream.videoSettings = [
            "width": 1280, // video output width
            "height": 720, // video output height
            "bitrate": 4 * 1024 * 1024, // video output bitrate
            //"dataRateLimits": [1024 * 1024 / 8, 1], optional kVTCompressionPropertyKey_DataRateLimits property
            "profileLevel": kVTProfileLevel_H264_Baseline_3_1, // H264 Profile require "import VideoToolbox"
            "maxKeyFrameIntervalDuration": 2, // key frame / sec
        ]
        // "0" means the same of input
        rtmpStream.recorderSettings = [
            AVMediaTypeAudio: [
                AVFormatIDKey: Int(kAudioFormatMPEG4AAC),
                AVSampleRateKey: 0,
                AVNumberOfChannelsKey: 0,
                // AVEncoderBitRateKey: 128000,
            ],
            AVMediaTypeVideo: [
                AVVideoCodecKey: AVVideoCodecH264,
                AVVideoHeightKey: 0,
                AVVideoWidthKey: 0,
                /*
                 AVVideoCompressionPropertiesKey: [
                 AVVideoMaxKeyFrameIntervalDurationKey: 2,
                 AVVideoProfileLevelKey: AVVideoProfileLevelH264Baseline30,
                 AVVideoAverageBitRateKey: 512000
                 ]
                 */
            ],
        ]

![zrzut ekranu 2017-04-07 o 10 30 44](https://cloud.githubusercontent.com/assets/48938/24792219/634178de-1b7d-11e7-9c27-a8ff8030318e.png)
![zrzut ekranu 2017-04-07 o 10 31 03](https://cloud.githubusercontent.com/assets/48938/24792220/63473a12-1b7d-11e7-9f83-1e0136b05764.png)

**Comment by shogo4405** [comment]
How about this? Please set "profileLevel" to kVTProfileLevel_H264_Baseline_AutoLevel.
H264 don't support Baseline_3_1 for 1280x720 and 4Mbps. https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC

I can publish more than 1 hours.
```
        rtmpStream.videoSettings = [
            "width": 1280, // video output width
            "height": 720, // video output height
            "bitrate": 4 * 1024 * 1024, // video output bitrate
            //"dataRateLimits": [1024 * 1024 / 8, 1], optional kVTCompressionPropertyKey_DataRateLimits property
            "profileLevel": kVTProfileLevel_H264_Baseline_AutoLevel, // H264 Profile require "import VideoToolbox"
            "maxKeyFrameIntervalDuration": 2, // key frame / sec
        ]
```

**Comment by Gamec** [comment]
Oh, I didn't know that. However, using latest code (from yesterday) from master branch I no longer had those crashes. So I guess some of your changes fixed it.
