### ISSUE TITLE
[Xcode 8.3.x]Crashes during streaming

### ISSUE THREAD

**Issue by grizzly** [shogo4405/lf.swift#217]
App always crashes after a while at VideoIOComponent:

    func effect(_ buffer:CVImageBuffer) -> CIImage {
        var image:CIImage = CIImage(cvPixelBuffer: buffer)  <<--

malloc: *** error for object 0x17409c3dc: Invalid pointer dequeued from free list

**Comment by shogo4405** [comment]
Please write down your environment. XCode version, iOS version, framework version.
And how to reproduce.

Best regards.

**Comment by dekeract** [comment]
Hi! I'm also experiencing same crash. Tested on iphone 5s, 6, ios 10
Tested on framework versions 0.5.14 and 0.6.0
Xcode 8.3.1

> #11. Crashed: com.apple.coremedia.compressionsession.clientcallback
0  libsystem_kernel.dylib         0x184265014 __pthread_kill + 8
1  libsystem_pthread.dylib        0x18432f334 pthread_kill + 112
2  libsystem_c.dylib              0x1841d99c4 abort + 140
3  libsystem_malloc.dylib         0x1842aa9e8 nanozone_default_reader + 330
4  libsystem_malloc.dylib         0x1842abc54 _nano_malloc_check_clear + 412
5  libsystem_malloc.dylib         0x1842aac38 nano_malloc + 44
6  libsystem_malloc.dylib         0x184299664 malloc_zone_malloc + 172
7  libsystem_malloc.dylib         0x18429c56c malloc + 32
8  libswiftCore.dylib             0x102c1c048 swift_slowAlloc + 12
9  libswiftCore.dylib             0x102c1c09c _swift_allocObject_ + 28
10 libswiftFoundation.dylib       0x1030216a0 Data.init(bytes : UnsafeRawPointer, count : Int) -> Data + 72
11 lf                             0x1027238a0 _TFC2lf9RTMPMuxer12sampleOutputfT5videoCSo14CMSampleBuffer_T_ + 1916
12 lf                             0x102723ad8 _TTWC2lf9RTMPMuxerS_20VideoEncoderDelegateS_FS1_12sampleOutputfT5videoCSo14CMSampleBuffer_T_ + 52
13 lf                             0x1026aad50 _TFIvC2lf11H264EncoderP33_CDFEEBE6651AA2E305F0B49151E8836F8callbackcTGSqSv_GSqSv_Vs5Int32VSC17VTEncodeInfoFlagsGSqCSo14CMSampleBuffer__T_iU_FTGSqSv_GSqSv_S1_S2_GSqS3___T_ + 428
14 lf                             0x1026aadec _TToFIvC2lf11H264EncoderP33_CDFEEBE6651AA2E305F0B49151E8836F8callbackcTGSqSv_GSqSv_Vs5Int32VSC17VTEncodeInfoFlagsGSqCSo14CMSampleBuffer__T_iU_FTGSqSv_GSqSv_S1_S2_GSqS3___T_ + 72
15 VideoToolbox                   0x187e303c8 __vtcsr_dequeueAllPendingFramesAndCallbackClientForEach_block_invoke + 400
16 libdispatch.dylib              0x1841229e0 _dispatch_call_block_and_release
17 libdispatch.dylib              0x1841229a0 _dispatch_client_callout
18 libdispatch.dylib              0x184130830 _dispatch_queue_serial_drain
19 libdispatch.dylib              0x1841262cc _dispatch_queue_invoke
20 libdispatch.dylib              0x184132a50 _dispatch_root_queue_drain
21 libdispatch.dylib              0x1841327d0 _dispatch_worker_thread3
22 libsystem_pthread.dylib        0x18432b1d0 _pthread_wqthread + 1096
23 libsystem_pthread.dylib        0x18432ad7c start_wqthread + 4

**Comment by shogo4405** [comment]
Related issues is here. https://github.com/shogo4405/lf.swift/issues/210

**Comment by shogo4405** [comment]
Related issues is here. https://github.com/shogo4405/lf.swift/issues/218

**Comment by shogo4405** [comment]
Please try xcode 8.3.3 and master branch.
Then If you are still experincing this crash you update #231 issue.

**Comment by shogo4405** [comment]
And Try Optimization Level "Fastest, Smallest [-Os]"
