### ISSUE TITLE
Video Stream Player in Facebook Website doesnt Play

### ISSUE THREAD

**Issue by omarojo** [shogo4405/lf.swift#218]
I found that live streaming to facebook live works great, but after a few minutes of streaming. 
Users CANT see the live feed. except for OPERA (which uses flash player) and plays okay. 

This is very easy to reproduce... 

**How to reproduce**
1- get your urls and streamkey from Facebook
2- hardcode it into your app, and start a stream
3- post/publish the stream to your facebook timeline
4- Visualize the video feed in your Browser of choice (Chrome/Safari/Firefox)
5- wait a few minutes... keep streaming
6- Open a new browser window and go to your facebook timeline and try to play the LIVE video, at this point you will notice.. it WONT load, no matter what you do. But the first window where you are still visualizing your stream... is playing fine. If you close that player.. you wont be able to go back and see it again. 

This behaviour doesnt happen with other streaming libraies in facebook live. So Im assuming is the LF streaming lib. This is very sad.. because I cant do anything about it, dont know how to debug it 😩

**Comment by omarojo** [comment]
Im still investigating this issue, it seems the problem is related to my implementation.
Because Im using `rtmpStream.appendSampleBuffer(buffer, withType: .video);` maybe the timestamp in my sample buffer is wrong or something.

**Comment by shogo4405** [comment]
Close. Dupliate #217.

**Comment by omarojo** [comment]
Sorry, this is not a framework/library issue. Apparently It is the way I'm implementing the `rtmpStream.appendSampleBuffer(buffer, withType: .video)` Im doing something inefficiently. which I posted on #222 

Thanks again @shogo4405
