### ISSUE TITLE
broadcast camera feed to local network

### ISSUE THREAD

**Issue by parthjdabhi** [shogo4405/lf.swift#219]
I am trying to broadcast camera feed to the local network.

**Comment by shogo4405** [comment]
Thank u for new issue.
Do you need help with anything?

**Comment by parthjdabhi** [comment]
@shogo4405 Yes, i want to create broadcast camera feed and want to play that stream within the same network.
Can I use if.swift to achieve this?

**Comment by omarojo** [comment]
@parthjdabhi I suggest to read about how to make a rtmp server using NGINX-RTMP module. You run your server in your local area network, then configure LF library to stream to that rtmp url and key. And it should work.

**Comment by parthjdabhi** [comment]
@omarojo I search about setting up Local RTMP server into iOS app but Could find anything, It just shows me how to setup a Live web server.
If do you tink you could gather some link can you share it?

**Comment by shogo4405** [comment]
Framework has a HLS Streaming feature.

iOS(as a HTTPServer) -- localnework --> an iPhone(Safari) or Android(Chrome)
Sample code is here: https://github.com/shogo4405/lf.swift#http-usage

You can see a HLS Streaming demo. This is a macOS example. But works fine iOS.
https://github.com/shogo4405/lf.swift/tree/master/Examples/macOS
