### ISSUE TITLE
Ability to Not Delete .localRecord File From Documents After Recording

### ISSUE THREAD

**Issue by barger27** [shogo4405/lf.swift#220]
The `DefaultAVMixerRecorderDelegate` imports the video to the iOS photo gallery, and then deletes the original file out of documents. I need to be able to take the .mp4 file and back it up on my own servers. I tried subclassing the delegate and overriding `didFinishWriting`, but it's not an "open" method.

So... I'd like to either see a property to not delete the file (probably the easiest solution) or make it easier to subclass the default delegate. I'm certainly open to other ideas if I'm missing something. 

Xcode 8.2 / iOS 10 / Swift 3

**Comment by shogo4405** [comment]
I changed https://github.com/shogo4405/lf.swift/commit/5896f6af75fbf09897e26faf683ab806da817f6b#diff-96edd15de0f32e192458870e71b0db54. But not released yet.

I think better way. You copy and paste `DefaultAVMixerRecorderDelegate` to your project. Then customize AVMixerRecorderDelegate.

rtmpStream.mixer.recorder.delegate = YourAVMixerRecorderDelegate()

**Comment by barger27** [comment]
The default delegate makes calls on the recorder that are marked internal... namely in the rotateFile:  `recorder.finishWriting()` and `recorder.sourceTime = withPresentationTimeStamp`.

But this may get me by for a while. The rotate file would be handy in my case, but there's other ways to accomplish that.

Thanks!
