### ISSUE TITLE
[Xcode 8.3.x]Another Streaming Crash

### ISSUE THREAD

**Issue by jrahaim** [shogo4405/lf.swift#223]
```    
open override func draw(_ rect: CGRect) {
        glClear(GLbitfield(GL_COLOR_BUFFER_BIT))
        guard let displayImage:CIImage = displayImage else {
            return
        }
        var inRect:CGRect = CGRect(x: 0, y: 0, width: CGFloat(drawableWidth), height: CGFloat(drawableHeight))
        var fromRect:CGRect = displayImage.extent
        VideoGravityUtil.calclute(videoGravity, inRect: &inRect, fromRect: &fromRect)
        if (position == .front) {
            ciContext.draw(displayImage.applyingOrientation(2), in: inRect, from: fromRect)
        } else {
>>>            ciContext.draw(displayImage, in: inRect, from: fromRect)
        }
    }
```

`iOS 10.3.1`
`iPhone 7+`
`Xcode 8.3,2`
`Using glm (0.9.7.1)`
`Using lf (0.6.0)`
Streaming to youtube

With an image overlay.
Video(1787,0x1abd49b40) malloc: *** error for object 0x1700933cc: Invalid pointer dequeued from free list

**Comment by macness-pavelh** [comment]
Happened to me too... slightly suspect it was related to device orientation change.

**Comment by DLNlab** [comment]
This crash always occurs in RTMP in the example iOS application, I see that by commenting ciContext.draw(displayImage, in: inRect, from: fromRect) the error disappears, (and the image too). I don't know if its a bug from the new Xcode. Any idea?

**Comment by dekeract** [comment]
Hi! Seems like this crashes happen only on Xcode 8.3+.
I downgraded xcode to 8.2, and broadcasting is always stable
I will try to investigate issue farther

**Comment by macness-pavelh** [comment]
Possibly this might be a race condition related to `displayImage` here https://github.com/shogo4405/lf.swift/blob/master/Platforms/iOS/GLLFView.swift#L77

`draw(_ rect: CGRect)` is called on MT but `draw(image: CIImage)` is not.

I modified the later function as bellow now waiting if I see the crash again. So far so  #good.

```
func draw(image:CIImage) {
        //displayImage = image
        DispatchQueue.main.async {
            self.displayImage = image
            self.setNeedsDisplay()
        }
}
```

**Comment by shogo4405** [comment]
Please try xcode 8.3.3 and master branch.
Then If you are still experincing this crash you update #231 issue.

**Comment by shogo4405** [comment]
And Try Optimization Level "Fastest, Smallest [-Os]"

**Comment by jrahaim** [comment]
@macness-pavelh Did your changes above fix the issue?

**Comment by macness-pavelh** [comment]
@jrahaim hard to tell... I was testing just for a short period of time, then I was doing something else. In that short time it did not happen though I'd like to give it more time. I should know in a couple of days.
