### ISSUE TITLE
Custom screen capture question

### ISSUE THREAD

**Issue by tkikala** [shogo4405/lf.swift#224]
Hi,
I am using this library to stream some part of screen to youtube. When I modify ScreenCaptureSession init method to pass a view to it to change bounds of capturing it works perfectly.
The problem is that I didn't find any other way except modifying library class to fulfil my goal. ScreenCaptureSession is final and also VideoIOComponent is final so I cannot override function .attachScreen as well to take other class as parameter. Could you suggest anything that I can do?

**Comment by shogo4405** [comment]
> Could you suggest anything that I can do?

Currentry, no way :( I'm waiting your PR.

**Comment by shogo4405** [comment]
#225 merged
