### ISSUE TITLE
rtmpt? any plans?

### ISSUE THREAD

**Issue by zhuker** [shogo4405/lf.swift#228]

**Comment by shogo4405** [comment]
What's do you mean?

**Comment by zhuker** [comment]
sorry for not explaining properly

i mean you say `RTMPT (Technical Preview)` in the README.md and there's some code in the repo
but no example how to stream via rtmpt

**Comment by shogo4405** [comment]
Please try this.
rtmpConnection.connect("**rtmpt**://hostname/appName/instanceName")

**Comment by zhuker** [comment]
That easy? Nice!
