### ISSUE TITLE
[Xcode 8.3.x]Crash Invalid pointer dequeued from free list (RTMPChunk)

### ISSUE THREAD

**Issue by omarojo** [shogo4405/lf.swift#229]
Im getting consistent crashes right here: 
`malloc: *** error for object 0x17409904c: Invalid pointer dequeued from free list
*** set a breakpoint in malloc_error_break to debug`

![image](https://cloud.githubusercontent.com/assets/995265/26413470/f6d1fe36-4060-11e7-9de5-eed938cf0f83.png)

**Comment by shogo4405** [comment]
Please try xcode 8.3.3 and master branch.
Then If you are still experincing this crash you update #231 issue.

**Comment by shogo4405** [comment]
And Try Optimization Level "Fastest, Smallest [-Os]"
