### ISSUE TITLE
[Xcode 8.3.x]crashes in NetSocket.deinitConnection()

### ISSUE THREAD

**Issue by mwawrusch** [shogo4405/lf.swift#230]
The app crashes 90% of the time when trying to destroy an unallocated buffer:

 malloc: *** error for object 0x10bf5c000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

This happens here: https://github.com/shogo4405/lf.swift/blob/master/Sources/Net/NetSocket.swift#L156

Any ideas?

**Comment by shogo4405** [comment]
Please try xcode 8.3.3. Then If you are still experincing this crash you update #231 issue.
