### ISSUE TITLE
[Xcode 8.3.x] "Invalid pointer dequeued from free list" after updating to iOS 10.3/Xcode 8.3

### ISSUE THREAD

**Issue by shogo4405** [shogo4405/lf.swift#231]
## Link
* https://forums.developer.apple.com/thread/74884

## Temporary solution
* Update XCode 8.3.3
* Change Optimization Level
  - Fastest, Smallest [-Os]

## Related issues
  - #210 
  - #217
  - #221
  - #223 
  - #230 ?

**Comment by shogo4405** [comment]
Optimization Level
* None → occured
* Fast → occured
* Fastest, Smallest → No experience. I can publish over 5 hours many times.

**Comment by dmitryond** [comment]
At some point I was wondering this could be related to crashed I described in #248 , but since changing Optimization Level didn't fix the issue, I've dismissed that idea, maybe mistakenly.

**Comment by shogo4405** [comment]
After, these commits. I get the feeling that fall in crash rate. 

1b9b99a
197dc37
28ffd72

**Comment by shogo4405** [comment]
umm....

Example iOS(571,0x1b3650b40) malloc: *** error for object 0x17009ac6c: Invalid pointer dequeued from free list
*** set a breakpoint in malloc_error_break to debug

GLLFView.swift with malloc "invalid pointer dequeued from free list" error.

**Comment by shogo4405** [comment]
It took more time than I'd expected.
I fixed it! https://github.com/shogo4405/lf.swift/commit/9e8dde72bec8a7f65104c8b9a31d3bb0d8ff3a70

**Comment by Noiled** [comment]
@shogo4405  what cause this strange crash stack
