### ISSUE TITLE
my project suddenly stop working and getting error "SWIFT_UNAVAILABLE"

### ISSUE THREAD

**Issue by BharatAgarSoftTech** [shogo4405/lf.swift#236]
the project was working fine, after removing derived data and perform "carthage build --platform iOS"
now it's showing below error 

1.
![screen shot 2017-06-05 at 8 31 17 pm](https://cloud.githubusercontent.com/assets/18732229/26789609/77cb501a-4a2e-11e7-8b92-78f1217df167.png)

2.
![screen shot 2017-06-05 at 8 32 01 pm](https://cloud.githubusercontent.com/assets/18732229/26789611/781b309e-4a2e-11e7-9b71-31160fff14e9.png)

Thanks.

**Comment by shogo4405** [comment]
It seemes Objective-C project. I stopped supporting Objective-C project :(

**Comment by BharatAgarSoftTech** [comment]
@shogo4405  so now lf.swift not going to work on  Objective-C? can you please tell me which tag going to work for objective c?

**Comment by shogo4405** [comment]
Please try 0.5.12 or 0.5.11.
I'm considering to revert a commit...

**Comment by BharatAgarSoftTech** [comment]
@shogo4405 i already try that tags and its also showing same error, if you didn't revert any commit then can you please do that for me because now i am familiar with lf.swift and its working perfectly.

Thanks.

**Comment by BharatAgarSoftTech** [comment]
@shogo4405  any update?

**Comment by pvinis** [comment]
@BharatAgarSoftTech how about you try to bisect and find the last commit that works? then also you can figure out which commit could be reverted. and then give a pr?

**Comment by shogo4405** [comment]
I reverted. But I will be able to release 7.1 after a few weeks
Please consider use old version. And I have looked into the tag 0.5.12 again.
That is contains support for Objective-C code.
