### ISSUE TITLE
QUESTION: adaptive bitrate for RTMP

### ISSUE THREAD

**Issue by macness-pavelh** [shogo4405/lf.swift#238]
Hi,

I'm testing RTMP streaming with bitrate set to 2_000_000 - I limit iphone upstream bitrate to 1mbps using the network conditioner. It seems that frames are dropped, but the bitrate does not (just an impression). The readme says that adaptive bitrate is supported. 

a) how can I check what is really happening
b) is there a way I could influence what policy is applied when upstream is choked?

    rtmpStream.videoSettings = [
            "width": 1280,
            "height": 720,

            "bitrate" : 2_00_000,
            "scalingMode" : kVTScalingMode_Letterbox,
        ]`

**Comment by shogo4405** [comment]
You have to write handling code.
Please see this issue. https://github.com/shogo4405/lf.swift/issues/126
