### ISSUE TITLE
RTMP connection error

### ISSUE THREAD

**Issue by gonghao** [shogo4405/lf.swift#24]
Hi, 

I've tried to make the connection to `rtmp://pili-live-rtmp.skyplatanus.com/skyplatanus/56daaad95e77b0351602c712`. But it always fails. I've try to make some modification to the code, but I found there are a lot of compatibilities to do for dealing with various RTMP servers now. 

for examples, I've met a problem like this [link](https://forums.adobe.com/thread/27034?start=0&tstart=0)

So I think it's hared to make a RTMP client without `librtmp` unless make lots of tests for it.

**Comment by shogo4405** [comment]
I can't access pili-live-rtmp.skyplatanus.com. (ip block? from Japan)
Do you know server software(FMS, Wowza, Red5)?

**Comment by shogo4405** [comment]
@gonghao I fixed it! current master branch works fine.

**Comment by gonghao** [comment]
@shogo4405 It's so great!!!! Thanks!!
