### ISSUE TITLE
Streaming quality issues

### ISSUE THREAD

**Issue by ballmw** [shogo4405/lf.swift#246]
Hello, We're working on a new product using lf.swift that streams and records simultaneously.

Our recordings are very nice, high quality but the stream is not.

We're looking for help with this and can provide any information as far as configuration, code etc.

We'd also be willing to pay someone for their consulting time as this is an urgent matter.

Thanks!

**Comment by shogo4405** [comment]
Please see the Settings Section. https://github.com/shogo4405/lf.swift/blob/master/README.md#settings

Try change "bitrate" properties.
Best regards.

**Comment by ballmw** [comment]
What is the default bitrate?

**Comment by shogo4405** [comment]
Video -> 160 * 1024 = 160kbps
Audio -> 32 * 1024 = 32kbps
