### ISSUE TITLE
HLS not working

### ISSUE THREAD

**Issue by sohymg** [shogo4405/lf.swift#247]
I followed your code snippet for HLS. The view shows up on my phone but when I enter the URL in my browser, it just downloads the m3u8 file. How do I view the stream?

Thank you in advance.

**Comment by shogo4405** [comment]
If you are using a Chrome(macOS).
Please use Safari(macOS) or chrome(iPhone(

**Comment by sohymg** [comment]
Thanks for the prompt response. I can see it on Safari now but there is a delay of 4 seconds. The phone and the mac are on the same local network. Is there any way to speed things up?

**Comment by shogo4405** [comment]
No way. It's  specifications of HLS.
