### ISSUE TITLE
Crash after streaming for a while

### ISSUE THREAD

**Issue by sohymg** [shogo4405/lf.swift#248]
Hi,

I ran the Example iOS and after turning on the streaming for awhile (no connected client yet), the app will crash with:

`Example iOS(4515,0x16de93000) malloc: *** error for object 0x10c538000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug`

The error line is on the last line of 'NetSocket.swift'

```
    func deinitConnection(isDisconnected:Bool) {
        inputStream?.close()
        inputStream?.remove(from: runloop!, forMode: .defaultRunLoopMode)
        inputStream?.delegate = nil
        inputStream = nil
        outputStream?.close()
        outputStream?.remove(from: runloop!, forMode: .defaultRunLoopMode)
        outputStream?.delegate = nil
        outputStream = nil
        buffer?.deallocate(capacity: windowSizeC) <---- this line
    }
```

**Comment by RomanIvaniv** [comment]
Hi. I have same problem, even more, I can't start streaming to remote rtmp url from example ios. Can you stream to remote url?

**Comment by shogo4405** [comment]
Please tell me your XCode and device name.
I can't reproduce.

**Comment by sohymg** [comment]
Xcode Version 8.3.3 (8E3004b)
Device Iphone 7 plus

**Comment by sohymg** [comment]
> Hi. I have same problem, even more, I can't start streaming to remote rtmp url from example ios. Can you stream to remote url?

I couldn't find a working rtmp player for macOS

**Comment by Gamec** [comment]
Just happened to me. Xcode 8.3.3, iPhone 7, iOS 10.3.2

`malloc: *** error for object 0x105a48000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug`

on line `super.deinitConnection(isDisconnected: isDisconnected)` in RTMPSocket

That one is very rare. I'm streaming for days, it was first time.

**Comment by dmitryond** [comment]
I'm having the same issue, it seems, for the last week, collecting data.

So far crash only happens on my iPhone 6s Plus with iOS 10.3.2.
Crash does not happen on simulators (including iPhone 6s Plus with 10.3.2).
Crash does not happen on my iPhone 6 Plus with iOS 9.3.4.

Crash happens randomly, sometimes withing minutes after starting the stream, sometimes a couple of hours.
Crashes happen in: line 54 of GLLFView.swift (6 crashes)
line 70 of RTMPMessage.swift (1 crash)
line 29 of RTMPChunk.swift (1 crash)
line 292 of VideoIOComponent.swift (1 crash)

**Comment by macness-pavelh** [comment]
possibly realted to #252

**Comment by dmitryond** [comment]
After this commit I only had one crash on line 54 of GLLFView.swift with malloc "invalid pointer dequeued from free list" error during approx 7 hours of streaming.
