### ISSUE TITLE
append CVPixelBuffer to RTMPStream

### ISSUE THREAD

**Issue by tkikala** [shogo4405/lf.swift#250]
Hi,
I'm provided with CVPixelbuffer which I need to display on View and Stream to youtube as well. My solution works with screencapture, but when I want to use rtmpStream.appendSampleBuffer(sampleBuffer, withType: CMSampleBufferType.video) where sampleBuffer is CVPixelBuffer converted to CMSampleBuffer, on youtube it is written LIVE but nothing is shown and spinner is loading.

Here is how I convert CVPixelBuffer to CMSampleBuffer:
```
var sampleBuffer: CMSampleBuffer?  = nil
        var sampleTimingInfo: CMSampleTimingInfo = kCMTimingInfoInvalid
        var formatDesc: CMVideoFormatDescription? = nil
        _ = CMVideoFormatDescriptionCreateForImageBuffer(kCFAllocatorDefault, pixelBuffer, &formatDesc)
        
        if let formatDesc = formatDesc {
            CMSampleBufferCreateReadyWithImageBuffer(kCFAllocatorDefault, pixelBuffer, formatDesc, &sampleTimingInfo, &sampleBuffer)
        }
        
        if let sampleBuffer = sampleBuffer {
            self.rtmpStream.appendSampleBuffer(sampleBuffer, withType: CMSampleBufferType.video)
        }
```
Any ideas how to make it to work?
Thanks beforehand

**Comment by shogo4405** [comment]
This line is problem.
var sampleTimingInfo: CMSampleTimingInfo = kCMTimingInfoInvalid

RTMP needs a timestamp delta.
Internally,  Timestamp delta is "previous sampleTimingInfo.presentationTimestamp - next sampleTimingInfo.presentationTimestamp"

Please, make a valid value!

**Comment by tkikala** [comment]
@shogo4405 Thank you, 
        let doubleForSeconds: Double = 1 / 30 this means (1 / framerate)
        sampleTimingInfo.duration = CMTime(seconds: doubleForSeconds, preferredTimescale: 1000000)
        sampleTimingInfo.presentationTimeStamp = presentationTime
        sampleTimingInfo.decodeTimeStamp = kCMTimeInvalid

and it is working for some 5-6 seconds and then stops streaming.
presentationTime is:
let presentationTime = CMTime(value: frame.timestamp, timescale: 1000000)

and frame is what I am provided with.
