### ISSUE TITLE
Multistreaming ability

### ISSUE THREAD

**Issue by RomanIvaniv** [shogo4405/lf.swift#251]
Hi. What is the best way to implement multi streaming ability? Just create few instance of RTMPConnection and RTMPStream or just one instance with few sockets, AVMixer, etc?

**Comment by shogo4405** [comment]
What do you want to do?
Could you be more specific.

**Comment by RomanIvaniv** [comment]
I want to stream live video on Facebook and YouTube at the same time.

**Comment by shogo4405** [comment]
Just create few instance of RTMPConnection and RTMPStream.
