### ISSUE TITLE
NetSocket - double deallocate

### ISSUE THREAD

**Issue by macness-pavelh** [shogo4405/lf.swift#252]
in NetSocket the `buffer` is allocated in `initConnection` and deallocated in `deinitConnection`.

In my setup it happened that `case Stream.Event.errorOccurred` is caught in stream delegate, what inherently invokes `deinitConnection`, but the same happens a bit later from the timeoutHandler and the app crashes.

It appears that either

- `deinitConnection` should be made reentrant (and thread safe)
- on `Stream.Event.errorOccurred` the timeout handler should be removed (thread safe again)

... just ideas, not sure what is better.

**Comment by macness-pavelh** [comment]
possibly related to #248

**Comment by shogo4405** [comment]
https://github.com/shogo4405/lf.swift/commit/197dc37336631049a17b59b6f5b18eeddb816dcd
