### ISSUE TITLE
Can't stream for two rtmp url at same time.

### ISSUE THREAD

**Issue by RomanIvaniv** [shogo4405/lf.swift#253]

**Comment by RomanIvaniv** [comment]
Hi. I'm trying to stream on Facebook and youtube at same time. I created two instance of RTMPConnection and RTMPStream. But when I try to call  "publish"  method on both rtmpStream instance its work only for one (for latest one, that was called)

**Comment by RomanIvaniv** [comment]
BTW: When I start stream only in Facebook(or youtube), its start start stream, but just after I call "publish" for next service, previous just stop streaming, and work only new one

**Comment by shogo4405** [comment]
Are you using RTMPStream.attach(Camera|Audio) method?
Probably, iOS can't use two Front/Back Camera AVCaptureDevice instance.

**Comment by RomanIvaniv** [comment]
Thanks for your help. I tried to do as you say, but its still stream only to one service.

class MultiStream : NSObject {
    
    var fbRtmpConnection:RTMPConnection = RTMPConnection()
    var fbRtmpStream:RTMPStream?

    var ytRtmpConnection:RTMPConnection = RTMPConnection()
    var ytRtmpStream:RTMPStream?
    
    func settings (view: UIView) {
        
        
        fbRtmpStream = RTMPStream(connection: fbRtmpConnection)
        
        fbRtmpStream?.attachAudio(AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeAudio)) { error in
            AlertManager.showLightAlert(title: "Error", message: "Change attach audio")
            print(error)
        }
        fbRtmpStream?.attachCamera(DeviceUtil.device(withPosition: .back)) { error in
            AlertManager.showLightAlert(title: "Error", message: "Change attach video")
            print(error)
        }
//
        //insert all setting in init
        fbRtmpStream?.captureSettings = [
            "fps": 30, // FPS
            "sessionPreset": AVCaptureSessionPresetHigh,
            "continuousAutofocus": true,
            "continuousExposure": true,
        ]
        
        fbRtmpStream?.audioSettings = [
            "muted": false,
            "bitrate": 100 * 1024,
            "sampleRate": sampleRate,
        ]
        
        fbRtmpStream?.videoSettings = [
            "width": 640,
            "height": 1136,
            "bitrate": 1200 * 1000,
            "profileLevel": kVTProfileLevel_H264_Baseline_AutoLevel,
            "maxKeyFrameIntervalDuration": 2,
        ]
        
        fbRtmpStream?.syncOrientation = true
//
        
        
        ytRtmpStream = RTMPStream(connection: ytRtmpConnection)
        ytRtmpStream?.attachAudio(AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeAudio)) { error in
            AlertManager.showLightAlert(title: "Error", message: "Cnage attach audio")
            print(error)
        }
        ytRtmpStream?.attachCamera(DeviceUtil.device(withPosition: .back)) { error in
            AlertManager.showLightAlert(title: "Error", message: "Cnage attach video")
            print(error)
        }
        
        //insert all setting in init
        ytRtmpStream?.captureSettings = [
            "fps": 30, // FPS
            "sessionPreset": AVCaptureSessionPresetHigh,
            "continuousAutofocus": true,
            "continuousExposure": true,
        ]
        
        ytRtmpStream?.audioSettings = [
            "muted": false,
            "bitrate": 100 * 1024,
            "sampleRate": sampleRate,
        ]
        
        ytRtmpStream?.videoSettings = [
            "width": 640,
            "height": 1136,
            "bitrate": 1200 * 1000,
            "profileLevel": kVTProfileLevel_H264_Baseline_AutoLevel,
            "maxKeyFrameIntervalDuration": 2,
        ]
        
        ytRtmpStream?.syncOrientation = true
//
        let view:LFView = view as! LFView
        
        view.videoGravity = AVLayerVideoGravityResizeAspectFill
        view.attachStream(fbRtmpStream)
        view.attachStream(ytRtmpStream)
    }
    
    
    func publish() {
        fbRtmpStream?.publish("my fb key")
        ytRtmpStream?.publish("my yt key")
    }
    
    func connect() {
        fbRtmpConnection.connect("rtmp://rtmp-api.facebook.com:80/rtmp/")
        ytRtmpConnection.connect("rtmp://a.rtmp.youtube.com/live2")
    }
    
    func close() {
        fbRtmpConnection.close()
        ytRtmpConnection.close()
    }
}

//THIS METHOD NOT EVEN CALL
extension MultiStream: AVCaptureVideoDataOutputSampleBufferDelegate {
    // MARK: AVCaptureVideoDataOutputSampleBufferDelegate
    func captureOutput(_ captureOutput:AVCaptureOutput!, didOutputSampleBuffer sampleBuffer:CMSampleBuffer!, from connection:AVCaptureConnection!) {
        fbRtmpStream?.appendSampleBuffer(sampleBuffer, withType: .video)
        ytRtmpStream?.appendSampleBuffer(sampleBuffer, withType: .video)
    }
}

**Comment by RomanIvaniv** [comment]
Thanks for your help. I tried to do as you say, but its still stream only to one service.
I need to attach audio/video for both RTMPStream? And which one should be attached to LFView?

**Comment by RomanIvaniv** [comment]
class MultiStream : NSObject {
    
    var fbRtmpConnection:RTMPConnection = RTMPConnection()
    var fbRtmpStream:RTMPStream?
    var ytRtmpConnection:RTMPConnection = RTMPConnection()
    var ytRtmpStream:RTMPStream?

    func settings (view: UIView) {
        fbRtmpStream = RTMPStream(connection: fbRtmpConnection)
        fbRtmpStream?.attachAudio(AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeAudio)) { error in
            AlertManager.showLightAlert(title: "Error", message: "Change attach audio")
            print(error)
        }
        fbRtmpStream?.attachCamera(DeviceUtil.device(withPosition: .back)) { error in
            AlertManager.showLightAlert(title: "Error", message: "Change attach video")
            print(error)
        }
//
        //insert all setting in init
        fbRtmpStream?.captureSettings = [
            "fps": 30, // FPS
            "sessionPreset": AVCaptureSessionPresetHigh,
            "continuousAutofocus": true,
            "continuousExposure": true,
        ]
        fbRtmpStream?.audioSettings = [
            "muted": false,
            "bitrate": 100 * 1024,
            "sampleRate": sampleRate,
        ]
        fbRtmpStream?.videoSettings = [
            "width": 640,
            "height": 1136,
            "bitrate": 1200 * 1000,
            "profileLevel": kVTProfileLevel_H264_Baseline_AutoLevel,
            "maxKeyFrameIntervalDuration": 2,
        ]
        fbRtmpStream?.syncOrientation = true
        ytRtmpStream = RTMPStream(connection: ytRtmpConnection)
        ytRtmpStream?.attachAudio(AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeAudio)) { error in
            AlertManager.showLightAlert(title: "Error", message: "Cnage attach audio")
            print(error)
        }
        ytRtmpStream?.attachCamera(DeviceUtil.device(withPosition: .back)) { error in
            AlertManager.showLightAlert(title: "Error", message: "Cnage attach video")
            print(error)
        }
        ytRtmpStream?.captureSettings = [
            "fps": 30, // FPS
            "sessionPreset": AVCaptureSessionPresetHigh,
            "continuousAutofocus": true,
            "continuousExposure": true,
        ]
        
        ytRtmpStream?.audioSettings = [
            "muted": false,
            "bitrate": 100 * 1024,
            "sampleRate": sampleRate,
        ]
        
        ytRtmpStream?.videoSettings = [
            "width": 640,
            "height": 1136,
            "bitrate": 1200 * 1000,
            "profileLevel": kVTProfileLevel_H264_Baseline_AutoLevel,
            "maxKeyFrameIntervalDuration": 2,
        ]        
        ytRtmpStream?.syncOrientation = true
        let view:LFView = view as! LFView
        
        view.videoGravity = AVLayerVideoGravityResizeAspectFill
        view.attachStream(fbRtmpStream)
        view.attachStream(ytRtmpStream)
    }

    func publish() {
        fbRtmpStream?.publish("my key")
        ytRtmpStream?.publish("my key")
    }
    func connect() {
        fbRtmpConnection.connect("rtmp://rtmp-api.facebook.com:80/rtmp/")
        ytRtmpConnection.connect("rtmp://a.rtmp.youtube.com/live2")
    }
    
    func close() {
        fbRtmpConnection.close()
        ytRtmpConnection.close()
    }
}
//THIS METHOD NOT EVEN CALL
extension MultiStream: AVCaptureVideoDataOutputSampleBufferDelegate {
    // MARK: AVCaptureVideoDataOutputSampleBufferDelegate
    func captureOutput(_ captureOutput:AVCaptureOutput!, didOutputSampleBuffer sampleBuffer:CMSampleBuffer!, from connection:AVCaptureConnection!) {
        fbRtmpStream?.appendSampleBuffer(sampleBuffer, withType: .video)
        ytRtmpStream?.appendSampleBuffer(sampleBuffer, withType: .video)
    }
}

**Comment by RomanIvaniv** [comment]
And inside my controller i have a instance of MultiStream class. Where the problem is?

```
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        self.multiStream.settings(view: self.view)

        
        let captureSession = AVCaptureSession()
        
        let videoDevice = AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeVideo)
        let videoInput = try! AVCaptureDeviceInput.init(device: videoDevice)
        captureSession.addInput(videoInput)
        
        let videoDataOutput = AVCaptureVideoDataOutput()
        captureSession.addOutput(videoDataOutput)
        videoDataOutput.setSampleBufferDelegate(multiStream, queue: DispatchQueue.main)

    }
```

**Comment by shogo4405** [comment]
In this case, You can't use attach(Camra/Audio).  Please use appendSampleBuffer.
AVCaptureVideoDataOutputSampleBufferDelegate and AVCaptureAudioDataOutputSampleBufferDelegate
are basic for AVFoundation. google it.

**Comment by aarti1khajuria** [comment]
> In this case, You can't use attach(Camra/Audio). Please use appendSampleBuffer.
> AVCaptureVideoDataOutputSampleBufferDelegate and AVCaptureAudioDataOutputSampleBufferDelegate
> are basic for AVFoundation. google it.

I have used it. But still it is not working

**Comment by fyistream** [comment]
@aarti1khajuria any luck ?
