### ISSUE TITLE
Using ReplayKit SampleBuffer idle stream auto-disconnects 

### ISSUE THREAD

**Issue by dmitryond** [shogo4405/lf.swift#255]
ReplayKit Sample Buffer to RTMP implementation has a definite performance advantage, but I encountered a problem.

Stream doesn't show anything on the viewer side until something changes on the screen. It means, that while buffer is same as previous one, no updates are sent to server. Furthermore, after being idle for 10-20 seconds the stream disconnects.

It seems like ReplayKit SampleBuffer doesn't send updates if the picture is the same as before.

To test, implement streaming using SampleBuffer of ReplayKit, do not include camera, only a webpage or something. Connect a stream, a viewer and see it's showing black screen until webpage is scrolled or something. If you launch a stopwatch, for example, stream will run, but 10-20 seconds after you stop the stopwatch and screen is idle, RTMPConnection suddenly calls on function with status connectClosed.

**Comment by shogo4405** [comment]
Talking about ReplayKit with iOS10 or iOS11?

> It seems like ReplayKit SampleBuffer doesn't send updates if the picture is the same as before.
I think that your rtmp-client works out countermeasures. For example, send a last SampleBuffer by timer at fixed intervals.

**Comment by dmitryond** [comment]
I am running iOS 10 on that device and the project created with ReplayKit.

I don't know what countermeasures are you mentioning, but the stream disconnects on the server side. The other RTMP streams, that are not using SampleBuffer and ReplayKit, are working just fine, people stream for hours.

If you mean the client side of the streamer, then please explain me about these countermeasures if you can, I have failed finding info on those on the internet. And more importantly, how to stop this behaviour if possible. I mean, it's the same streamer, just redirected to use ReplayKit Sample buffer and to start stream at RTMPBroadcaster's init.

**Comment by shogo4405** [comment]
> how to stop this behaviour

What’s “THIS” behavior?

1. It seems like ReplayKit SampleBuffer doesn't send updates if the picture is the same as before.
    * We can’t change this behavior. 
2. the stream disconnects on the server side.
    * Please ask the server side administrator.

**Comment by dmitryond** [comment]
I see. So this behaviour can't be changed and ReplayKit works with buffers in a different way than the traditional LF.

By disconnect on the server side I meant disconnect is sent from streamer. Bad wording.

So, what can be done, is it's possible to add a LIVE indicator, that flashes while stream is live to ensure ReplayKit constantly sends updated buffer. Does this workaround make sense?

**Comment by shogo4405** [comment]
framework has no feature auto-disconnect.

If I were you, I deal with this problem.
1. Detection no SampleBuffer a while (a second) by RTMPStream
1. RTMPStream detects it. Then stream sends last SampleBuffer at fixed intervals.

framwork has no "Then stream sends last SampleBuffer at fixed intervals" feature. Please customize RTMPStream
