### ISSUE TITLE
RTMPTSocket reconnect?

### ISSUE THREAD

**Issue by zhuker** [shogo4405/lf.swift#256]
server i am sending my rtmpt requests to (nginx) has a request count limit after limit is exceeded http keep-alive connection is being dropped. lf.swift treats it as connection was closed and stops streaming. 
can you point me to the best place to look into it?
@shogo4405

**Comment by geeee** [comment]
Retrying failed request helps: https://github.com/shogo4405/lf.swift/pull/258
Not sure if it's the best solution though

**Comment by shogo4405** [comment]
How can I test it? I prepare nginx-rtmp-module(https://github.com/arut/nginx-rtmp-module)?

**Comment by geeee** [comment]
@shogo4405 should be reproducible with the max requests param enabled. We are using default value for `http2_max_requests 1000;`
