### ISSUE TITLE
Does GPUHaishinKit compatible with BradLarson/GPUImage2?

### ISSUE THREAD

**Issue by huynhphan89** [shogo4405/lf.swift#263]
BradLarson/GPUImage isn't maintained anymore, so I plan to migrate to BradLarson/GPUImage2.

Is it possible ?

**Comment by shogo4405** [comment]
No. I focused BradLarson/GPUImage.
GPUHaishinKit2 project is here. https://github.com/shogo4405/GPUHaishinKit2.swift
But, project is under suspension. Because GPUImage2 is not released. And I'm not familiar with GPUImage2.
