### ISSUE TITLE
Dropping application (live/_definst_) message. Clients not allowed to broadcast message.

### ISSUE THREAD

**Issue by shogo4405** [shogo4405/lf.swift#27]
* AdobeMediaServer5

**Comment by flashape** [comment]
Any updates on this?  We're hitting the same issue.  It seems like we can connect to an fms app just fine, then after a few seconds we get this error.

**Comment by shogo4405** [comment]
@flashape
no update.

**Comment by shogo4405** [comment]
@flashape 
I fixed this issue. Current master works fine!

**Comment by flashape** [comment]
Awesome, thanks!
