### ISSUE TITLE
How to switch between front and back facing cameras?

### ISSUE THREAD

**Issue by mrbemani** [shogo4405/lf.swift#3]
How to switch between front and back facing cameras?

**Comment by MingLoan** [comment]
func toggleCamera(sender:UIBarButtonItem) {
        let position:AVCaptureDevicePosition = currentPosition == .Back ? .Front : .Back
        rtmpStream.attachCamera(AVCaptureSessionManager.deviceWithPosition(position))
        currentPosition = position
    }

which has been already in the example project.

**Comment by mrbemani** [comment]
sorry, I figured that out later. please close this issue.

**Comment by shogo4405** [comment]
Sorry for late...X)
