### ISSUE TITLE
suggestion for HTTPStream

### ISSUE THREAD

**Issue by pzs7602** [shogo4405/lf.swift#34]
HTTPStream should have a attachAudio method for adding audio capture, that will be perfect for an IP camera.
I also add some useful methods for HTTPStream class in my project:

    public var audioSettings:[String: AnyObject] {
        get { return mixer.audioIO.encoder.dictionaryWithValuesForKeys(AACEncoder.supportedSettingsKeys)}
        set { mixer.audioIO.encoder.setValuesForKeysWithDictionary(newValue) }
    }
    
    public var videoSettings:[String: AnyObject] {
        get { return mixer.videoIO.encoder.dictionaryWithValuesForKeys(AVCEncoder.supportedSettingsKeys)}
        set { mixer.videoIO.encoder.setValuesForKeysWithDictionary(newValue)}
    }
    
    public var captureSettings:[String: AnyObject] {
        get { return mixer.dictionaryWithValuesForKeys(AVMixer.supportedSettingsKeys)}
        set { dispatch_async(lockQueue) { self.mixer.setValuesForKeysWithDictionary(newValue)}}
    }

**Comment by shogo4405** [comment]
Thanks suggestion.
I will.
