### ISSUE TITLE
HTTPStream corruption

### ISSUE THREAD

**Issue by pzs7602** [shogo4405/lf.swift#37]
I'm using lf.framework(downloaded on 10 May) to live broadcast a HTTPStream, at first my app runs OK and I can get the stream from http://ip.address:8080/hls/playlist.m3u8 ,while broadcasting several minutes, the app corrupted and stopped in the following statement within writeSampleBuffer method(TSWriter.swift):
            currentFileHandle?.writeData(NSData(bytes: packet.bytes))

console message:
*** Terminating app due to uncaught exception 'NSFileHandleOperationException', reason: '*** -[NSConcreteFileHandle writeData:]: Resource temporarily unavailable'
*** First throw call stack:
(0x1814a2e38 0x180b07f80 0x1814a2d80 0x181e290dc 0x181e299cc 0x10017f324 0x100183550 0x1001835d8 0x1001bc0dc 0x1001bc508 0x10020a830 0x10020a8d0 0x187bb7408 0x187bb72cc 0x1838604a4 0x18387c188 0x100b5da3c 0x100b75de0 0x100b5ffe0 0x100b6a770 0x100b6172c 0x100b6a770 0x100b6172c 0x100b6c66c 0x100b6c364 0x181105470 0x181105020)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by shogo4405** [comment]
@shogo4405
[fg169,169,169;[bg;2016-05-14 15:14:59.222 [Debug] [VideoIOComponent.swift:38] VideoIOComponent > cicontext use hardware renderer[;
2016-05-14 16:19:21.025 Example MacOS[39165:6983054] An uncaught exception was raised
2016-05-14 16:19:21.026 Example MacOS[39165:6983054] *** -[NSConcreteFileHandle writeData:]: Operation not supported on socket
2016-05-14 16:19:21.026 Example MacOS[39165:6983054] (
	0   CoreFoundation                      0x00007fff9e2de4f2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff93b3373c objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9e3454bd +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff9c1b5347 -[NSConcreteFileHandle writeData:] + 74
	4   lf                                  0x00000001001c7c90 _TFC2lf8TSWriter17writeSampleBufferfTVs6UInt168streamIDVs5UInt812sampleBufferCSo14CMSampleBuffer_T_ + 7456
	5   lf                                  0x00000001001cd58a _TFC2lf8TSWriter12sampleOutputfT5audioCSo14CMSampleBuffer_T_ + 90
	6   lf                                  0x00000001001cd60c _TTWC2lf8TSWriterS_20AudioEncoderDelegateS_FS1_12sampleOutputfT5audioCSo14CMSampleBuffer_T_ + 44
	7   lf                                  0x000000010019b8bc _TFC2lf10AACEncoder13captureOutputfTGSQCSo15AVCaptureOutput_21didOutputSampleBufferGSQCSo14CMSampleBuffer_14fromConnectionGSQCSo19AVCaptureConnection__T_ + 2796
	8   lf                                  0x000000010019bbf4 _TToFC2lf10AACEncoder13captureOutputfTGSQCSo15AVCaptureOutput_21didOutputSampleBufferGSQCSo14CMSampleBuffer_14fromConnectionGSQCSo19AVCaptureConnection__T_ + 100
	9   lf                                  0x0000000100200bf7 _TFC2lf16AudioIOComponent13captureOutputfTGSQCSo15AVCaptureOutput_21didOutputSampleBufferGSQCSo14CMSampleBuffer_14fromConnectionGSQCSo19AVCaptureConnection__T_ + 87
	10  lf                                  0x0000000100200c94 _TToFC2lf16AudioIOComponent13captureOutputfTGSQCSo15AVCaptureOutput_21didOutputSampleBufferGSQCSo14CMSampleBuffer_14fromConnectionGSQCSo19AVCaptureConnection__T_ + 100
	11  AVFoundation                        0x00007fff9b848a90 __ConsumerRender_block_invoke + 141
	12  libdispatch.dylib                   0x0000000100a1e070 _dispatch_call_block_and_release + 12
	13  libdispatch.dylib                   0x0000000100a10cc5 _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x0000000100a16112 _dispatch_queue_drain + 351
	15  libdispatch.dylib                   0x0000000100a1de24 _dispatch_queue_invoke + 557
	16  libdispatch.dylib                   0x0000000100a14dab _dispatch_root_queue_drain + 1226
	17  libdispatch.dylib                   0x0000000100a148a5 _dispatch_worker_thread3 + 106
	18  libsystem_pthread.dylib             0x0000000100a73336 _pthread_wqthread + 1129
	19  libsystem_pthread.dylib             0x0000000100a70f91 start_wqthread + 13
)
