### ISSUE TITLE
Read MP4 file and stream it

### ISSUE THREAD

**Issue by pzs7602** [shogo4405/lf.swift#38]
Although lf.swift does not implement the function to stream data read from a MP4(H264/aac encoded) file to a stream server(wowza,for example), but I think that it is not difficult to implement this based on lf.swift, I'm not familiar with the structure of a MP4 file, any advice or guide? thanks in advance!

**Comment by shogo4405** [comment]
lf.swift supported the MP4File's streamng version 0.0.4
[https://github.com/shogo4405/lf.swift/releases/tag/0.0.4](url) RTMPMuxer.swift
Unfortunately, I removed when rewrite api (https://github.com/shogo4405/lf.swift/pull/2)

Already, lf.swift can parse a mp4 file. see [https://github.com/shogo4405/lf.swift/blob/43881a97ecc40fb73609822d9fac3e8cb3cc2dfc/Sources/ISO/MP4File.swift](url)

**Comment by pzs7602** [comment]
Will this feature be added again?

**Comment by shogo4405** [comment]
Yes. I want to do a implement again.
