### ISSUE TITLE
Audio problem with RTMP and iPhone6s not iPad

### ISSUE THREAD

**Issue by mghazy** [shogo4405/lf.swift#40]
First, Thank you for this amazing project.

I'm trying to stream RTMP to Wowza, The video streaming very good my problem with audio it sent very fast and doesn't sync with the video.

This problem with iPhone 6s, on iPad it's work fine.

iPhone debug:
    
    2016-05-20 23:54:27.445 [Debug] [VideoIOComponent.swift:31] VideoIOComponent > cicontext use hardware renderer
    2016-05-20 23:54:29.907 [Warning] [Function.swift:7] IsNoErr > -1
    2016-05-20 23:54:29.935 [Warning] [Function.swift:7] IsNoErr > -1
    2016-05-20 23:54:29.977 [Warning] [Function.swift:7] IsNoErr > -1
    2016-05-20 23:54:30.019 [Warning] [Function.swift:7] IsNoErr > -1
    2016-05-20 23:54:30.063 [Warning] [Function.swift:7] IsNoErr > -1
    2016-05-20 23:54:30.106 [Warning] [Function.swift:7] IsNoErr > -1
    2016-05-20 23:54:30.149 [Warning] [Function.swift:7] IsNoErr > -1
    2016-05-20 23:54:30.191 [Warning] [Function.swift:7] IsNoErr > -1

This warning came from `AACEncoder.swift > func onInputDataForAudioConverter`

    iPhone print(currentBufferList)
    Optional(__C.AudioBufferList(mNumberBuffers: 1, mBuffers: __C.AudioBuffer(mNumberChannels: 1, mDataByteSize: 1882, mData: 0x00000001034322c0)))
    
    iPad print(currentBufferList)
    Optional(__C.AudioBufferList(mNumberBuffers: 1, mBuffers: __C.AudioBuffer(mNumberChannels: 1, mDataByteSize: 2048, mData: 0x00000001034b62c0)))

My code:
    
        rtmpStream = RTMPStream(rtmpConnection: rtmpConnection)
        
        rtmpStream.videoSettings = [
            "profileLevel": kVTProfileLevel_H264_Baseline_5_0,
            "width": 288,
            "height": 512,
            "fps": 25,
            "bitrate": 1000000,
        ]
        
        rtmpStream.audioSettings = [
            "bitrate": 1000000
        ]
        
        rtmpStream.attachCamera(AVMixer.deviceWithPosition(.Back))
        rtmpStream.attachAudio(AVCaptureDevice.defaultDeviceWithMediaType(AVMediaTypeAudio))
        
        rtmpStream.view.frame = CGRectMake(0, 0, preview.frame.width, preview.frame.height)
        preview.addSubview(rtmpStream.view)
        
        rtmpConnection.connect(streamServer)
        rtmpStream.publish(streamName)

**Comment by shogo4405** [comment]
@mghazy 
Is it lf.swift 0.2? I fixed it since released 0.2.
I believe, current master branch works fine. (I tested OSX)

**Comment by shogo4405** [comment]
https://github.com/shogo4405/lf.swift/issues/18

**Comment by mghazy** [comment]
my version 0.2

	$ pod update
	Update all pods
	Updating local specs repositories
	Analyzing dependencies
	Downloading dependencies
	Using CryptoSwift (0.4.1)
	Using XCGLogger (3.3)
	Using lf (0.2)

**Comment by shogo4405** [comment]
OK. Please wait a next release.
I will release next weekend 28 May〜.

**Comment by mghazy** [comment]
Thank you and can you give me a clue how to fix this problem.

**Comment by shogo4405** [comment]
> can you give me a clue how to fix this problem.

means, Do you want to try now? please, try download current master branch.
* released 0.2 - 1 May
* fixed it  - 8 May

Because can't use cocoapods. 
I'm not sure. try to cocoapod master branch. sorry.
