### ISSUE TITLE
NAL packaging

### ISSUE THREAD

**Issue by pzs7602** [shogo4405/lf.swift#41]
I’m newbie in the field of video streaming, please help me to understand your code in method sampleOutput(video sampleBuffer: CMSampleBuffer) in RTMPMuxer.swift:
1. data in buffer is formed by a header and encoded video data got from CMBlockBuffer in the CMSampleBuffer.
2. the header is 5 bytes in length, byte[0] is either 0x17(if it’s a keyframe) or 0x27(if it’s not a keyframe)
3. byte[1] is 1(NAL type)
4. I watched from debug window that byte[2]..byte[4] is always 0x000000
5. so I get every buffer data(in hex):
   1701000000 followed by encoded H264 video data
or
   2701000000 followed by encoded H264 video data
I know that the encoded video buffer should be converted to NALU before sent to stream,the NALU should be Annex B(3 or 4 bytes start code in header) or AVCC(4bytes in length in header) type. so I donnt understand why the 5 bytes header be added before the encoded H264 video data, would you please to explain this to me? thank you very mush!

**Comment by shogo4405** [comment]
see also section VIDEODATA[p.9] and AVCVIDEOPACKET[p.10]  https://www.adobe.com/content/dam/Adobe/en/devnet/flv/pdfs/video_file_format_spec_v10.pdf

- First byte
 - FrameType UB[4] 0x11110000
 - CodecID UB[4] 0x00001111
- Second Byte
 - AVCPacketType UI8
- 3rd - 5th Bytes
 - CompositionTime SI24

**Comment by shogo4405** [comment]
if you have no questions. 
please close this isuue.

Regards.
