### ISSUE TITLE
 'RTMPStream' has no member 'videoGravity'

### ISSUE THREAD

**Issue by Victor1506** [shogo4405/lf.swift#46]
I got an error - Value of type 'RTMPStream' has no member 'videoGravity'.
And also, i want to ask how can i add YouTube Stream Key to rtmpConnection.connect

**Comment by shogo4405** [comment]
@Victor1506 
Did you try README.md's snipet? I'm mistaken. Please change here.
rtmpStream.view.videoGravity
```sh
var rtmpConnection:RTMPConnection = RTMPConnection()
var rtmpStream = RTMPStream(rtmpConnection: rtmpConnection)
// X -> rtmpStream.videoGravity =  AVLayerVideoGravityResizeAspectFill 
rtmpStream.view.videoGravity = AVLayerVideoGravityResizeAspectFill // OK
rtmpStream.attachAudio(AVCaptureDevice.defaultDeviceWithMediaType(AVMediaTypeAudio))
rtmpStream.attachCamera(AVMixer.deviceWithPosition(.Back))

view.addSubview(rtmpStream.view)
rtmpConnection.connect("rtmp://localhost/appName/instanceName")
rtmpStream.publish("streamName")
```

**Comment by shogo4405** [comment]
> i want to ask how can i add YouTube Stream Key to rtmpConnection.connect

rtmpConnection.connect("Server URL")
rtmpStream.publish('YouTube Stream Key')

**Comment by shogo4405** [comment]
https://github.com/shogo4405/lf.swift/issues/47
