### ISSUE TITLE
VisualEffect performance issue

### ISSUE THREAD

**Issue by pzs7602** [shogo4405/lf.swift#50]
I run Example iOS built from lf.swift project on my iPhone 6 Plus, the example runs OK, but when I use its Pronama feature(by pressing Pronama segment), the preview video and streamed video become not fluency, can the project be improved to solve this?

**Comment by shogo4405** [comment]
fixed it. current lf.swift works OK. https://github.com/shogo4405/lf.swift/blob/683f40a90688da3ed5bcf53fdb3368cb8a9729c3/Examples/iOS/Icon.png
This reason. I removed Icon.png by mistake.

**Comment by shogo4405** [comment]
Yes. have to do performance improvement.
By the way. my device are enough.

RTMPStream.currentFPS is average 30 (iPhone5S/fps=30/PronamaFilter)
RTMPStream.currentFPS is average 30 (iPad Pro/fps=30/PronamaFilter)

Can I see your RTMPStream.captureSettings and videoSettings?

**Comment by shogo4405** [comment]
I added a property RTMPStream.currentFPS #48

**Comment by pzs7602** [comment]
rtmpStream!.captureSettings = [
                    "sessionPreset": AVCaptureSessionPresetHigh,
                    "continuousAutofocus": true,
                    "continuousExposure": true,
                ]
                rtmpStream!.videoSettings = [
                    "width": 1280, // video output width
                    "height": 720, // video output height
                    "profileLevel": kVTProfileLevel_H264_Main_5_0,
                    "bitrate": 800*1024  // bitrate
                ]

**Comment by shogo4405** [comment]
Benchmark note:
iPhone5S AVCaptureSessionPreset1280x720, width:1280, height:720, master branch

|-|None| Monochrome|Pronama|
|:--:|:----------:|:-----------:|:------------:|
|FPS|30|22-24|13-15|
|CPU|25%|65%|70%|

**Comment by pzs7602** [comment]
That means capture cann't reach 30 Frame Per Seconds for Pronama effect?

**Comment by shogo4405** [comment]
@pzs7602 
Yes and no. I'm trying to reach 30 FPS now.
current gpu-rendering branch: reach 25-27 FPS.

**Comment by shogo4405** [comment]
@pzs7602 
Hi. Current master branch: Pronama filter reaches 30FPS.
I will release 0.4.0 in late August.

**Comment by shogo4405** [comment]
release 0.4.0
