### ISSUE TITLE
Audio Sample Rate Causing Bad Audio

### ISSUE THREAD

**Issue by triwav** [shogo4405/lf.swift#58]
So I couldn't figure out why the audio was sounding so bad on my iPhone 6S while recording. I finally read up on the iPhone 6S puts out only 48,000 hertz audio which I guess is different from previous devices. If I set 
rtmpStream.audioSettings = [
    "sampleRate": 48_000
]
then the audio sounds good on the iPhone 6S. If I don't provide a sample rate or I set sample rate to
rtmpStream.audioSettings = [
    "sampleRate": 44_100
]
then the audio sounds bad. This is a recording of what it sounds like
https://www.youtube.com/watch?v=n1EsW2ksBic

Now the main issue is if I set sample rate to 48,000 then it now has the same issue on my iPad mini 2. In both cases the logger says that the input format is 44,100 even though I'm pretty sure that's incorrect for the iPhone 6S. Is there any way to improve this detection or the sample rate resampling? Again appreciate all your work on this project.

**Comment by shogo4405** [comment]
1. framework has no down/up sampleRate feature. It's difficult for me. 
1. framework can change input sampleRate 48000(iPhone6S) to 44100, 22050...(iOS) 7989696.
```swift
let sampleRate:Double = 48_000 // or 44_100
do {
  try AVAudioSession.sharedInstance().setPreferredSampleRate(sampleRate)
  try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord)
  try AVAudioSession.sharedInstance().setMode(AVAudioSessionModeVideoChat)
  try AVAudioSession.sharedInstance().setActive(true)
} catch {
}
rtmpStream.audioSettings = [
    "sampleRate": sampleRate, 
]

// 2nd arguemnt set false
rtmpStream.attachAudio(AVCaptureDevice.defaultDeviceWithMediaType(AVMediaTypeAudio), false)
```
We can see. mSampleRate: 48000.0 (iPhone5S)
```swift
[fg0,0,255;[bg;2016-06-10 12:56:21.848 [Info] [AACEncoder.swift:64] inSourceFormat > Optional(__C.AudioStreamBasicDescription(mSampleRate: 48000.0, mFormatID: 1819304813, mFormatFlags: 12, mBytesPerPacket: 2, mFramesPerPacket: 1, mBytesPerFrame: 2, mChannelsPerFrame: 1, mBitsPerChannel: 16, mReserved: 0))[;
```
Try 2nd solution. best regards.

**Comment by Rupasekhar** [comment]
Hi,
i've kept the same sample rate in my code, rtmpStream.audioSettings = [
"sampleRate": 48_000
]

rtmpStream.audioSettings = [
"sampleRate": 41_000
]
But I'm having low audio issue in iPhone 6S Plus and Higher devices.
Can you please figure out what might be the issue in this..?

**Comment by Rupasekhar** [comment]
Hi,
i've kept the same sample rate in my code, rtmpStream.audioSettings = [
"sampleRate": 48_000
]

rtmpStream.audioSettings = [
"sampleRate": 41_000
]
But I'm having low audio issue in iPhone 6S Plus and Higher devices.
Can you please figure out what might be the issue in this..?
