### ISSUE TITLE
Performance issue: iPad mini2, video bitrate=1024kbps

### ISSUE THREAD

**Issue by triwav** [shogo4405/lf.swift#59]
I didn't see this issue until today as I've been doing all my dev on an iPhone 6S but when I'm testing it on an iPad mini 2 and I crank up the video bitrate to 1024kbps or there about the program uses one full cpu core which then causes the frame rate to crash. I've profiled it in instruments and tracked it down to this line I believe: https://github.com/shogo4405/lf.swift/blob/master/Sources/RTMP/RTMPChunk.swift#L194
I tried a few alternative ways to combine the arrays but they all gave the same or worse performance. Let me know if some instrument logs would be helpful. Thanks again for all your hard work on this project.

**Comment by shogo4405** [comment]
@triwav 
Is your logging level is .Info or .Verbose?

**Comment by triwav** [comment]
Where do I specify that?

**Comment by shogo4405** [comment]
https://github.com/shogo4405/lf.swift/blob/master/Examples/iOS/AppDelegate.swift#L23

**Comment by triwav** [comment]
It's set to info

**Comment by triwav** [comment]
I should add this isn't just an issue with the iPad mini 2. I'd noticed an issue when using higher bitrates on the my iPhone 6S as well but thought it was an issue of me not setting the proper profile. That same line of code uses the vast majority of cpu time on the iPhone 6S as well. It can handle 1024kbps better because of the faster processor but bringing it up to 1500-2000kbps causes it to hit [Error] [AVCEncoder.swift:126] AVCEncoder > status = -12912[; I get this same error on the iPad mini 2 if I try and start the stream at 1024kbps instead of starting at a lower level and then increase it once it begins.

**Comment by triwav** [comment]
Alright, so I think I have a fix for this. Feel free to change the variable names but replacing https://github.com/shogo4405/lf.swift/blob/master/Sources/RTMP/RTMPChunk.swift#L194 with
if let message = message {
    var bytesCombine = _bytes
    bytesCombine.appendContentsOf(message.payload)
    return bytesCombine
} else {
    return _bytes
}
and then the same with https://github.com/shogo4405/lf.swift/blob/master/Sources/RTMP/RTMPChunk.swift#L210
I notice you are force unwrapping message here without actually checking it's not nil so I think it would make sense to do the same check as we do for line 194 and just return _bytes if it's empty. Let me know if you want me to put this in a pull request.

**Comment by shogo4405** [comment]
Thanks!! I will test and change this code.

**Comment by triwav** [comment]
So I still can't explain why but after changing that one spot I looked to the second highest CPU use section which is the split function https://github.com/shogo4405/lf.swift/blob/master/Sources/RTMP/RTMPChunk.swift#L162-L179

I tried replacing the following lines
https://github.com/shogo4405/lf.swift/blob/master/Sources/RTMP/RTMPChunk.swift#L172-L176
with:
while (total + size < bytes.count) {
    var bytesCombine = basicHeader
    bytesCombine.appendContentsOf(Array(bytes[total..<total + size]))
    result.append(bytesCombine)
    total += size
}
var bytesCombine = basicHeader
bytesCombine.appendContentsOf(Array(bytes[total..<bytes.count]))
result.append(bytesCombine)

and while I noticed a minor improvement it wasn't nearly as monumental as the previous. Still can't explain why this is. The arrays aren't that different in size so I can't explain why it's not helping the same way. Perhaps you have a better grasp on this. I did come with a benchmark that demonstrates this issue though:

var result:[Int] = []
for _ in 0..<10000 {
    result.append(Int(arc4random_uniform(255)))
}
let array = [0,3,5,3] 

var startTime = CFAbsoluteTimeGetCurrent()
for _ in 0..<10000 {
    let _ = array + result
}
print("A time taken\(CFAbsoluteTimeGetCurrent() - startTime)")

startTime = CFAbsoluteTimeGetCurrent()
for _ in 0..<10000 {
    var combinedArray = array
    let _ = combinedArray.appendContentsOf(result)
}
print("B time taken\(CFAbsoluteTimeGetCurrent() - startTime)")

I get the following results on my iPhone 6S
A time taken37.2160499691963
B time taken0.0648040175437927

**Comment by shogo4405** [comment]
@triwav Thanks!
Average CPU is 20〜30% (iPhone5S, 1024kbps)

**Comment by shogo4405** [comment]
```sh
// ByteArray

// Case A
    public func writeBytes(value:[UInt8]) -> Self {
        if (position == bytes.count) {
            bytes.appendContentsOf(value)
            // ~~~~~~~~~~~~~~~~~~~~~~~~
            position = bytes.count
            return self
        }
        let length:Int = min(bytes.count, value.count)
        bytes[position..<position + length] = value[0..<length]
        if (length == bytes.count) {
            bytes += value[length..<value.count]
        }
        position += value.count
        return self
    }

// Case B
    public func writeBytes(value:[UInt8]) -> Self {
        if (position == bytes.count) {
            bytes += value
            // ~~~~~~~~~~~
            position = bytes.count
            return self
        }
        let length:Int = min(bytes.count, value.count)
        bytes[position..<position + length] = value[0..<length]
        if (length == bytes.count) {
            bytes += value[length..<value.count]
        }
        position += value.count
        return self
    }

final class ByteArrayTests: XCTestCase {
    func testBenchmark() {
        var data:[UInt8] = []
        for _ in 0..<100 {
            data.append(UInt8(arc4random_uniform(255)))
        }
        let bytes:ByteArray = ByteArray()
        for _ in 0..<10000 {
            bytes.writeBytes(data)
        }
    }
}
```
1. Case A:  Test Case '-[Tests.ByteArrayTests testBenchmark]' passed (0.036 seconds).
1. Case B:  Test Case '-[Tests.ByteArrayTests testBenchmark]' passed (0.073 seconds).

I think appendContentsOf is better than "+=".

**Comment by shogo4405** [comment]
```swift
final class ByteArrayTests: XCTestCase {

    func testBenchmarkA() {
        var data:[UInt8] = []
        for _ in 0..<100 {
            data.append(UInt8(arc4random_uniform(255)))
        }
        var result:[UInt8] = []
        for _ in 0..<100000 {
            result += data
        }
    }

    func testBenchmarkB() {
        var data:[UInt8] = []
        for _ in 0..<100 {
            data.append(UInt8(arc4random_uniform(255)))
        }
        var result:[UInt8] = []
        for _ in 0..<100000 {
            result.appendContentsOf(data)
        }
    }
}
```
Table Of Result

|-|Try1|Try2|Try3|Try4|Try5|
|:-:|:-:|:-:|:-:|:-:|:-:|
|A|0.192|0.201|0.183|0.197|0.205|
|B|0.141|0.147|0.130|0.137|0.143|

**Comment by shogo4405** [comment]
@triwav 
Optimization Level -none (iPhone5S)
A time taken61.5075600147247
B time taken0.86178195476532

Optimization Level -Fast (iPhone5S)
A time taken1.05674999952316
B time taken0.833347976207733

Optimization Level -Fast, Whole Module Optimization (iPhone5S)
A time taken1.02917098999023
B time taken0.808952987194061

**Comment by triwav** [comment]
Interesting incite @shogo4405. Thanks.
