### ISSUE TITLE
Pod install error

### ISSUE THREAD

**Issue by Duallip** [shogo4405/lf.swift#60]
Hi,
I have a problem with the intall.
Cocoapods return this error

> [!] Unable to satisfy the following requirements:
>
>- `lf (~> 0.3.0)` required by `Podfile`
>
>None of your spec sources contain a spec satisfying the dependency: `lf (~> 0.3.0)`.
>
>You have either:
> * out-of-date source repos which you can update with `pod repo update`.
> * mistyped the name or version.
> * not added the source repo that hosts the Podspec to your Podfile.
>
>Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

My podfile

>  # Uncomment this line to define a global platform for your project
>platform :ios, ‘8.0’
>
>target 'Stampyt_Live_Video' do
>  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
>  use_frameworks!
>
>  pod 'lf', '~> 0.3.0’
>
>  # Pods for Stampyt_Live_Video
>
>  target 'Stampyt_Live_VideoTests' do
>    inherit! :search_paths
>    # Pods for testing
>  end
>
>  target 'Stampyt_Live_VideoUITests' do
>    inherit! :search_paths
>    # Pods for testing
>  end
>
>end

**Comment by shogo4405** [comment]
works for me.
```swift
ceylon:Test shogo$ pwd
/Users/shogo/Dropbox/xcode/Test
ceylon:Test shogo$ pod --version
1.0.1
ceylon:Test shogo$ pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing XCGLogger (3.3)
Installing lf (0.3.2)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total
pods installed.
```
```swift
platform :ios, ‘8.0’

target 'Test' do
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'lf', '~> 0.3.0’

end
```

**Comment by Duallip** [comment]
Hi,
I have found the solution.
I used TextEdit for editing the Podfile and this is not a good idea he adds weirds quote.
I edit Podifile with xCode and it's good.
