### ISSUE TITLE
Audio streaming (HLS) does not work on OSX.

### ISSUE THREAD

**Issue by yannickl** [shogo4405/lf.swift#61]
Hi,

On OSX when I use the HLS method to stream video and audio, the audio does not work because of an invalid packet size `kAudioConverterErr_InvalidInputSize = 'insz'` (code 1768846202) [here](https://github.com/shogo4405/lf.swift/blob/00d4c8bf002681ebc6ac6352c228b2583f116c37/Sources/Codec/AACEncoder.swift#L225).

It works fine on my iPhone, but not on my macbook.

PS: I use your project example.

**Comment by shogo4405** [comment]
Yes. can't work built in microphone.
I tested a external microphone.

I will try fix.

**Comment by shogo4405** [comment]
released 0.3.4

**Comment by yannickl** [comment]
Thank you!
