### ISSUE TITLE
Better handle connection interruption

### ISSUE THREAD

**Issue by triwav** [shogo4405/lf.swift#64]
So starting to do some testing to see how the framework handles connection interruptions and am noticing some issues. So sometimes (although rarely) when the wifi connection goes away I get a proper NetConnection.Connect.Closed notification. In these cases I can handle the notification and reconnect when the connection returns or reconnect using the cellular connection. Reconnect attempts work as expected and it starts streaming again. What normally happens though is that I get no notification and it continues trying to encode for a little while. At this point the ram usage starts climbing and eventually we hit this loop: https://github.com/shogo4405/lf.swift/blob/master/Sources/Net/NetSocket.swift#L65-L69
At this point length is repeatedly returning -1 which means we can never get out of the loop and the app uses all the available cpu cycles. It doesn't matter if you hit the stop button before it gets in this loop it will eventually use all the cpu. At this point trying to start streaming again will never work and the only way to get it back working is to force quit the iOS application and reopen it. Let me know if I can provide any further details to help clarify things. Thanks again for all your work on this framework.

**Comment by shogo4405** [comment]
fixed. and released 0.3.3
