### ISSUE TITLE
Zoom options

### ISSUE THREAD

**Issue by tomerhatav-zent** [shogo4405/lf.swift#66]
Hi @shogo4405 ,
Is there any way that we can zoom in and out while streaming?

Thank you.

**Comment by pzs7602** [comment]
Yes u can.
add this method to VideoIOComponent.swift:

    var videoZoomFactor:CGFloat?{
        didSet{
            guard let
            device:AVCaptureDevice = input?.device,
                factor:CGFloat = videoZoomFactor where factor < device.activeFormat.videoMaxZoomFactor else{
                    return
            }
            
            do {
                print("max factor=\(device.activeFormat.videoMaxZoomFactor)")
                try device.lockForConfiguration()
                // transition time: 2^(-4.0)
                device.rampToVideoZoomFactor(factor, withRate: -4.0)
                device.unlockForConfiguration()
            } catch let error as NSError {
                logger.error("while locking device for videoZoomFactor: \(error)")
            }
        }
    }

and this to RTMPStream.swift :

    public func setVideoZoomFactor(factor:CGFloat)
    {
        mixer.videoIO.videoZoomFactor = factor
    }

in your ViewController，add an UIPinchGestureRecognizer to its view:

                let pinchGesture = UIPinchGestureRecognizer(target: self, action: #selector(pinchScreen(_:)))
                touchView.addGestureRecognizer(pinchGesture)

gesture action:

    // we only allow 4x zoom out
    func pinchScreen(gesture:UIPinchGestureRecognizer)
    {
        let newScale:CGFloat = gesture.scale-self.lastScale+1.0
        if gesture.state == .Ended{
            if newScale > 1.0{
                print("pinch out")
                if self.currentZoomFactor * 2.0 <= 4.0{
                    self.rtmpStream?.setVideoZoomFactor(self.currentZoomFactor * 2.0)
                    self.currentZoomFactor *= 2.0
                }
            }
            else{
                print("pinch in")
                if self.currentZoomFactor / 2.0 >= 1.0{
                    self.rtmpStream?.setVideoZoomFactor(self.currentZoomFactor / 2.0)
                    self.currentZoomFactor /= 2.0
                    
                }
            }
            self.lastScale = 1.0
        }

    }

**Comment by pzs7602** [comment]
@shogo4405 
consider to add this feature

**Comment by shogo4405** [comment]
@pzs7602 
Thank u.
