### ISSUE TITLE
Support for uploading HLS playlist and ts segments to remote server

### ISSUE THREAD

**Issue by HiroshiHorie** [shogo4405/lf.swift#67]
Hello, 

If I would like to upload the Live stream to an remote server such as AWS S3, how could I do this ?
Is it currently possible with your framework or what modifications do i need to make ?

And can I also confirm if this the encoding is hardware accelerated by VideoToolbox ?

Regards
Hiroshi

**Comment by shogo4405** [comment]
> If I would like to upload the Live stream to an remote server such as AWS S3, how could I do this ?

1. framework(RTMP) + nignx-rtmp-module(mount AWS S3)
 - It is convenient.
1. framework(HLS) + AWS S3
 - have to do modifications. You can get a .ts 
https://github.com/shogo4405/lf.swift/blob/master/Sources/HTTP/TSWriter.swift#L151
Then upload file. 
 - get a playlist TSWriter#playlist https://github.com/shogo4405/lf.swift/blob/master/Sources/HTTP/TSWriter.swift#L13-L24

> And can I also confirm if this the encoding is hardware accelerated by VideoToolbox ?

Yes. audio too.
