### ISSUE TITLE
Add bandwidth monitoring of some type

### ISSUE THREAD

**Issue by triwav** [shogo4405/lf.swift#69]
So the latest issue I'm noticing is that because sending is handled separately from encoding the reported currentFPS does not accurately reflect that there are no issues with the stream. It just means that the CPU is able to keep up with the encoding side. If there is not enough bandwidth available then everything just keeps getting queued up and the ram usage will keep growing. Currently there's no way to detect this other than to keep track of how much memory the app is using which isn't the best way to handle this. If we know at what rate data is being sent out we can build some checks to make sure that given the current audio and video bitrates that our connection is keeping up with sending the data out. Two options I see here. First we have a totalBytesOut property already: https://github.com/shogo4405/lf.swift/blob/master/Sources/Net/NetSocket.swift#L15 this could opened up by changing it and its class to public and making https://github.com/shogo4405/lf.swift/blob/master/Sources/RTMP/RTMPConnection.swift#L165 public as well. There are several other things that would need to be made public as well as a result of this.
The second option is to add some new properties to the RTMPStream class. You'd need to add something like
dynamic public private(set) var currentBytesPerSecond:Int = 0
and a variable to store the previousTotalBytesOut which you could then subtract like rtmpConnection.socket.totalBytesOut - previousTotalBytesOut to get currentBytesPerSecond. Being able to know total bytes out might be useful info in some apps so not sure if  previousTotalBytesOut should be public as well or not.

These are just ways to handle this. Feel free to come with some other method but at the end of the day we need the ability to know when the connection isn't able to keep up with the video data it's being fed. I don't know if it's possible to know how many items are queued on the com.github.shogo4405.lf.NetSocket.lock queue or not but this would be another way of knowing if we're getting behind on sending.

**Comment by shogo4405** [comment]
@triwav 
I'm off 21 Jun - 29 Jun. when i come back. I do this. 
I think not good public to socket. I want to implement RTMPStream#currentBytesPerSecond

**Comment by triwav** [comment]
Thanks @shogo4405. Get to it when you can. One thing of note that you probably have no control over but I've noticed the bitrate you specify for video can often times be exceeded especially if you're moving the camera around a lot. This makes it harder in trying to figure out if the connection is keeping up or not since you don't actually know what the true bitrate is. If you have any ideas on better ways to handle this I'd love to hear.

**Comment by triwav** [comment]
So can't believe I didn't think of this until just now. We don't care what the queue depth is really. What we care about is how many bytes are waiting to be sent out. This we can get to fairly easily. All we need to do is add a property say 
private(set) var totalPendingBytesOut = 0
here
https://github.com/shogo4405/lf.swift/blob/master/Sources/Net/NetSocket.swift#L16 

Then at a minimum add onto it in https://github.com/shogo4405/lf.swift/blob/master/Sources/Net/NetSocket.swift#L28-L32
final func doOutput(bytes bytes:[UInt8]) {
	totalPendingBytesOut += bytes.count       
	dispatch_async(lockQueue) {
		self.doOutputProcess(UnsafePointer<UInt8>(bytes), maxLength: bytes.count)
	}
}
adding onto it the other doOutputs would probably be a good idea for consistency but isn't needed in the case of RTMP.

reset it here https://github.com/shogo4405/lf.swift/blob/master/Sources/Net/NetSocket.swift#L92

and then in https://github.com/shogo4405/lf.swift/blob/master/Sources/RTMP/RTMPStream.swift add a couple computed properties like
public var rtmpConnectionTotalBytesOut: Int {
	return rtmpConnection.socket.totalBytesOut
}

public var rtmpConnectionTotalPendingBytesOut: Int {
	return rtmpConnection.socket.totalPendingBytesOut
}

From this you could get totalBytes out, how many bytes are queued for output and current bytes per second (with a timer). I think this makes the most sense and provides the most flexibility.

**Comment by triwav** [comment]
I suppose you could also add computed properties on https://github.com/shogo4405/lf.swift/blob/master/Sources/RTMP/RTMPConnection.swift if you wanted instead. Not sure which spot it seems to fit better.

**Comment by shogo4405** [comment]
@triwav 
framework will support these property. 99127c6 Do you want other properties?
* RTMPConnection
 - totalBytesIn:UInt64 // = publishStream1.byteCount + publishStream2.byteCount + other data
 - totalBytesOut:UInt64 // = playStream1.byteCount + playStream1.byteCount + other data
 - currentBytesInPerSecond:UInt32
 - currentBytesOutPerSecond:UInt32
* RTMPStream
 - info:RTMPStreamInfo
    - resourceName:String
    - byteCount:UInt64  // publishing totalOutBytes, playling totalInBytes
    - currentBytesPerSecond:UInt32

> This makes it harder in trying to figure out if the connection is keeping up or not since you don't actually know what the true bitrate is. If you have any ideas on better ways to handle this I'd love to hear.

I think kVTCompressionPropertyKey_DataRateLimits property. 
https://github.com/shogo4405/lf.swift/issues/71

**Comment by triwav** [comment]
Thanks @shogo4405. This will largely work for me. This gets us close enough to know if the connection is keeping up. We still don't have a perfect picture though since all the commands to connect, publish, etc skip the rtmpstream and go straight to the rtmpsocket. Because of this you can have what appears to be more bytes out than bytes that have been queued up to go out. If you could add a property on RTMPConnection something like totalQueuedBytesOut that gets the number of bytes that have been queued on the socket that would be ideal but like I said this gets us close enough to make it work.

**Comment by shogo4405** [comment]
OK. next time :)

**Comment by shogo4405** [comment]
released 0.3.4
