### ISSUE TITLE
I want to put the array to the arguments of the call method.

### ISSUE THREAD

**Issue by cocoloper** [shogo4405/lf.swift#70]
I want use custom call method with  arguments to array.
but I can not complete the process with an error.
How wowza will be capable of processing array format

for iOS
call("sendMessage" ,responder:nil, argments:arrayParams)

for Wowza
sendMessage(IClient client, RequestFunction function, AMFDataList arrayParams)

**Comment by shogo4405** [comment]
try here.
```swift
var arrayParams:ASArray = ["foo","bar"]
call("sendMessage" ,responder:nil, argments:arrayParams)
```

P.S. 日本語でも大丈夫です。
