### ISSUE TITLE
Save File locally?

### ISSUE THREAD

**Issue by KCastiglione** [shogo4405/lf.swift#73]
is it possible to save the video stream created to local photo Album (iOS) and in file system (Mac)?

**Comment by shogo4405** [comment]
it is not. framework has no feature.

**Comment by AshishMall** [comment]
is there any method to save stream locally because i write this code  -----------------------------
rtmpStream.publish(Preference.defaultInstance.streamName!, type: .localRecord)--------------
but not saved in my gallery.
