### ISSUE TITLE
Audio mute

### ISSUE THREAD

**Issue by iSinch** [shogo4405/lf.swift#74]
@shogo4405  Hey bro.thanks for your project.
Could you tell me, please. How can I mute or unmute when i tap the button ?

> rtmpStream.audioSettings = [
>     "muted": true,
> ]

it's not work for me

**Comment by shogo4405** [comment]
You’re welcome. works for me...
> rtmpStream.audioSettings = [
>     "muted": true,
> ]
Tell me, your framework version. 
framework supported muted property since 0.3.2

**Comment by iSinch** [comment]
Ooo,you're right. Now it's work for me ;)
may be you will update information in cocoaPods and README.md about newVersion ?
thank's you
