### ISSUE TITLE
RTMP Code always Closed 

### ISSUE THREAD

**Issue by oxxy** [shogo4405/lf.swift#76]
I'm trying to stream to Facebook, after providing the Stream URL and run the App I got the code value = NetConnection.Connect.Closed and stream is offline 
This is the Event object
```
Event{
  type:rtmpStatus,
  bubbles:false,
  data:Optional([
    "level": Optional("status"), 
    "code": Optional("NetConnection.Connect.Closed"), 
    "description": Optional("")
    ]),
    target:Optional(<lf.RTMPConnection: "0x16d46ad0">)
}
```

**Comment by shogo4405** [comment]
It works for me. I tested 0.3.4
releated issue https://github.com/shogo4405/lf.swift/issues/51
