### ISSUE TITLE
jittery audio / fan noise

### ISSUE THREAD

**Issue by San-Jeevan** [shogo4405/lf.swift#82]
Xcode7 running the app on IOS 9.3.3 iPhone 6s

The audio is completely jittery. Like when I say hello, you can hear "h..l..o".
There is also a fan-noise in background, I dont know where it comes from because its completely silent in my house right now.

I have uploaded a sample of the bug
[https://www.youtube.com/watch?v=eOEXRReLQGc](https://www.youtube.com/watch?v=eOEXRReLQGc)

The code I used was
` let rtmpConnection:RTMPConnection = RTMPConnection()
        let rtmpStream = RTMPStream(rtmpConnection: rtmpConnection)

```
    rtmpStream.captureSettings = [
        "fps": 30, // FPS
        "sessionPreset": AVCaptureSessionPresetHigh, // input video width/height
        "continuousAutofocus": false, // use camera autofocus mode
        "continuousExposure": false, //  use camera exposure mode
    ]
    rtmpStream.audioSettings = [
        "muted": false, // mute audio
        "bitrate": 64 * 1024,
    ]

    rtmpStream.videoSettings = [
        "width": 1280, // video output width
        "height": 720, // video output height
        "bitrate": 1200 * 1024, // video output bitrate
        "profileLevel": kVTProfileLevel_H264_Baseline_3_1, // H264 Profile require "import VideoToolbox"
        "maxKeyFrameIntervalDuration": 2, // key frame / sec
    ]


    rtmpStream.view.videoGravity = AVLayerVideoGravityResizeAspectFill
    rtmpStream.attachAudio(AVCaptureDevice.defaultDeviceWithMediaType(AVMediaTypeAudio))
    rtmpStream.attachCamera(AVMixer.deviceWithPosition(.Back))

    view.addSubview(rtmpStream.view)
    rtmpConnection.connect("rtmp://bmorigin.cloudapp.net:1935/live")
    rtmpStream.publish("test")
```

`

The RTMP server is fine, I tried broadcasting from my webcam and it worked smoothly.

**Comment by Duallip** [comment]
Hi,

See this closed issues : #58

**Comment by shogo4405** [comment]
I cant' see the video.
well... I think fixed it since 0.3.0... It seems not be fixed.
please try #58

**Comment by San-Jeevan** [comment]
great thanks

**Comment by jagadesh93** [comment]
@shogo4405 I am facing the same issue like fan sound in back ground
`self.rtmpStream.captureSettings = [
                .fps: 30, // FPS
                .sessionPreset: AVCaptureSession.Preset.medium, // input video width/height
                .continuousAutofocus: false, // use camera autofocus mode
                .continuousExposure: false, //  use camera exposure mode

            ]
            self.rtmpStream.audioSettings = [
                .muted: false, // mute audio
                .bitrate: 32 * 1000,
                .sampleRate: 48000.0,
            ]
            self.rtmpStream.videoSettings = [
                .width: 960,  // video output width
                .height: 540,  // video output height
                .bitrate: 1024 * 512, // video output bitrate
                .profileLevel: AVVideoProfileLevelH264Baseline31,//kVTProfileLevel_H264_Baseline_3_1, // H264 Profile require "import VideoToolbox"
                .maxKeyFrameIntervalDuration: 2, // key frame / sec
            ]
            
            self.rtmpStream.mixer.session.commitConfiguration()`
