### ISSUE TITLE
Any plan for pull rtmp stream ?

### ISSUE THREAD

**Issue by chenshaobo** [shogo4405/lf.swift#85]
It is amazing work for push rtmp stream , man!
but I didn't see pull rtmp stream example.
Does this project support pull rtmp stream?

**Comment by shogo4405** [comment]
framework has a playback feature.
http://cocoadocs.org/docsets/lf/0.3.4/Classes/RTMPStream.html#/s:FC2lf10RTMPStream4playFtGSaGSqP____T_
currently, exprimental and buggy.
I recommend VLCKit for playback RTMP/RTSP and so on.
https://code.videolan.org/videolan/VLCKit

**Comment by chenshaobo** [comment]
thx！ I will try。
