### ISSUE TITLE
Unable to broadcast video, when stop broadcast and start again.

### ISSUE THREAD

**Issue by serbintv** [shogo4405/lf.swift#87]
Hello!

I build example from git. And have a problem when i try to broadcast video after app start all works fine. But when i stop broadcasting and try to broadcast again nothing happend. Seems like LiveViewController don't receive notifications from rtmpConnection.

**Comment by shogo4405** [comment]
umm. yes. I will fix asap.

**Comment by shogo4405** [comment]
@serbintv 
I fixed it. #84 is a cause.
