### ISSUE TITLE
Connection lost handling

### ISSUE THREAD

**Issue by MingLoan** [shogo4405/lf.swift#9]
Any easy way to return error once stream is interrupted after network lost??

**Comment by shogo4405** [comment]
Not yet...X)
Thank u feed back.

**Comment by shogo4405** [comment]
take notes NetConnection specifications
* no route to host
 1. NetConnection.Connect.Failed
* client network down
 1. NetConnection.Connect.Success:Connection succeeded.
 1. NetConnection.Connect.NetworkChange:undefined
 1. NetConnection.Connect.NetworkChange:undefined
 1. NetConnection.Connect.Closed:undefined

**Comment by MingLoan** [comment]
you means the notification will return these?

**Comment by shogo4405** [comment]
no. i'm going to implement this notes.

**Comment by MingLoan** [comment]
one more suggestion, can you let developer to toggle debug mode for showing logs? for now.. streaming logs flush the console.

**Comment by mrbemani** [comment]
my current solution is repeatedly check the connected property of RTMPConnection, it works for me.

**Comment by MingLoan** [comment]
I can't playback via HLS from WOWZA server. Seems the encoding is not compatible. Any idea?

I can stream onto WOWZA server but I cannot playback using native AVPlayer on my iPhone.

**Comment by mrbemani** [comment]
me too. the problem is very strange. if you play within 5 seconds after you broadcast, you will see the video. but the playlist.m3u8 file changes after about 5 seconds, then, you cannot play it on any IOS device. Although you still can play it on MAC, PC, ANDROID.....very very strange.....

**Comment by mrbemani** [comment]
the playlist.m3u8 file firstly look like this:

**Comment by mrbemani** [comment]
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=250000
chunklist.m3u8

**Comment by mrbemani** [comment]
after a while. it changes to this:

**Comment by mrbemani** [comment]
after a while it changes to this:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=141274,CODECS="avc1.66.11,mp4a.40.1",RESOLUTION=136x240
chunklist.m3u8

**Comment by mrbemani** [comment]
once it become this ⬆️  format, no IOS device can play it.

**Comment by shogo4405** [comment]
(oh... I'm wrong issue number...)

**Comment by shogo4405** [comment]
Currently, can handle lost connection. 

> * no route to host
 1. NetConnection.Connect.Failed
* client network down
 1. NetConnection.Connect.Success:Connection
 1. NetConnection.Connect.Closed
* server shutdown
 1. NetConnection.Connect.Success: Connection succeeded.
 1. NetConnection.Connect.Closed

**Comment by sherm4n90** [comment]
@MingLoan Hello, Im trying to implement a live streaming app. Already using Wowza Cloud API to create the live_stream. Can you tell me how can I connect to the rtmp source, Im using the rtmp source provided inside de live_stream object recently created("source_connection_information") but Is not working. Thanks in advance.

**Comment by allenlinli** [comment]
Should `RTMPConnection.Code.connectClosed.rawValue` be called in `rtmpStatusHandler` when it does `rtmpConnection.close()`?
I didn't receive the event `connectClosed`.

https://github.com/shogo4405/HaishinKit.swift/issues/653
