### ISSUE TITLE
Class name "Event" is repeated in ReactiveCocoa framework

### ISSUE THREAD

**Issue by AdamLuisSean** [shogo4405/lf.swift#90]
When swift class contains ReactiveCocoa and lf frameworks and using 'Event' class on the same class it fails with an error:
![screen shot 2016-08-16 at 2 35 06 pm](https://cloud.githubusercontent.com/assets/10870984/17697684/dcfdefc6-63be-11e6-9cba-2c3db603ea5b.png)
Please rename "Event" class using most unique name. Thanks!

**Comment by shogo4405** [comment]
best practice is "framework name" prefix.
 ```swift
let e:lf.Event = lf.Event.from(notification)
 ```
