### ISSUE TITLE
Crash when try to get rtmpSream.videoSettings

### ISSUE THREAD

**Issue by serbintv** [shogo4405/lf.swift#91]
Hi!
I have a crash when try to get rtmpSream.videoSettings.
`2016-08-22 14:30:07.099 Example iOS[4615:960666] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<lf.AVCEncoder 0x14d8f590> valueForUndefinedKey:]: this class is not key value coding-compliant for the key enabledHardwareEncoder.'

*** First throw call stack:
(0x21c9391b 0x2142ee17 0x21c93629 0x2248a6bb 0x223ebacd 0x2248a8cf 0x2cdf90 0x2213e4 0xa8fb6b 0xa990d5 0x2c9a5c 0x33c70 0x35f34 0x2620cd8b 0x262ca683 0x262ca575 0x262c9929 0x262c955f 0x262c91b5 0x262c912b 0x26208a73 0x242a1bdd 0x2429d385 0x2429d219 0x2429c6e1 0x2429c3b5 0x264c1619 0x21c55d21 0x21c557dd 0x21c53d51 0x21ba3229 0x21ba3015 0x23193ac9 0x26275189 0x2f748 0x2184b873)
libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by shogo4405** [comment]
@serbintv 
Yes.  This is the correct behavior.
+ "enabledHardwareEncoder" property is macOS only. 
+ It seemes framework versions is older. enabledHardwareEncoder is supported since 0.4.0.

**Comment by serbintv** [comment]
I use framework from git. And just add this line to your IOS example. I don't add this key to videoSettings dictionary.

**Comment by shogo4405** [comment]
Sorry. I will fix.

**Comment by shogo4405** [comment]
fixed it X)

**Comment by serbintv** [comment]
Thanks for your work.
