### ISSUE TITLE
RTMP Chunk size

### ISSUE THREAD

**Issue by sherm4n90** [shogo4405/lf.swift#92]
Hello, can I set a custom RTMP chunk size before going live? Thanks

**Comment by shogo4405** [comment]
@sherm4n90 
framework can't. I will make it :)

**Comment by shogo4405** [comment]
Hi. I updated. Let's try.

    var connection = RTMPConnection()
    connection.chunkSize = xxx

**Comment by sherm4n90** [comment]
@shogo4405 I will try it. Thanks for the quick response and your awesome work.

**Comment by sherm4n90** [comment]
@shogo4405 it is not yet in 0.4.0 right?

**Comment by shogo4405** [comment]
Yes. Please try current master branch from git.

**Comment by shogo4405** [comment]
released 0.4.1
