### ISSUE TITLE
Video capture session lost with incoming call

### ISSUE THREAD

**Issue by sherm4n90** [shogo4405/lf.swift#93]
If a phone call is received, the connection outgoing bytes drops to 0, that's ok I think, but then when the call is rejected or ended, the streaming start sending bytes again but only for audio, fps still in 0. There is something I can do when this happens? to force the framework to reconnect the video session or something like that?

**Comment by shogo4405** [comment]
@sherm4n90 
Thank u. I fixed it. Please wait next release 0.4.1. (3 Sep)

**Comment by sherm4n90** [comment]
@shogo4405 Awesome my friend. How would I recover the video transmission?

**Comment by shogo4405** [comment]
You don’t have to recover.
framework detect a phone call end, then recover automatically.

**Comment by shogo4405** [comment]
released 0.4.1
