### ISSUE TITLE
Swift 3.0 Migration

### ISSUE THREAD

**Issue by shogo4405** [shogo4405/lf.swift#95]
* https://swift.org/migration-guide/

**Comment by shogo4405** [comment]
I will be able to release 17 Sep.
Please wait :)

**Comment by tomerhatav** [comment]
Hi shogo, 
any news on that?

**Comment by shogo4405** [comment]
@tomerhatav and Everyone
Delayed. I'm waiting for release the XCGLogger 4.0.0.
Unfortunately, xcode framework project have to all dependencies are Swift 3.0.

**Comment by tomerhatav** [comment]
XCGLogger 4.0.0. has been released :)

**Comment by shogo4405** [comment]
Released 0.5.0.
frameworks has sume issues #104. I will fix 0.5.1 soon :)
