### ISSUE TITLE
Build error in 0.4.1

### ISSUE THREAD

**Issue by sherm4n90** [shogo4405/lf.swift#98]
I got an build error in this Line:
`stream.attachCamera(AVMixer.deviceWithPosition(.Back))`

says  'Use of unresolved identifier AVMixer'

I have tried with `DeviceUtil..deviceWithPosition(.Back)` and it compiles but sometimes it shows a black screen. Also flipping the camera make the app frozen.

**Comment by sherm4n90** [comment]
never mind. I used `DeviceUtil.deviceWithPosition(position)` and it works. You may need to update the docs.

**Comment by shogo4405** [comment]
close as duplicate #104
